package com.jaydizzle.buildingblocks.datagen.loot;

import com.jaydizzle.buildingblocks.block.*;
import com.jaydizzle.buildingblocks.block.custom.JDBlocks;
import net.minecraft.data.loot.BlockLootSubProvider;
import net.minecraft.world.flag.FeatureFlags;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.registries.RegistryObject;

import java.util.Set;

public class JDBlockLootTables extends BlockLootSubProvider {
    public JDBlockLootTables() {
        super(Set.of(), FeatureFlags.REGISTRY.allFlags());
    }

    @Override
    protected void generate() {
        //CUSTOM BLOCKS (37)
        this.dropSelf(JDBlocks.PINK_CALCITE.get());
        this.dropSelf(JDBlocks.PURPLE_CALCITE.get());
        this.dropSelf(JDBlocks.ORANGE_CALCITE.get());
        this.dropSelf(JDBlocks.LIGHT_BLUE_CALCITE.get());
        this.dropSelf(JDBlocks.YELLOW_CALCITE.get());
        this.dropSelf(JDBlocks.LIME_CALCITE.get());
        this.dropSelf(JDBlocks.BLUE_CALCITE.get());
        this.dropSelf(JDBlocks.LIGHT_GRAY_CALCITE.get());
        this.dropSelf(JDBlocks.MAGENTA_CALCITE.get());
        this.dropSelf(JDBlocks.GRAY_CALCITE.get());
        this.dropSelf(JDBlocks.BLUE_CONCRETE_BRICKS.get());
        this.dropSelf(JDBlocks.BROWN_CONCRETE_BRICKS.get());
        this.dropSelf(JDBlocks.CYAN_CONCRETE_BRICKS.get());
        this.dropSelf(JDBlocks.GRAY_CONCRETE_BRICKS.get());
        this.dropSelf(JDBlocks.GREEN_CONCRETE_BRICKS.get());
        this.dropSelf(JDBlocks.LIGHT_BLUE_CONCRETE_BRICKS.get());
        this.dropSelf(JDBlocks.LIGHT_GRAY_CONCRETE_BRICKS.get());
        this.dropSelf(JDBlocks.LIME_CONCRETE_BRICKS.get());
        this.dropSelf(JDBlocks.MAGENTA_CONCRETE_BRICKS.get());
        this.dropSelf(JDBlocks.ORANGE_CONCRETE_BRICKS.get());
        this.dropSelf(JDBlocks.PINK_CONCRETE_BRICKS.get());
        this.dropSelf(JDBlocks.PURPLE_CONCRETE_BRICKS.get());
        this.dropSelf(JDBlocks.RED_CONCRETE_BRICKS.get());
        this.dropSelf(JDBlocks.WHITE_CONCRETE_BRICKS.get());
        this.dropSelf(JDBlocks.YELLOW_CONCRETE_BRICKS.get());
        this.dropSelf(JDBlocks.YELLOW_BRICKS.get());
        this.dropSelf(JDBlocks.RED_BRICKS.get());
        this.dropSelf(JDBlocks.BLACK_BRICKS.get());
        this.dropSelf(JDBlocks.WHITE_BRICKS.get());
        this.dropSelf(JDBlocks.BROWN_BRICKS.get());
        this.dropSelf(JDBlocks.AQUA_BRICKS.get());
        this.dropSelf(JDBlocks.ORANGE_BRICKS.get());
        this.dropSelf(JDBlocks.GREEN_BRICKS.get());
        this.dropSelf(JDBlocks.GRAY_BRICKS.get());
        this.dropSelf(JDBlocks.BLUE_BRICKS.get());
        this.dropSelf(JDBlocks.PURPLE_BRICKS.get());
        this.dropSelf(JDBlocks.BASIC_BRICKS.get());

        //SLABS (111)
        this.add(JDSlabs.SPRUCE_LOG_SLAB.get(), block -> createSlabItemTable(JDSlabs.SPRUCE_LOG_SLAB.get()));
        this.add(JDSlabs.OAK_LOG_SLAB.get(), block -> createSlabItemTable(JDSlabs.OAK_LOG_SLAB.get()));
        this.add(JDSlabs.DARK_OAK_LOG_SLAB.get(), block -> createSlabItemTable(JDSlabs.DARK_OAK_LOG_SLAB.get()));
        this.add(JDSlabs.ACACIA_LOG_SLAB.get(), block -> createSlabItemTable(JDSlabs.ACACIA_LOG_SLAB.get()));
        this.add(JDSlabs.JUNGLE_LOG_SLAB.get(), block -> createSlabItemTable(JDSlabs.JUNGLE_LOG_SLAB.get()));
        this.add(JDSlabs.BIRCH_LOG_SLAB.get(), block -> createSlabItemTable(JDSlabs.BIRCH_LOG_SLAB.get()));
        this.add(JDSlabs.WARPED_LOG_SLAB.get(), block -> createSlabItemTable(JDSlabs.WARPED_LOG_SLAB.get()));
        this.add(JDSlabs.CRIMSON_LOG_SLAB.get(), block -> createSlabItemTable(JDSlabs.CRIMSON_LOG_SLAB.get()));
        this.add(JDSlabs.SPRUCE_SKINNED_LOG_SLAB.get(), block -> createSlabItemTable(JDSlabs.SPRUCE_SKINNED_LOG_SLAB.get()));
        this.add(JDSlabs.OAK_SKINNED_LOG_SLAB.get(), block -> createSlabItemTable(JDSlabs.OAK_SKINNED_LOG_SLAB.get()));
        this.add(JDSlabs.DARK_SKINNED_OAK_LOG_SLAB.get(), block -> createSlabItemTable(JDSlabs.DARK_SKINNED_OAK_LOG_SLAB.get()));
        this.add(JDSlabs.ACACIA_SKINNED_LOG_SLAB.get(), block -> createSlabItemTable(JDSlabs.ACACIA_SKINNED_LOG_SLAB.get()));
        this.add(JDSlabs.JUNGLE_SKINNED_LOG_SLAB.get(), block -> createSlabItemTable(JDSlabs.JUNGLE_SKINNED_LOG_SLAB.get()));
        this.add(JDSlabs.BIRCH_SKINNED_LOG_SLAB.get(), block -> createSlabItemTable(JDSlabs.BIRCH_SKINNED_LOG_SLAB.get()));
        this.add(JDSlabs.WARPED_SKINNED_LOG_SLAB.get(), block -> createSlabItemTable(JDSlabs.WARPED_SKINNED_LOG_SLAB.get()));
        this.add(JDSlabs.CRIMSON_SKINNED_LOG_SLAB.get(), block -> createSlabItemTable(JDSlabs.CRIMSON_SKINNED_LOG_SLAB.get()));
        this.add(JDSlabs.CALCITE_SLAB.get(), block -> createSlabItemTable(JDSlabs.CALCITE_SLAB.get()));
        this.add(JDSlabs.CLAY_SLAB.get(), block -> createSlabItemTable(JDSlabs.CLAY_SLAB.get()));
        this.add(JDSlabs.GRAVEL_SLAB.get(), block -> createSlabItemTable(JDSlabs.GRAVEL_SLAB.get()));
        this.add(JDSlabs.TUFF_SLAB.get(), block -> createSlabItemTable(JDSlabs.TUFF_SLAB.get()));
        this.add(JDSlabs.SAND_SLAB.get(), block -> createSlabItemTable(JDSlabs.SAND_SLAB.get()));
        this.add(JDSlabs.RED_SAND_SLAB.get(), block -> createSlabItemTable(JDSlabs.RED_SAND_SLAB.get()));
        this.add(JDSlabs.DIRT_SLAB.get(), block -> createSlabItemTable(JDSlabs.DIRT_SLAB.get()));
        this.add(JDSlabs.COARSE_DIRT_SLAB.get(), block -> createSlabItemTable(JDSlabs.COARSE_DIRT_SLAB.get()));
        this.add(JDSlabs.ROOTED_DIRT_SLAB.get(), block -> createSlabItemTable(JDSlabs.ROOTED_DIRT_SLAB.get()));
        this.add(JDSlabs.AMETHYST_SLAB.get(), block -> createSlabItemTable(JDSlabs.AMETHYST_SLAB.get()));
        this.add(JDSlabs.OBSIDIAN_SLAB.get(), block -> createSlabItemTable(JDSlabs.OBSIDIAN_SLAB.get()));
        this.add(JDSlabs.CRYING_OBSIDIAN_SLAB.get(), block -> createSlabItemTable(JDSlabs.CRYING_OBSIDIAN_SLAB.get()));
        this.add(JDSlabs.NETHERRACK_SLAB.get(), block -> createSlabItemTable(JDSlabs.NETHERRACK_SLAB.get()));
        this.add(JDSlabs.END_STONE_SLAB.get(), block -> createSlabItemTable(JDSlabs.END_STONE_SLAB.get()));
        this.add(JDSlabs.CHISELED_QUARTZ_SLAB.get(), block -> createSlabItemTable(JDSlabs.CHISELED_QUARTZ_SLAB.get()));
        this.add(JDSlabs.QUARTZ_BRICKS_SLAB.get(), block -> createSlabItemTable(JDSlabs.QUARTZ_BRICKS_SLAB.get()));
        this.add(JDSlabs.QUARTZ_PILLAR_SLAB.get(), block -> createSlabItemTable(JDSlabs.QUARTZ_PILLAR_SLAB.get()));
        this.add(JDSlabs.BONE_BLOCK_SLAB.get(), block -> createSlabItemTable(JDSlabs.BONE_BLOCK_SLAB.get()));
        this.add(JDSlabs.SMOOTH_BASALT_SLAB.get(), block -> createSlabItemTable(JDSlabs.SMOOTH_BASALT_SLAB.get()));
        this.add(JDSlabs.BASALT_SLAB.get(), block -> createSlabItemTable(JDSlabs.BASALT_SLAB.get()));
        this.add(JDSlabs.POLISHED_BASALT_SLAB.get(), block -> createSlabItemTable(JDSlabs.POLISHED_BASALT_SLAB.get()));
        this.add(JDSlabs.WHITE_WOOL_SLAB.get(), block -> createSlabItemTable(JDSlabs.WHITE_WOOL_SLAB.get()));
        this.add(JDSlabs.ORANGE_WOOL_SLAB.get(), block -> createSlabItemTable(JDSlabs.ORANGE_WOOL_SLAB.get()));
        this.add(JDSlabs.MAGENTA_WOOL_SLAB.get(), block -> createSlabItemTable(JDSlabs.MAGENTA_WOOL_SLAB.get()));
        this.add(JDSlabs.LIGHT_BLUE_WOOL_SLAB.get(), block -> createSlabItemTable(JDSlabs.LIGHT_BLUE_WOOL_SLAB.get()));
        this.add(JDSlabs.YELLOW_WOOL_SLAB.get(), block -> createSlabItemTable(JDSlabs.YELLOW_WOOL_SLAB.get()));
        this.add(JDSlabs.LIME_WOOL_SLAB.get(), block -> createSlabItemTable(JDSlabs.LIME_WOOL_SLAB.get()));
        this.add(JDSlabs.PINK_WOOL_SLAB.get(), block -> createSlabItemTable(JDSlabs.PINK_WOOL_SLAB.get()));
        this.add(JDSlabs.GRAY_WOOL_SLAB.get(), block -> createSlabItemTable(JDSlabs.GRAY_WOOL_SLAB.get()));
        this.add(JDSlabs.LIGHT_GRAY_WOOL_SLAB.get(), block -> createSlabItemTable(JDSlabs.LIGHT_GRAY_WOOL_SLAB.get()));
        this.add(JDSlabs.CYAN_WOOL_SLAB.get(), block -> createSlabItemTable(JDSlabs.CYAN_WOOL_SLAB.get()));
        this.add(JDSlabs.PURPLE_WOOL_SLAB.get(), block -> createSlabItemTable(JDSlabs.PURPLE_WOOL_SLAB.get()));
        this.add(JDSlabs.BLUE_WOOL_SLAB.get(), block -> createSlabItemTable(JDSlabs.BLUE_WOOL_SLAB.get()));
        this.add(JDSlabs.BROWN_WOOL_SLAB.get(), block -> createSlabItemTable(JDSlabs.BROWN_WOOL_SLAB.get()));
        this.add(JDSlabs.GREEN_WOOL_SLAB.get(), block -> createSlabItemTable(JDSlabs.GREEN_WOOL_SLAB.get()));
        this.add(JDSlabs.RED_WOOL_SLAB.get(), block -> createSlabItemTable(JDSlabs.RED_WOOL_SLAB.get()));
        this.add(JDSlabs.BLACK_WOOL_SLAB.get(), block -> createSlabItemTable(JDSlabs.BLACK_WOOL_SLAB.get()));
        this.add(JDSlabs.CRACKED_NETHER_BRICKS_SLAB.get(), block -> createSlabItemTable(JDSlabs.CRACKED_NETHER_BRICKS_SLAB.get()));
        this.add(JDSlabs.CHISELED_NETHER_BRICKS_SLAB.get(), block -> createSlabItemTable(JDSlabs.CHISELED_NETHER_BRICKS_SLAB.get()));
        this.add(JDSlabs.CHISELED_RED_SANDSTONE_SLAB.get(), block -> createSlabItemTable(JDSlabs.CHISELED_RED_SANDSTONE_SLAB.get()));
        this.add(JDSlabs.CHISELED_SANDSTONE_SLAB.get(), block -> createSlabItemTable(JDSlabs.CHISELED_SANDSTONE_SLAB.get()));
        this.add(JDSlabs.CHISELED_STONE_BRICKS_SLAB.get(), block -> createSlabItemTable(JDSlabs.CHISELED_STONE_BRICKS_SLAB.get()));
        this.add(JDSlabs.CRACKED_STONE_BRICKS_SLAB.get(), block -> createSlabItemTable(JDSlabs.CRACKED_STONE_BRICKS_SLAB.get()));
        this.add(JDSlabs.CRACKED_POLISHED_BLACKSTONE_BRICKS_SLAB.get(), block -> createSlabItemTable(JDSlabs.CRACKED_POLISHED_BLACKSTONE_BRICKS_SLAB.get()));
        this.add(JDSlabs.MOSS_BLOCK_SLAB.get(), block -> createSlabItemTable(JDSlabs.MOSS_BLOCK_SLAB.get()));
        this.add(JDSlabs.HONEYCOMB_BLOCK_SLAB.get(), block -> createSlabItemTable(JDSlabs.HONEYCOMB_BLOCK_SLAB.get()));
        this.add(JDSlabs.TERRACOTTA_SLAB.get(), block -> createSlabItemTable(JDSlabs.TERRACOTTA_SLAB.get()));
        this.add(JDSlabs.BLACK_TERRACOTTA_SLAB.get(), block -> createSlabItemTable(JDSlabs.BLACK_TERRACOTTA_SLAB.get()));
        this.add(JDSlabs.BLUE_TERRACOTTA_SLAB.get(), block -> createSlabItemTable(JDSlabs.BLUE_TERRACOTTA_SLAB.get()));
        this.add(JDSlabs.BROWN_TERRACOTTA_SLAB.get(), block -> createSlabItemTable(JDSlabs.BROWN_TERRACOTTA_SLAB.get()));
        this.add(JDSlabs.CYAN_TERRACOTTA_SLAB.get(), block -> createSlabItemTable(JDSlabs.CYAN_TERRACOTTA_SLAB.get()));
        this.add(JDSlabs.GRAY_TERRACOTTA_SLAB.get(), block -> createSlabItemTable(JDSlabs.GRAY_TERRACOTTA_SLAB.get()));
        this.add(JDSlabs.GREEN_TERRACOTTA_SLAB.get(), block -> createSlabItemTable(JDSlabs.GREEN_TERRACOTTA_SLAB.get()));
        this.add(JDSlabs.LIGHT_BLUE_TERRACOTTA_SLAB.get(), block -> createSlabItemTable(JDSlabs.LIGHT_BLUE_TERRACOTTA_SLAB.get()));
        this.add(JDSlabs.LIGHT_GRAY_TERRACOTTA_SLAB.get(), block -> createSlabItemTable(JDSlabs.LIGHT_GRAY_TERRACOTTA_SLAB.get()));
        this.add(JDSlabs.LIME_TERRACOTTA_SLAB.get(), block -> createSlabItemTable(JDSlabs.LIME_TERRACOTTA_SLAB.get()));
        this.add(JDSlabs.MAGENTA_TERRACOTTA_SLAB.get(), block -> createSlabItemTable(JDSlabs.MAGENTA_TERRACOTTA_SLAB.get()));
        this.add(JDSlabs.ORANGE_TERRACOTTA_SLAB.get(), block -> createSlabItemTable(JDSlabs.ORANGE_TERRACOTTA_SLAB.get()));
        this.add(JDSlabs.PINK_TERRACOTTA_SLAB.get(), block -> createSlabItemTable(JDSlabs.PINK_TERRACOTTA_SLAB.get()));
        this.add(JDSlabs.PURPLE_TERRACOTTA_SLAB.get(), block -> createSlabItemTable(JDSlabs.PURPLE_TERRACOTTA_SLAB.get()));
        this.add(JDSlabs.RED_TERRACOTTA_SLAB.get(), block -> createSlabItemTable(JDSlabs.RED_TERRACOTTA_SLAB.get()));
        this.add(JDSlabs.WHITE_TERRACOTTA_SLAB.get(), block -> createSlabItemTable(JDSlabs.WHITE_TERRACOTTA_SLAB.get()));
        this.add(JDSlabs.YELLOW_TERRACOTTA_SLAB.get(), block -> createSlabItemTable(JDSlabs.YELLOW_TERRACOTTA_SLAB.get()));
        this.add(JDSlabs.BLACK_CONCRETE_POWDER_SLAB.get(), block -> createSlabItemTable(JDSlabs.BLACK_CONCRETE_POWDER_SLAB.get()));
        this.add(JDSlabs.BLUE_CONCRETE_POWDER_SLAB.get(), block -> createSlabItemTable(JDSlabs.BLUE_CONCRETE_POWDER_SLAB.get()));
        this.add(JDSlabs.BROWN_CONCRETE_POWDER_SLAB.get(), block -> createSlabItemTable(JDSlabs.BROWN_CONCRETE_POWDER_SLAB.get()));
        this.add(JDSlabs.CYAN_CONCRETE_POWDER_SLAB.get(), block -> createSlabItemTable(JDSlabs.CYAN_CONCRETE_POWDER_SLAB.get()));
        this.add(JDSlabs.GRAY_CONCRETE_POWDER_SLAB.get(), block -> createSlabItemTable(JDSlabs.GRAY_CONCRETE_POWDER_SLAB.get()));
        this.add(JDSlabs.GREEN_CONCRETE_POWDER_SLAB.get(), block -> createSlabItemTable(JDSlabs.GREEN_CONCRETE_POWDER_SLAB.get()));
        this.add(JDSlabs.LIGHT_BLUE_CONCRETE_POWDER_SLAB.get(), block -> createSlabItemTable(JDSlabs.LIGHT_BLUE_CONCRETE_POWDER_SLAB.get()));
        this.add(JDSlabs.LIGHT_GRAY_CONCRETE_POWDER_SLAB.get(), block -> createSlabItemTable(JDSlabs.LIGHT_GRAY_CONCRETE_POWDER_SLAB.get()));
        this.add(JDSlabs.LIME_CONCRETE_POWDER_SLAB.get(), block -> createSlabItemTable(JDSlabs.LIME_CONCRETE_POWDER_SLAB.get()));
        this.add(JDSlabs.MAGENTA_CONCRETE_POWDER_SLAB.get(), block -> createSlabItemTable(JDSlabs.MAGENTA_CONCRETE_POWDER_SLAB.get()));
        this.add(JDSlabs.ORANGE_CONCRETE_POWDER_SLAB.get(), block -> createSlabItemTable(JDSlabs.ORANGE_CONCRETE_POWDER_SLAB.get()));
        this.add(JDSlabs.PINK_CONCRETE_POWDER_SLAB.get(), block -> createSlabItemTable(JDSlabs.PINK_CONCRETE_POWDER_SLAB.get()));
        this.add(JDSlabs.PURPLE_CONCRETE_POWDER_SLAB.get(), block -> createSlabItemTable(JDSlabs.PURPLE_CONCRETE_POWDER_SLAB.get()));
        this.add(JDSlabs.RED_CONCRETE_POWDER_SLAB.get(), block -> createSlabItemTable(JDSlabs.RED_CONCRETE_POWDER_SLAB.get()));
        this.add(JDSlabs.WHITE_CONCRETE_POWDER_SLAB.get(), block -> createSlabItemTable(JDSlabs.WHITE_CONCRETE_POWDER_SLAB.get()));
        this.add(JDSlabs.YELLOW_CONCRETE_POWDER_SLAB.get(), block -> createSlabItemTable(JDSlabs.YELLOW_CONCRETE_POWDER_SLAB.get()));
        this.add(JDSlabs.BLACK_CONCRETE_SLAB.get(), block -> createSlabItemTable(JDSlabs.BLACK_CONCRETE_SLAB.get()));
        this.add(JDSlabs.BLUE_CONCRETE_SLAB.get(), block -> createSlabItemTable(JDSlabs.BLUE_CONCRETE_SLAB.get()));
        this.add(JDSlabs.BROWN_CONCRETE_SLAB.get(), block -> createSlabItemTable(JDSlabs.BROWN_CONCRETE_SLAB.get()));
        this.add(JDSlabs.CYAN_CONCRETE_SLAB.get(), block -> createSlabItemTable(JDSlabs.CYAN_CONCRETE_SLAB.get()));
        this.add(JDSlabs.GRAY_CONCRETE_SLAB.get(), block -> createSlabItemTable(JDSlabs.GRAY_CONCRETE_SLAB.get()));
        this.add(JDSlabs.GREEN_CONCRETE_SLAB.get(), block -> createSlabItemTable(JDSlabs.GREEN_CONCRETE_SLAB.get()));
        this.add(JDSlabs.LIGHT_BLUE_CONCRETE_SLAB.get(), block -> createSlabItemTable(JDSlabs.LIGHT_BLUE_CONCRETE_SLAB.get()));
        this.add(JDSlabs.LIGHT_GRAY_CONCRETE_SLAB.get(), block -> createSlabItemTable(JDSlabs.LIGHT_GRAY_CONCRETE_SLAB.get()));
        this.add(JDSlabs.LIME_CONCRETE_SLAB.get(), block -> createSlabItemTable(JDSlabs.LIME_CONCRETE_SLAB.get()));
        this.add(JDSlabs.MAGENTA_CONCRETE_SLAB.get(), block -> createSlabItemTable(JDSlabs.MAGENTA_CONCRETE_SLAB.get()));
        this.add(JDSlabs.ORANGE_CONCRETE_SLAB.get(), block -> createSlabItemTable(JDSlabs.ORANGE_CONCRETE_SLAB.get()));
        this.add(JDSlabs.PINK_CONCRETE_SLAB.get(), block -> createSlabItemTable(JDSlabs.PINK_CONCRETE_SLAB.get()));
        this.add(JDSlabs.PURPLE_CONCRETE_SLAB.get(), block -> createSlabItemTable(JDSlabs.PURPLE_CONCRETE_SLAB.get()));
        this.add(JDSlabs.RED_CONCRETE_SLAB.get(), block -> createSlabItemTable(JDSlabs.RED_CONCRETE_SLAB.get()));
        this.add(JDSlabs.WHITE_CONCRETE_SLAB.get(), block -> createSlabItemTable(JDSlabs.WHITE_CONCRETE_SLAB.get()));
        this.add(JDSlabs.YELLOW_CONCRETE_SLAB.get(), block -> createSlabItemTable(JDSlabs.YELLOW_CONCRETE_SLAB.get()));

        //STAIRS (111)
        this.dropSelf(JDStairs.SPRUCE_LOG_STAIRS.get());
        this.dropSelf(JDStairs.OAK_LOG_STAIRS.get());
        this.dropSelf(JDStairs.DARK_OAK_LOG_STAIRS.get());
        this.dropSelf(JDStairs.ACACIA_LOG_STAIRS.get());
        this.dropSelf(JDStairs.JUNGLE_LOG_STAIRS.get());
        this.dropSelf(JDStairs.BIRCH_LOG_STAIRS.get());
        this.dropSelf(JDStairs.WARPED_LOG_STAIRS.get());
        this.dropSelf(JDStairs.CRIMSON_LOG_STAIRS.get());
        this.dropSelf(JDStairs.SPRUCE_SKINNED_LOG_STAIRS.get());
        this.dropSelf(JDStairs.OAK_SKINNED_LOG_STAIRS.get());
        this.dropSelf(JDStairs.DARK_OAK_SKINNED_LOG_STAIRS.get());
        this.dropSelf(JDStairs.ACACIA_SKINNED_LOG_STAIRS.get());
        this.dropSelf(JDStairs.JUNGLE_SKINNED_LOG_STAIRS.get());
        this.dropSelf(JDStairs.BIRCH_SKINNED_LOG_STAIRS.get());
        this.dropSelf(JDStairs.WARPED_SKINNED_LOG_STAIRS.get());
        this.dropSelf(JDStairs.CRIMSON_SKINNED_LOG_STAIRS.get());
        this.dropSelf(JDStairs.CALCITE_STAIRS.get());
        this.dropSelf(JDStairs.CLAY_STAIRS.get());
        this.dropSelf(JDStairs.GRAVEL_STAIRS.get());
        this.dropSelf(JDStairs.TUFF_STAIRS.get());
        this.dropSelf(JDStairs.SAND_STAIRS.get());
        this.dropSelf(JDStairs.RED_SAND_STAIRS.get());
        this.dropSelf(JDStairs.DIRT_STAIRS.get());
        this.dropSelf(JDStairs.COARSE_DIRT_STAIRS.get());
        this.dropSelf(JDStairs.ROOTED_DIRT_STAIRS.get());
        this.dropSelf(JDStairs.AMETHYST_STAIRS.get());
        this.dropSelf(JDStairs.OBSIDIAN_STAIRS.get());
        this.dropSelf(JDStairs.CRYING_OBSIDIAN_STAIRS.get());
        this.dropSelf(JDStairs.NETHERRACK_STAIRS.get());
        this.dropSelf(JDStairs.END_STONE_STAIRS.get());
        this.dropSelf(JDStairs.CHISELED_QUARTZ_STAIRS.get());
        this.dropSelf(JDStairs.QUARTZ_BRICKS_STAIRS.get());
        this.dropSelf(JDStairs.QUARTZ_PILLAR_STAIRS.get());
        this.dropSelf(JDStairs.BONE_BLOCK_STAIRS.get());
        this.dropSelf(JDStairs.SMOOTH_BASALT_STAIRS.get());
        this.dropSelf(JDStairs.BASALT_STAIRS.get());
        this.dropSelf(JDStairs.POLISHED_BASALT_STAIRS.get());
        this.dropSelf(JDStairs.WHITE_WOOL_STAIRS.get());
        this.dropSelf(JDStairs.ORANGE_WOOL_STAIRS.get());
        this.dropSelf(JDStairs.MAGENTA_WOOL_STAIRS.get());
        this.dropSelf(JDStairs.LIGHT_BLUE_WOOL_STAIRS.get());
        this.dropSelf(JDStairs.YELLOW_WOOL_STAIRS.get());
        this.dropSelf(JDStairs.LIME_WOOL_STAIRS.get());
        this.dropSelf(JDStairs.PINK_WOOL_STAIRS.get());
        this.dropSelf(JDStairs.GRAY_WOOL_STAIRS.get());
        this.dropSelf(JDStairs.LIGHT_GRAY_WOOL_STAIRS.get());
        this.dropSelf(JDStairs.CYAN_WOOL_STAIRS.get());
        this.dropSelf(JDStairs.PURPLE_WOOL_STAIRS.get());
        this.dropSelf(JDStairs.BLUE_WOOL_STAIRS.get());
        this.dropSelf(JDStairs.BROWN_WOOL_STAIRS.get());
        this.dropSelf(JDStairs.GREEN_WOOL_STAIRS.get());
        this.dropSelf(JDStairs.RED_WOOL_STAIRS.get());
        this.dropSelf(JDStairs.BLACK_WOOL_STAIRS.get());
        this.dropSelf(JDStairs.CRACKED_NETHER_BRICKS_STAIRS.get());
        this.dropSelf(JDStairs.CHISELED_NETHER_BRICKS_STAIRS.get());
        this.dropSelf(JDStairs.CHISELED_RED_SANDSTONE_STAIRS.get());
        this.dropSelf(JDStairs.CHISELED_SANDSTONE_STAIRS.get());
        this.dropSelf(JDStairs.CHISELED_STONE_BRICKS_STAIRS.get());
        this.dropSelf(JDStairs.CRACKED_STONE_BRICKS_STAIRS.get());
        this.dropSelf(JDStairs.CRACKED_POLISHED_BLACKSTONE_BRICKS_STAIRS.get());
        this.dropSelf(JDStairs.MOSS_BLOCK_STAIRS.get());
        this.dropSelf(JDStairs.HONEYCOMB_BLOCK_STAIRS.get());
        this.dropSelf(JDStairs.TERRACOTTA_STAIRS.get());
        this.dropSelf(JDStairs.BLACK_TERRACOTTA_STAIRS.get());
        this.dropSelf(JDStairs.BLUE_TERRACOTTA_STAIRS.get());
        this.dropSelf(JDStairs.BROWN_TERRACOTTA_STAIRS.get());
        this.dropSelf(JDStairs.CYAN_TERRACOTTA_STAIRS.get());
        this.dropSelf(JDStairs.GRAY_TERRACOTTA_STAIRS.get());
        this.dropSelf(JDStairs.GREEN_TERRACOTTA_STAIRS.get());
        this.dropSelf(JDStairs.LIGHT_BLUE_TERRACOTTA_STAIRS.get());
        this.dropSelf(JDStairs.LIGHT_GRAY_TERRACOTTA_STAIRS.get());
        this.dropSelf(JDStairs.LIME_TERRACOTTA_STAIRS.get());
        this.dropSelf(JDStairs.MAGENTA_TERRACOTTA_STAIRS.get());
        this.dropSelf(JDStairs.ORANGE_TERRACOTTA_STAIRS.get());
        this.dropSelf(JDStairs.PINK_TERRACOTTA_STAIRS.get());
        this.dropSelf(JDStairs.PURPLE_TERRACOTTA_STAIRS.get());
        this.dropSelf(JDStairs.RED_TERRACOTTA_STAIRS.get());
        this.dropSelf(JDStairs.WHITE_TERRACOTTA_STAIRS.get());
        this.dropSelf(JDStairs.YELLOW_TERRACOTTA_STAIRS.get());
        this.dropSelf(JDStairs.BLACK_CONCRETE_POWDER_STAIRS.get());
        this.dropSelf(JDStairs.BLUE_CONCRETE_POWDER_STAIRS.get());
        this.dropSelf(JDStairs.BROWN_CONCRETE_POWDER_STAIRS.get());
        this.dropSelf(JDStairs.CYAN_CONCRETE_POWDER_STAIRS.get());
        this.dropSelf(JDStairs.GRAY_CONCRETE_POWDER_STAIRS.get());
        this.dropSelf(JDStairs.GREEN_CONCRETE_POWDER_STAIRS.get());
        this.dropSelf(JDStairs.LIGHT_BLUE_CONCRETE_POWDER_STAIRS.get());
        this.dropSelf(JDStairs.LIGHT_GRAY_CONCRETE_POWDER_STAIRS.get());
        this.dropSelf(JDStairs.LIME_CONCRETE_POWDER_STAIRS.get());
        this.dropSelf(JDStairs.MAGENTA_CONCRETE_POWDER_STAIRS.get());
        this.dropSelf(JDStairs.ORANGE_CONCRETE_POWDER_STAIRS.get());
        this.dropSelf(JDStairs.PINK_CONCRETE_POWDER_STAIRS.get());
        this.dropSelf(JDStairs.PURPLE_CONCRETE_POWDER_STAIRS.get());
        this.dropSelf(JDStairs.RED_CONCRETE_POWDER_STAIRS.get());
        this.dropSelf(JDStairs.WHITE_CONCRETE_POWDER_STAIRS.get());
        this.dropSelf(JDStairs.YELLOW_CONCRETE_POWDER_STAIRS.get());
        this.dropSelf(JDStairs.BLACK_CONCRETE_STAIRS.get());
        this.dropSelf(JDStairs.BLUE_CONCRETE_STAIRS.get());
        this.dropSelf(JDStairs.BROWN_CONCRETE_STAIRS.get());
        this.dropSelf(JDStairs.CYAN_CONCRETE_STAIRS.get());
        this.dropSelf(JDStairs.GRAY_CONCRETE_STAIRS.get());
        this.dropSelf(JDStairs.GREEN_CONCRETE_STAIRS.get());
        this.dropSelf(JDStairs.LIGHT_BLUE_CONCRETE_STAIRS.get());
        this.dropSelf(JDStairs.LIGHT_GRAY_CONCRETE_STAIRS.get());
        this.dropSelf(JDStairs.LIME_CONCRETE_STAIRS.get());
        this.dropSelf(JDStairs.MAGENTA_CONCRETE_STAIRS.get());
        this.dropSelf(JDStairs.ORANGE_CONCRETE_STAIRS.get());
        this.dropSelf(JDStairs.PINK_CONCRETE_STAIRS.get());
        this.dropSelf(JDStairs.PURPLE_CONCRETE_STAIRS.get());
        this.dropSelf(JDStairs.RED_CONCRETE_STAIRS.get());
        this.dropSelf(JDStairs.WHITE_CONCRETE_STAIRS.get());
        this.dropSelf(JDStairs.YELLOW_CONCRETE_STAIRS.get());

        //WALLS (128)
        this.dropSelf(JDWalls.SPRUCE_LOG_WALL.get());
        this.dropSelf(JDWalls.OAK_LOG_WALL.get());
        this.dropSelf(JDWalls.DARK_OAK_LOG_WALL.get());
        this.dropSelf(JDWalls.ACACIA_LOG_WALL.get());
        this.dropSelf(JDWalls.JUNGLE_LOG_WALL.get());
        this.dropSelf(JDWalls.BIRCH_LOG_WALL.get());
        this.dropSelf(JDWalls.WARPED_LOG_WALL.get());
        this.dropSelf(JDWalls.CRIMSON_LOG_WALL.get());
        this.dropSelf(JDWalls.SPRUCE_SKINNED_LOG_WALL.get());
        this.dropSelf(JDWalls.OAK_SKINNED_LOG_WALL.get());
        this.dropSelf(JDWalls.DARK_SKINNED_OAK_LOG_WALL.get());
        this.dropSelf(JDWalls.ACACIA_SKINNED_LOG_WALL.get());
        this.dropSelf(JDWalls.JUNGLE_SKINNED_LOG_WALL.get());
        this.dropSelf(JDWalls.BIRCH_SKINNED_LOG_WALL.get());
        this.dropSelf(JDWalls.WARPED_SKINNED_LOG_WALL.get());
        this.dropSelf(JDWalls.CRIMSON_SKINNED_LOG_WALL.get());
        this.dropSelf(JDWalls.CALCITE_WALL.get());
        this.dropSelf(JDWalls.CLAY_WALL.get());
        this.dropSelf(JDWalls.GRAVEL_WALL.get());
        this.dropSelf(JDWalls.TUFF_WALL.get());
        this.dropSelf(JDWalls.SAND_WALL.get());
        this.dropSelf(JDWalls.RED_SAND_WALL.get());
        this.dropSelf(JDWalls.DIRT_WALL.get());
        this.dropSelf(JDWalls.COARSE_DIRT_WALL.get());
        this.dropSelf(JDWalls.ROOTED_DIRT_WALL.get());
        this.dropSelf(JDWalls.AMETHYST_WALL.get());
        this.dropSelf(JDWalls.OBSIDIAN_WALL.get());
        this.dropSelf(JDWalls.CRYING_OBSIDIAN_WALL.get());
        this.dropSelf(JDWalls.NETHERRACK_WALL.get());
        this.dropSelf(JDWalls.END_STONE_WALL.get());
        this.dropSelf(JDWalls.CHISELED_QUARTZ_WALL.get());
        this.dropSelf(JDWalls.QUARTZ_BRICKS_WALL.get());
        this.dropSelf(JDWalls.QUARTZ_PILLAR_WALL.get());
        this.dropSelf(JDWalls.BONE_BLOCK_WALL.get());
        this.dropSelf(JDWalls.SMOOTH_BASALT_WALL.get());
        this.dropSelf(JDWalls.BASALT_WALL.get());
        this.dropSelf(JDWalls.POLISHED_BASALT_WALL.get());
        this.dropSelf(JDWalls.WHITE_WOOL_WALL.get());
        this.dropSelf(JDWalls.ORANGE_WOOL_WALL.get());
        this.dropSelf(JDWalls.MAGENTA_WOOL_WALL.get());
        this.dropSelf(JDWalls.LIGHT_BLUE_WOOL_WALL.get());
        this.dropSelf(JDWalls.YELLOW_WOOL_WALL.get());
        this.dropSelf(JDWalls.LIME_WOOL_WALL.get());
        this.dropSelf(JDWalls.PINK_WOOL_WALL.get());
        this.dropSelf(JDWalls.GRAY_WOOL_WALL.get());
        this.dropSelf(JDWalls.LIGHT_GRAY_WOOL_WALL.get());
        this.dropSelf(JDWalls.CYAN_WOOL_WALL.get());
        this.dropSelf(JDWalls.PURPLE_WOOL_WALL.get());
        this.dropSelf(JDWalls.BLUE_WOOL_WALL.get());
        this.dropSelf(JDWalls.BROWN_WOOL_WALL.get());
        this.dropSelf(JDWalls.GREEN_WOOL_WALL.get());
        this.dropSelf(JDWalls.RED_WOOL_WALL.get());
        this.dropSelf(JDWalls.BLACK_WOOL_WALL.get());
        this.dropSelf(JDWalls.CRACKED_NETHER_BRICKS_WALL.get());
        this.dropSelf(JDWalls.CHISELED_NETHER_BRICKS_WALL.get());
        this.dropSelf(JDWalls.CHISELED_RED_SANDSTONE_WALL.get());
        this.dropSelf(JDWalls.CHISELED_SANDSTONE_WALL.get());
        this.dropSelf(JDWalls.CHISELED_STONE_BRICKS_WALL.get());
        this.dropSelf(JDWalls.CRACKED_STONE_BRICKS_WALL.get());
        this.dropSelf(JDWalls.CRACKED_POLISHED_BLACKSTONE_BRICKS_WALL.get());
        this.dropSelf(JDWalls.MOSS_BLOCK_WALL.get());
        this.dropSelf(JDWalls.HONEYCOMB_BLOCK_WALL.get());
        this.dropSelf(JDWalls.TERRACOTTA_WALL.get());
        this.dropSelf(JDWalls.BLACK_TERRACOTTA_WALL.get());
        this.dropSelf(JDWalls.BLUE_TERRACOTTA_WALL.get());
        this.dropSelf(JDWalls.BROWN_TERRACOTTA_WALL.get());
        this.dropSelf(JDWalls.CYAN_TERRACOTTA_WALL.get());
        this.dropSelf(JDWalls.GRAY_TERRACOTTA_WALL.get());
        this.dropSelf(JDWalls.GREEN_TERRACOTTA_WALL.get());
        this.dropSelf(JDWalls.LIGHT_BLUE_TERRACOTTA_WALL.get());
        this.dropSelf(JDWalls.LIGHT_GRAY_TERRACOTTA_WALL.get());
        this.dropSelf(JDWalls.LIME_TERRACOTTA_WALL.get());
        this.dropSelf(JDWalls.MAGENTA_TERRACOTTA_WALL.get());
        this.dropSelf(JDWalls.ORANGE_TERRACOTTA_WALL.get());
        this.dropSelf(JDWalls.PINK_TERRACOTTA_WALL.get());
        this.dropSelf(JDWalls.PURPLE_TERRACOTTA_WALL.get());
        this.dropSelf(JDWalls.RED_TERRACOTTA_WALL.get());
        this.dropSelf(JDWalls.WHITE_TERRACOTTA_WALL.get());
        this.dropSelf(JDWalls.YELLOW_TERRACOTTA_WALL.get());
        this.dropSelf(JDWalls.BLACK_CONCRETE_POWDER_WALL.get());
        this.dropSelf(JDWalls.BLUE_CONCRETE_POWDER_WALL.get());
        this.dropSelf(JDWalls.BROWN_CONCRETE_POWDER_WALL.get());
        this.dropSelf(JDWalls.CYAN_CONCRETE_POWDER_WALL.get());
        this.dropSelf(JDWalls.GRAY_CONCRETE_POWDER_WALL.get());
        this.dropSelf(JDWalls.GREEN_CONCRETE_POWDER_WALL.get());
        this.dropSelf(JDWalls.LIGHT_BLUE_CONCRETE_POWDER_WALL.get());
        this.dropSelf(JDWalls.LIGHT_GRAY_CONCRETE_POWDER_WALL.get());
        this.dropSelf(JDWalls.LIME_CONCRETE_POWDER_WALL.get());
        this.dropSelf(JDWalls.MAGENTA_CONCRETE_POWDER_WALL.get());
        this.dropSelf(JDWalls.ORANGE_CONCRETE_POWDER_WALL.get());
        this.dropSelf(JDWalls.PINK_CONCRETE_POWDER_WALL.get());
        this.dropSelf(JDWalls.PURPLE_CONCRETE_POWDER_WALL.get());
        this.dropSelf(JDWalls.RED_CONCRETE_POWDER_WALL.get());
        this.dropSelf(JDWalls.WHITE_CONCRETE_POWDER_WALL.get());
        this.dropSelf(JDWalls.YELLOW_CONCRETE_POWDER_WALL.get());
        this.dropSelf(JDWalls.BLACK_CONCRETE_WALL.get());
        this.dropSelf(JDWalls.BLUE_CONCRETE_WALL.get());
        this.dropSelf(JDWalls.BROWN_CONCRETE_WALL.get());
        this.dropSelf(JDWalls.CYAN_CONCRETE_WALL.get());
        this.dropSelf(JDWalls.GRAY_CONCRETE_WALL.get());
        this.dropSelf(JDWalls.GREEN_CONCRETE_WALL.get());
        this.dropSelf(JDWalls.LIGHT_BLUE_CONCRETE_WALL.get());
        this.dropSelf(JDWalls.LIGHT_GRAY_CONCRETE_WALL.get());
        this.dropSelf(JDWalls.LIME_CONCRETE_WALL.get());
        this.dropSelf(JDWalls.MAGENTA_CONCRETE_WALL.get());
        this.dropSelf(JDWalls.ORANGE_CONCRETE_WALL.get());
        this.dropSelf(JDWalls.PINK_CONCRETE_WALL.get());
        this.dropSelf(JDWalls.PURPLE_CONCRETE_WALL.get());
        this.dropSelf(JDWalls.RED_CONCRETE_WALL.get());
        this.dropSelf(JDWalls.WHITE_CONCRETE_WALL.get());
        this.dropSelf(JDWalls.YELLOW_CONCRETE_WALL.get());
        this.dropSelf(JDWalls.MANGROVE_PLANK_WALL.get());
        this.dropSelf(JDWalls.OAK_PLANK_WALL.get());
        this.dropSelf(JDWalls.DARK_OAK_PLANK_WALL.get());
        this.dropSelf(JDWalls.SPRUCE_PLANK_WALL.get());
        this.dropSelf(JDWalls.JUNGLE_PLANK_WALL.get());
        this.dropSelf(JDWalls.ACACIA_PLANK_WALL.get());
        this.dropSelf(JDWalls.BIRCH_PLANK_WALL.get());
        this.dropSelf(JDWalls.CRIMSON_PLANK_WALL.get());
        this.dropSelf(JDWalls.WARPED_PLANK_WALL.get());
        this.dropSelf(JDWalls.MANGROVE_LOG_WALL.get());
        this.dropSelf(JDWalls.PACKED_MUD_WALL.get());
        this.dropSelf(JDWalls.MUDDY_MANGROVE_ROOTS_WALL.get());
        this.dropSelf(JDWalls.STRIPPED_MANGROVE_LOG_WALL.get());
        this.dropSelf(JDWalls.MUD_WALL.get());
        this.dropSelf(JDWalls.OCHRE_FROGLIGHT_WALL.get());
        this.dropSelf(JDWalls.VERDANT_FROGLIGHT_WALL.get());
        this.dropSelf(JDWalls.PEARLESCENT_FROGLIGHT_WALL.get());

        //FENCES (16)
        this.dropSelf(JDFences.SPRUCE_LOG_FENCE.get());
        this.dropSelf(JDFences.OAK_LOG_FENCE.get());
        this.dropSelf(JDFences.DARK_OAK_LOG_FENCE.get());
        this.dropSelf(JDFences.ACACIA_LOG_FENCE.get());
        this.dropSelf(JDFences.JUNGLE_LOG_FENCE.get());
        this.dropSelf(JDFences.BIRCH_LOG_FENCE.get());
        this.dropSelf(JDFences.WARPED_LOG_FENCE.get());
        this.dropSelf(JDFences.CRIMSON_LOG_FENCE.get());
        this.dropSelf(JDFences.SPRUCE_SKINNED_LOG_FENCE.get());
        this.dropSelf(JDFences.OAK_SKINNED_LOG_FENCE.get());
        this.dropSelf(JDFences.DARK_SKINNED_OAK_LOG_FENCE.get());
        this.dropSelf(JDFences.ACACIA_SKINNED_LOG_FENCE.get());
        this.dropSelf(JDFences.JUNGLE_SKINNED_LOG_FENCE.get());
        this.dropSelf(JDFences.BIRCH_SKINNED_LOG_FENCE.get());
        this.dropSelf(JDFences.WARPED_SKINNED_LOG_FENCE.get());
        this.dropSelf(JDFences.CRIMSON_SKINNED_LOG_FENCE.get());

        //FENCE GATES (16)
        this.dropSelf(JDFenceGates.SPRUCE_LOG_FENCE_GATE.get());
        this.dropSelf(JDFenceGates.OAK_LOG_FENCE_GATE.get());
        this.dropSelf(JDFenceGates.DARK_OAK_LOG_FENCE_GATE.get());
        this.dropSelf(JDFenceGates.ACACIA_LOG_FENCE_GATE.get());
        this.dropSelf(JDFenceGates.JUNGLE_LOG_FENCE_GATE.get());
        this.dropSelf(JDFenceGates.BIRCH_LOG_FENCE_GATE.get());
        this.dropSelf(JDFenceGates.WARPED_LOG_FENCE_GATE.get());
        this.dropSelf(JDFenceGates.CRIMSON_LOG_FENCE_GATE.get());
        this.dropSelf(JDFenceGates.SPRUCE_SKINNED_LOG_FENCE_GATE.get());
        this.dropSelf(JDFenceGates.OAK_SKINNED_LOG_FENCE_GATE.get());
        this.dropSelf(JDFenceGates.DARK_SKINNED_OAK_LOG_FENCE_GATE.get());
        this.dropSelf(JDFenceGates.ACACIA_SKINNED_LOG_FENCE_GATE.get());
        this.dropSelf(JDFenceGates.JUNGLE_SKINNED_LOG_FENCE_GATE.get());
        this.dropSelf(JDFenceGates.BIRCH_SKINNED_LOG_FENCE_GATE.get());
        this.dropSelf(JDFenceGates.WARPED_SKINNED_LOG_FENCE_GATE.get());
        this.dropSelf(JDFenceGates.CRIMSON_SKINNED_LOG_FENCE_GATE.get());

    }

    @Override
    protected Iterable<Block> getKnownBlocks() {
        return JDBlocks.BLOCKS.getEntries().stream().map(RegistryObject::get)::iterator;

    }
}