package com.jaydizzle.buildingblocks.block;

import com.jaydizzle.buildingblocks.BuildingBlocks;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.StairBlock;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.function.Supplier;

public class JDStairs {
    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, BuildingBlocks.MOD_ID);
    public static final RegistryObject<Block> SPRUCE_LOG_STAIRS = registerBlock("spruce_log_stairs", () -> new StairBlock(Blocks.SPRUCE_STAIRS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.SPRUCE_STAIRS).sound(SoundType.WOOD).strength(2f, 2f)));
    public static final RegistryObject<Block> OAK_LOG_STAIRS = registerBlock("oak_log_stairs", () -> new StairBlock(Blocks.OAK_STAIRS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.OAK_STAIRS).sound(SoundType.WOOD).strength(2f, 2f)));
    public static final RegistryObject<Block> DARK_OAK_LOG_STAIRS = registerBlock("dark_oak_log_stairs", () -> new StairBlock(Blocks.DARK_OAK_STAIRS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.DARK_OAK_STAIRS).sound(SoundType.WOOD).strength(2f, 2f)));
    public static final RegistryObject<Block> ACACIA_LOG_STAIRS = registerBlock("acacia_log_stairs", () -> new StairBlock(Blocks.ACACIA_STAIRS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.ACACIA_STAIRS).sound(SoundType.WOOD).strength(2f, 2f)));
    public static final RegistryObject<Block> JUNGLE_LOG_STAIRS = registerBlock("jungle_log_stairs", () -> new StairBlock(Blocks.JUNGLE_STAIRS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.JUNGLE_STAIRS).sound(SoundType.WOOD).strength(2f, 2f)));
    public static final RegistryObject<Block> BIRCH_LOG_STAIRS = registerBlock("birch_log_stairs", () -> new StairBlock(Blocks.BIRCH_STAIRS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.BIRCH_STAIRS).sound(SoundType.WOOD).strength(2f, 2f)));
    public static final RegistryObject<Block> WARPED_LOG_STAIRS = registerBlock("warped_log_stairs", () -> new StairBlock(Blocks.WARPED_STAIRS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.WARPED_STAIRS).sound(SoundType.STEM).strength(2f, 2f)));
    public static final RegistryObject<Block> CRIMSON_LOG_STAIRS = registerBlock("crimson_log_stairs", () -> new StairBlock(Blocks.CRIMSON_STAIRS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.CRIMSON_STAIRS).sound(SoundType.STEM).strength(2f, 2f)));
    public static final RegistryObject<Block> SPRUCE_SKINNED_LOG_STAIRS = registerBlock("spruce_skinned_log_stairs", () -> new StairBlock(Blocks.SPRUCE_STAIRS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.SPRUCE_STAIRS).sound(SoundType.WOOD).strength(2f, 2f)));
    public static final RegistryObject<Block> OAK_SKINNED_LOG_STAIRS = registerBlock("oak_skinned_log_stairs", () -> new StairBlock(Blocks.OAK_STAIRS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.OAK_STAIRS).sound(SoundType.WOOD).strength(2f, 2f)));
    public static final RegistryObject<Block> DARK_OAK_SKINNED_LOG_STAIRS = registerBlock("dark_oak_skinned_log_stairs", () -> new StairBlock(Blocks.DARK_OAK_STAIRS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.DARK_OAK_STAIRS).sound(SoundType.WOOD).strength(2f, 2f)));
    public static final RegistryObject<Block> ACACIA_SKINNED_LOG_STAIRS = registerBlock("acacia_skinned_log_stairs", () -> new StairBlock(Blocks.ACACIA_STAIRS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.ACACIA_STAIRS).sound(SoundType.WOOD).strength(2f, 2f)));
    public static final RegistryObject<Block> JUNGLE_SKINNED_LOG_STAIRS = registerBlock("jungle_skinned_log_stairs", () -> new StairBlock(Blocks.JUNGLE_STAIRS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.JUNGLE_STAIRS).sound(SoundType.WOOD).strength(2f, 2f)));
    public static final RegistryObject<Block> BIRCH_SKINNED_LOG_STAIRS = registerBlock("birch_skinned_log_stairs", () -> new StairBlock(Blocks.BIRCH_STAIRS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.BIRCH_STAIRS).sound(SoundType.WOOD).strength(2f, 2f)));
    public static final RegistryObject<Block> WARPED_SKINNED_LOG_STAIRS = registerBlock("warped_skinned_log_stairs", () -> new StairBlock(Blocks.WARPED_STAIRS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.WARPED_STAIRS).sound(SoundType.STEM).strength(2f, 2f)));
    public static final RegistryObject<Block> CRIMSON_SKINNED_LOG_STAIRS = registerBlock("crimson_skinned_log_stairs", () -> new StairBlock(Blocks.CRIMSON_STAIRS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.CRIMSON_STAIRS).sound(SoundType.STEM).strength(2f, 2f)));
    public static final RegistryObject<Block> CALCITE_STAIRS = registerBlock("calcite_stairs", () -> new StairBlock(Blocks.CALCITE::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.CALCITE).sound(SoundType.CALCITE).strength(0.75f, 0.75f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> CLAY_STAIRS = registerBlock("clay_stairs", () -> new StairBlock(Blocks.CLAY::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.CLAY).sound(SoundType.GRAVEL).strength(0.6f, 0.6f)));
    public static final RegistryObject<Block> GRAVEL_STAIRS = registerBlock("gravel_stairs", () -> new StairBlock(Blocks.GRAVEL::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.GRAVEL).sound(SoundType.GRAVEL).strength(0.6f, 0.6f)));
    public static final RegistryObject<Block> TUFF_STAIRS = registerBlock("tuff_stairs", () -> new StairBlock(Blocks.TUFF::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.TUFF).sound(SoundType.TUFF).strength(1.5f, 6f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> SAND_STAIRS = registerBlock("sand_stairs", () -> new StairBlock(Blocks.SAND::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.SAND).sound(SoundType.SAND).strength(0.5f, 0.5f)));
    public static final RegistryObject<Block> RED_SAND_STAIRS = registerBlock("red_sand_stairs", () -> new StairBlock(Blocks.RED_SAND::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.RED_SAND).sound(SoundType.SAND).strength(0.5f, 0.5f)));
    public static final RegistryObject<Block> DIRT_STAIRS = registerBlock("dirt_stairs", () -> new StairBlock(Blocks.DIRT::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.DIRT).sound(SoundType.GRAVEL).strength(0.5f, 0.5f)));
    public static final RegistryObject<Block> COARSE_DIRT_STAIRS = registerBlock("coarse_dirt_stairs", () -> new StairBlock(Blocks.COARSE_DIRT::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.COARSE_DIRT).sound(SoundType.GRAVEL).strength(0.5f, 0.5f)));
    public static final RegistryObject<Block> ROOTED_DIRT_STAIRS = registerBlock("rooted_dirt_stairs", () -> new StairBlock(Blocks.ROOTED_DIRT::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.ROOTED_DIRT).sound(SoundType.ROOTED_DIRT).strength(0.5f, 0.1f)));
    public static final RegistryObject<Block> AMETHYST_STAIRS = registerBlock("amethyst_stairs", () -> new StairBlock(Blocks.AMETHYST_BLOCK::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.AMETHYST_BLOCK).sound(SoundType.AMETHYST).strength(1.5f, 1.5f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> OBSIDIAN_STAIRS = registerBlock("obsidian_stairs", () -> new StairBlock(Blocks.OBSIDIAN::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.OBSIDIAN).sound(SoundType.STONE).strength(50f, 1200f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> CRYING_OBSIDIAN_STAIRS = registerBlock("crying_obsidian_stairs", () -> new StairBlock(Blocks.CRYING_OBSIDIAN::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.CRYING_OBSIDIAN).sound(SoundType.STONE).strength(50f, 1200f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> NETHERRACK_STAIRS = registerBlock("netherrack_stairs", () -> new StairBlock(Blocks.NETHERRACK::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.NETHERRACK).sound(SoundType.NETHERRACK).strength(0.4f, 0.4f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> END_STONE_STAIRS = registerBlock("end_stone_stairs", () -> new StairBlock(Blocks.END_STONE::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.END_STONE).sound(SoundType.STONE).strength(3f, 9f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> CHISELED_QUARTZ_STAIRS = registerBlock("chiseled_quartz_stairs", () -> new StairBlock(Blocks.CHISELED_QUARTZ_BLOCK::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.CHISELED_QUARTZ_BLOCK).sound(SoundType.STONE).strength(0.8f, 4f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> QUARTZ_BRICKS_STAIRS = registerBlock("quartz_bricks_stairs", () -> new StairBlock(Blocks.QUARTZ_BRICKS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.QUARTZ_BRICKS).sound(SoundType.STONE).strength(0.8f, 4f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> QUARTZ_PILLAR_STAIRS = registerBlock("quartz_pillar_stairs", () -> new StairBlock(Blocks.QUARTZ_PILLAR::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.QUARTZ_PILLAR).sound(SoundType.STONE).strength(0.8f, 4f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> BONE_BLOCK_STAIRS = registerBlock("bone_block_stairs", () -> new StairBlock(Blocks.BONE_BLOCK::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.BONE_BLOCK).sound(SoundType.BONE_BLOCK).strength(2f, 2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> SMOOTH_BASALT_STAIRS = registerBlock("smooth_basalt_stairs", () -> new StairBlock(Blocks.SMOOTH_BASALT::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.SMOOTH_BASALT).sound(SoundType.BASALT).strength(1.25f, 4.2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> BASALT_STAIRS = registerBlock("basalt_stairs", () -> new StairBlock(Blocks.BASALT::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.BASALT).sound(SoundType.BASALT).strength(1.25f, 4.2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> POLISHED_BASALT_STAIRS = registerBlock("polished_basalt_stairs", () -> new StairBlock(Blocks.POLISHED_BASALT::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.POLISHED_BASALT).sound(SoundType.BASALT).strength(1.25f, 4.2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> HONEYCOMB_BLOCK_STAIRS = registerBlock("honeycomb_block_stairs", () -> new StairBlock(Blocks.HONEYCOMB_BLOCK::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.HONEYCOMB_BLOCK).sound(SoundType.CORAL_BLOCK).strength(0.6f, 0.6f)));
    public static final RegistryObject<Block> WHITE_WOOL_STAIRS = registerBlock("white_wool_stairs", () -> new StairBlock(Blocks.WHITE_WOOL::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.WHITE_WOOL).sound(SoundType.WOOL).strength(0.8f, 0.8f)));
    public static final RegistryObject<Block> ORANGE_WOOL_STAIRS = registerBlock("orange_wool_stairs", () -> new StairBlock(Blocks.ORANGE_WOOL::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.ORANGE_WOOL).sound(SoundType.WOOL).strength(0.8f, 0.8f)));
    public static final RegistryObject<Block> MAGENTA_WOOL_STAIRS = registerBlock("magenta_wool_stairs", () -> new StairBlock(Blocks.MAGENTA_WOOL::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.MAGENTA_WOOL).sound(SoundType.WOOL).strength(0.8f, 0.8f)));
    public static final RegistryObject<Block> LIGHT_BLUE_WOOL_STAIRS = registerBlock("light_blue_wool_stairs", () -> new StairBlock(Blocks.LIGHT_BLUE_WOOL::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.LIGHT_BLUE_WOOL).sound(SoundType.WOOL).strength(0.8f, 0.8f)));
    public static final RegistryObject<Block> YELLOW_WOOL_STAIRS = registerBlock("yellow_wool_stairs", () -> new StairBlock(Blocks.YELLOW_WOOL::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.YELLOW_WOOL).sound(SoundType.WOOL).strength(0.8f, 0.8f)));
    public static final RegistryObject<Block> LIME_WOOL_STAIRS = registerBlock("lime_wool_stairs", () -> new StairBlock(Blocks.LIME_WOOL::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.LIME_WOOL).sound(SoundType.WOOL).strength(0.8f, 0.8f)));
    public static final RegistryObject<Block> PINK_WOOL_STAIRS = registerBlock("pink_wool_stairs", () -> new StairBlock(Blocks.PINK_WOOL::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.PINK_WOOL).sound(SoundType.WOOL).strength(0.8f, 0.8f)));
    public static final RegistryObject<Block> GRAY_WOOL_STAIRS = registerBlock("gray_wool_stairs", () -> new StairBlock(Blocks.GRAY_WOOL::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.GRAY_WOOL).sound(SoundType.WOOL).strength(0.8f, 0.8f)));
    public static final RegistryObject<Block> LIGHT_GRAY_WOOL_STAIRS = registerBlock("light_gray_wool_stairs", () -> new StairBlock(Blocks.LIGHT_GRAY_WOOL::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.LIGHT_GRAY_WOOL).sound(SoundType.WOOL).strength(0.8f, 0.8f)));
    public static final RegistryObject<Block> CYAN_WOOL_STAIRS = registerBlock("cyan_wool_stairs", () -> new StairBlock(Blocks.CYAN_WOOL::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.CYAN_WOOL).sound(SoundType.WOOL).strength(0.8f, 0.8f)));
    public static final RegistryObject<Block> PURPLE_WOOL_STAIRS = registerBlock("purple_wool_stairs", () -> new StairBlock(Blocks.PURPLE_WOOL::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.PURPLE_WOOL).sound(SoundType.WOOL).strength(0.8f, 0.8f)));
    public static final RegistryObject<Block> BLUE_WOOL_STAIRS = registerBlock("blue_wool_stairs", () -> new StairBlock(Blocks.BLUE_WOOL::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.BLUE_WOOL).sound(SoundType.WOOL).strength(0.8f, 0.8f)));
    public static final RegistryObject<Block> BROWN_WOOL_STAIRS = registerBlock("brown_wool_stairs", () -> new StairBlock(Blocks.BROWN_WOOL::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.BROWN_WOOL).sound(SoundType.WOOL).strength(0.8f, 0.8f)));
    public static final RegistryObject<Block> GREEN_WOOL_STAIRS = registerBlock("green_wool_stairs", () -> new StairBlock(Blocks.GREEN_WOOL::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.GREEN_WOOL).sound(SoundType.WOOL).strength(0.8f, 0.8f)));
    public static final RegistryObject<Block> RED_WOOL_STAIRS = registerBlock("red_wool_stairs", () -> new StairBlock(Blocks.RED_WOOL::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.RED_WOOL).sound(SoundType.WOOL).strength(0.8f, 0.8f)));
    public static final RegistryObject<Block> BLACK_WOOL_STAIRS = registerBlock("black_wool_stairs", () -> new StairBlock(Blocks.BLACK_WOOL::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.BLACK_WOOL).sound(SoundType.WOOL).strength(0.8f, 0.8f)));
    public static final RegistryObject<Block> CRACKED_NETHER_BRICKS_STAIRS = registerBlock("cracked_nether_bricks_stairs", () -> new StairBlock(Blocks.CRACKED_NETHER_BRICKS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.CRACKED_NETHER_BRICKS).sound(SoundType.NETHER_BRICKS).strength(2f, 6f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> CHISELED_NETHER_BRICKS_STAIRS = registerBlock("chiseled_nether_bricks_stairs", () -> new StairBlock(Blocks.CHISELED_NETHER_BRICKS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.CHISELED_NETHER_BRICKS).sound(SoundType.NETHER_BRICKS).strength(2f, 6f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> MOSS_BLOCK_STAIRS = registerBlock("moss_block_stairs", () -> new StairBlock(Blocks.MOSS_BLOCK::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.MOSS_BLOCK).sound(SoundType.MOSS).strength(0.1f, 0.1f)));
    public static final RegistryObject<Block> CRACKED_POLISHED_BLACKSTONE_BRICKS_STAIRS = registerBlock("cracked_polished_blackstone_bricks_stairs", () -> new StairBlock(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS).sound(SoundType.STONE).strength(1.5f, 6f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> CHISELED_RED_SANDSTONE_STAIRS = registerBlock("chiseled_red_sandstone_stairs", () -> new StairBlock(Blocks.CHISELED_RED_SANDSTONE::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.CHISELED_RED_SANDSTONE).sound(SoundType.STONE).strength(0.8f, 0.8f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> CHISELED_SANDSTONE_STAIRS = registerBlock("chiseled_sandstone_stairs", () -> new StairBlock(Blocks.CHISELED_SANDSTONE::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.CHISELED_SANDSTONE).sound(SoundType.STONE).strength(0.8f, 0.8f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> CHISELED_STONE_BRICKS_STAIRS = registerBlock("chiseled_stone_bricks_stairs", () -> new StairBlock(Blocks.CHISELED_STONE_BRICKS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.CHISELED_STONE_BRICKS).sound(SoundType.STONE).strength(1.5f, 6f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> CRACKED_STONE_BRICKS_STAIRS = registerBlock("cracked_stone_bricks_stairs", () -> new StairBlock(Blocks.CRACKED_STONE_BRICKS::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.CRACKED_STONE_BRICKS).sound(SoundType.STONE).strength(1.5f, 6f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> TERRACOTTA_STAIRS = registerBlock("terracotta_stairs", () -> new StairBlock(Blocks.TERRACOTTA::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.TERRACOTTA).sound(SoundType.STONE).strength(1.25f, 4.2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> BLACK_TERRACOTTA_STAIRS = registerBlock("black_terracotta_stairs", () -> new StairBlock(Blocks.BLACK_TERRACOTTA::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.BLACK_TERRACOTTA).sound(SoundType.STONE).strength(1.25f, 4.2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> BLUE_TERRACOTTA_STAIRS = registerBlock("blue_terracotta_stairs", () -> new StairBlock(Blocks.BLUE_TERRACOTTA::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.BLUE_TERRACOTTA).sound(SoundType.STONE).strength(1.25f, 4.2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> BROWN_TERRACOTTA_STAIRS = registerBlock("brown_terracotta_stairs", () -> new StairBlock(Blocks.BROWN_TERRACOTTA::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.BROWN_TERRACOTTA).sound(SoundType.STONE).strength(1.25f, 4.2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> CYAN_TERRACOTTA_STAIRS = registerBlock("cyan_terracotta_stairs", () -> new StairBlock(Blocks.CYAN_TERRACOTTA::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.CYAN_TERRACOTTA).sound(SoundType.STONE).strength(1.25f, 4.2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> GRAY_TERRACOTTA_STAIRS = registerBlock("gray_terracotta_stairs", () -> new StairBlock(Blocks.GRAY_TERRACOTTA::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.GRAY_TERRACOTTA).sound(SoundType.STONE).strength(1.25f, 4.2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> GREEN_TERRACOTTA_STAIRS = registerBlock("green_terracotta_stairs", () -> new StairBlock(Blocks.GREEN_TERRACOTTA::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.GREEN_TERRACOTTA).sound(SoundType.STONE).strength(1.25f, 4.2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> LIGHT_BLUE_TERRACOTTA_STAIRS = registerBlock("light_blue_terracotta_stairs", () -> new StairBlock(Blocks.LIGHT_BLUE_TERRACOTTA::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.LIGHT_BLUE_TERRACOTTA).sound(SoundType.STONE).strength(1.25f, 4.2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> LIGHT_GRAY_TERRACOTTA_STAIRS = registerBlock("light_gray_terracotta_stairs", () -> new StairBlock(Blocks.LIGHT_GRAY_TERRACOTTA::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.LIGHT_GRAY_TERRACOTTA).sound(SoundType.STONE).strength(1.25f, 4.2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> LIME_TERRACOTTA_STAIRS = registerBlock("lime_terracotta_stairs", () -> new StairBlock(Blocks.LIME_TERRACOTTA::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.LIME_TERRACOTTA).sound(SoundType.STONE).strength(1.25f, 4.2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> MAGENTA_TERRACOTTA_STAIRS = registerBlock("magenta_terracotta_stairs", () -> new StairBlock(Blocks.MAGENTA_TERRACOTTA::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.MAGENTA_TERRACOTTA).sound(SoundType.STONE).strength(1.25f, 4.2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> ORANGE_TERRACOTTA_STAIRS = registerBlock("orange_terracotta_stairs", () -> new StairBlock(Blocks.ORANGE_TERRACOTTA::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.ORANGE_TERRACOTTA).sound(SoundType.STONE).strength(1.25f, 4.2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> PINK_TERRACOTTA_STAIRS = registerBlock("pink_terracotta_stairs", () -> new StairBlock(Blocks.PINK_TERRACOTTA::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.PINK_TERRACOTTA).sound(SoundType.STONE).strength(1.25f, 4.2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> PURPLE_TERRACOTTA_STAIRS = registerBlock("purple_terracotta_stairs", () -> new StairBlock(Blocks.PURPLE_TERRACOTTA::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.PURPLE_TERRACOTTA).sound(SoundType.STONE).strength(1.25f, 4.2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> RED_TERRACOTTA_STAIRS = registerBlock("red_terracotta_stairs", () -> new StairBlock(Blocks.RED_TERRACOTTA::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.RED_TERRACOTTA).sound(SoundType.STONE).strength(1.25f, 4.2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> WHITE_TERRACOTTA_STAIRS = registerBlock("white_terracotta_stairs", () -> new StairBlock(Blocks.WHITE_TERRACOTTA::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.WHITE_TERRACOTTA).sound(SoundType.STONE).strength(1.25f, 4.2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> YELLOW_TERRACOTTA_STAIRS = registerBlock("yellow_terracotta_stairs", () -> new StairBlock(Blocks.YELLOW_TERRACOTTA::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.YELLOW_TERRACOTTA).sound(SoundType.STONE).strength(1.25f, 4.2f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> BLACK_CONCRETE_POWDER_STAIRS = registerBlock("black_concrete_powder_stairs", () -> new StairBlock(Blocks.BLACK_CONCRETE_POWDER::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.BLACK_CONCRETE_POWDER).sound(SoundType.SAND).strength(0.5f, 0.5f)));
    public static final RegistryObject<Block> BLUE_CONCRETE_POWDER_STAIRS = registerBlock("blue_concrete_powder_stairs", () -> new StairBlock(Blocks.BLUE_CONCRETE_POWDER::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.BLUE_CONCRETE_POWDER).sound(SoundType.SAND).strength(0.5f, 0.5f)));
    public static final RegistryObject<Block> BROWN_CONCRETE_POWDER_STAIRS = registerBlock("brown_concrete_powder_stairs", () -> new StairBlock(Blocks.BROWN_CONCRETE_POWDER::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.BROWN_CONCRETE_POWDER).sound(SoundType.SAND).strength(0.5f, 0.5f)));
    public static final RegistryObject<Block> CYAN_CONCRETE_POWDER_STAIRS = registerBlock("cyan_concrete_powder_stairs", () -> new StairBlock(Blocks.CYAN_CONCRETE_POWDER::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.CYAN_CONCRETE_POWDER).sound(SoundType.SAND).strength(0.5f, 0.5f)));
    public static final RegistryObject<Block> GRAY_CONCRETE_POWDER_STAIRS = registerBlock("gray_concrete_powder_stairs", () -> new StairBlock(Blocks.GRAY_CONCRETE_POWDER::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.GRAY_CONCRETE_POWDER).sound(SoundType.SAND).strength(0.5f, 0.5f)));
    public static final RegistryObject<Block> GREEN_CONCRETE_POWDER_STAIRS = registerBlock("green_concrete_powder_stairs", () -> new StairBlock(Blocks.GREEN_CONCRETE_POWDER::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.GREEN_CONCRETE_POWDER).sound(SoundType.SAND).strength(0.5f, 0.5f)));
    public static final RegistryObject<Block> LIGHT_BLUE_CONCRETE_POWDER_STAIRS = registerBlock("light_blue_concrete_powder_stairs", () -> new StairBlock(Blocks.LIGHT_BLUE_CONCRETE_POWDER::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.LIGHT_BLUE_CONCRETE_POWDER).sound(SoundType.SAND).strength(0.5f, 0.5f)));
    public static final RegistryObject<Block> LIGHT_GRAY_CONCRETE_POWDER_STAIRS = registerBlock("light_gray_concrete_powder_stairs", () -> new StairBlock(Blocks.LIGHT_GRAY_CONCRETE_POWDER::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.LIGHT_GRAY_CONCRETE_POWDER).sound(SoundType.SAND).strength(0.5f, 0.5f)));
    public static final RegistryObject<Block> LIME_CONCRETE_POWDER_STAIRS = registerBlock("lime_concrete_powder_stairs", () -> new StairBlock(Blocks.LIME_CONCRETE_POWDER::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.LIME_CONCRETE_POWDER).sound(SoundType.SAND).strength(0.5f, 0.5f)));
    public static final RegistryObject<Block> MAGENTA_CONCRETE_POWDER_STAIRS = registerBlock("magenta_concrete_powder_stairs", () -> new StairBlock(Blocks.MAGENTA_CONCRETE_POWDER::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.MAGENTA_CONCRETE_POWDER).sound(SoundType.SAND).strength(0.5f, 0.5f)));
    public static final RegistryObject<Block> ORANGE_CONCRETE_POWDER_STAIRS = registerBlock("orange_concrete_powder_stairs", () -> new StairBlock(Blocks.ORANGE_CONCRETE_POWDER::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.ORANGE_CONCRETE_POWDER).sound(SoundType.SAND).strength(0.5f, 0.5f)));
    public static final RegistryObject<Block> PINK_CONCRETE_POWDER_STAIRS = registerBlock("pink_concrete_powder_stairs", () -> new StairBlock(Blocks.PINK_CONCRETE_POWDER::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.PINK_CONCRETE_POWDER).sound(SoundType.SAND).strength(0.5f, 0.5f)));
    public static final RegistryObject<Block> PURPLE_CONCRETE_POWDER_STAIRS = registerBlock("purple_concrete_powder_stairs", () -> new StairBlock(Blocks.PURPLE_CONCRETE_POWDER::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.PURPLE_CONCRETE_POWDER).sound(SoundType.SAND).strength(0.5f, 0.5f)));
    public static final RegistryObject<Block> RED_CONCRETE_POWDER_STAIRS = registerBlock("red_concrete_powder_stairs", () -> new StairBlock(Blocks.RED_CONCRETE_POWDER::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.RED_CONCRETE_POWDER).sound(SoundType.SAND).strength(0.5f, 0.5f)));
    public static final RegistryObject<Block> WHITE_CONCRETE_POWDER_STAIRS = registerBlock("white_concrete_powder_stairs", () -> new StairBlock(Blocks.WHITE_CONCRETE_POWDER::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.WHITE_CONCRETE_POWDER).sound(SoundType.SAND).strength(0.5f, 0.5f)));
    public static final RegistryObject<Block> YELLOW_CONCRETE_POWDER_STAIRS = registerBlock("yellow_concrete_powder_stairs", () -> new StairBlock(Blocks.YELLOW_CONCRETE_POWDER::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.YELLOW_CONCRETE_POWDER).sound(SoundType.SAND).strength(0.5f, 0.5f)));
    public static final RegistryObject<Block> BLACK_CONCRETE_STAIRS = registerBlock("black_concrete_stairs", () -> new StairBlock(Blocks.BLACK_CONCRETE::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.BLACK_CONCRETE).sound(SoundType.STONE).strength(1.8f, 1.8f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> BLUE_CONCRETE_STAIRS = registerBlock("blue_concrete_stairs", () -> new StairBlock(Blocks.BLUE_CONCRETE::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.BLUE_CONCRETE).sound(SoundType.STONE).strength(1.8f, 1.8f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> BROWN_CONCRETE_STAIRS = registerBlock("brown_concrete_stairs", () -> new StairBlock(Blocks.BROWN_CONCRETE::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.BROWN_CONCRETE).sound(SoundType.STONE).strength(1.8f, 1.8f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> CYAN_CONCRETE_STAIRS = registerBlock("cyan_concrete_stairs", () -> new StairBlock(Blocks.CYAN_CONCRETE::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.CYAN_CONCRETE).sound(SoundType.STONE).strength(1.8f, 1.8f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> GREEN_CONCRETE_STAIRS = registerBlock("green_concrete_stairs", () -> new StairBlock(Blocks.GREEN_CONCRETE::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.GREEN_CONCRETE).sound(SoundType.STONE).strength(1.8f, 1.8f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> LIGHT_BLUE_CONCRETE_STAIRS = registerBlock("light_blue_concrete_stairs", () -> new StairBlock(Blocks.LIGHT_BLUE_CONCRETE::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.LIGHT_BLUE_CONCRETE).sound(SoundType.STONE).strength(1.8f, 1.8f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> LIGHT_GRAY_CONCRETE_STAIRS = registerBlock("light_gray_concrete_stairs", () -> new StairBlock(Blocks.LIGHT_GRAY_CONCRETE::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.LIGHT_GRAY_CONCRETE).sound(SoundType.STONE).strength(1.8f, 1.8f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> LIME_CONCRETE_STAIRS = registerBlock("lime_concrete_stairs", () -> new StairBlock(Blocks.LIME_CONCRETE::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.LIME_CONCRETE).sound(SoundType.STONE).strength(1.8f, 1.8f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> MAGENTA_CONCRETE_STAIRS = registerBlock("magenta_concrete_stairs", () -> new StairBlock(Blocks.MAGENTA_CONCRETE::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.MAGENTA_CONCRETE).sound(SoundType.STONE).strength(1.8f, 1.8f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> ORANGE_CONCRETE_STAIRS = registerBlock("orange_concrete_stairs", () -> new StairBlock(Blocks.ORANGE_CONCRETE::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.ORANGE_CONCRETE).sound(SoundType.STONE).strength(1.8f, 1.8f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> PINK_CONCRETE_STAIRS = registerBlock("pink_concrete_stairs", () -> new StairBlock(Blocks.PINK_CONCRETE::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.PINK_CONCRETE).sound(SoundType.STONE).strength(1.8f, 1.8f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> PURPLE_CONCRETE_STAIRS = registerBlock("purple_concrete_stairs", () -> new StairBlock(Blocks.PURPLE_CONCRETE::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.PURPLE_CONCRETE).sound(SoundType.STONE).strength(1.8f, 1.8f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> RED_CONCRETE_STAIRS = registerBlock("red_concrete_stairs", () -> new StairBlock(Blocks.RED_CONCRETE::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.RED_CONCRETE).sound(SoundType.STONE).strength(1.8f, 1.8f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> WHITE_CONCRETE_STAIRS = registerBlock("white_concrete_stairs", () -> new StairBlock(Blocks.WHITE_CONCRETE::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.WHITE_CONCRETE).sound(SoundType.STONE).strength(1.8f, 1.8f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> YELLOW_CONCRETE_STAIRS = registerBlock("yellow_concrete_stairs", () -> new StairBlock(Blocks.YELLOW_CONCRETE::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.YELLOW_CONCRETE).sound(SoundType.STONE).strength(1.8f, 1.8f).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> GRAY_CONCRETE_STAIRS = registerBlock("gray_concrete_stairs", () -> new StairBlock(Blocks.GRAY_CONCRETE::defaultBlockState, BlockBehaviour.Properties.copy(Blocks.GRAY_CONCRETE).sound(SoundType.STONE).strength(1.8f, 1.8f).requiresCorrectToolForDrops()));

    private static <T extends Block> RegistryObject<T> registerBlock(String name, Supplier<T> block) {
        RegistryObject<T> toReturn = BLOCKS.register(name, block);
        registerBlockItem(name, toReturn);
        return toReturn;
    }

    private static <T extends Block> RegistryObject<Item> registerBlockItem(String name, RegistryObject<T> block) {
        return com.jaydizzle.buildingblocks.item.JDItems.ITEMS.register(name, () -> new BlockItem(block.get(), new Item.Properties()));
    }

    public static void register(IEventBus eventBus) {
        BLOCKS.register(eventBus);
    }
}
