package com.jaydizzle.buildingblocks.datagen;

import com.jaydizzle.buildingblocks.BuildingBlocks;
import com.jaydizzle.buildingblocks.block.custom.JDBlocks;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.*;
import net.minecraftforge.client.model.generators.BlockStateProvider;
import net.minecraftforge.client.model.generators.ModelFile;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraftforge.registries.RegistryObject;

public class JDBlockStateProvider extends BlockStateProvider {
    public JDBlockStateProvider(PackOutput output, ExistingFileHelper exFileHelper) {
        super(output, BuildingBlocks.MOD_ID, exFileHelper);
    }

    @Override
    protected void registerStatesAndModels() {

        //CUSTOM BLOCKS
        blockWithItem(JDBlocks.PINK_CALCITE);
        blockWithItem(JDBlocks.PURPLE_CALCITE);
        blockWithItem(JDBlocks.ORANGE_CALCITE);
        blockWithItem(JDBlocks.LIGHT_BLUE_CALCITE);
        blockWithItem(JDBlocks.YELLOW_CALCITE);
        blockWithItem(JDBlocks.LIME_CALCITE);
        blockWithItem(JDBlocks.BLUE_CALCITE);
        blockWithItem(JDBlocks.LIGHT_GRAY_CALCITE);
        blockWithItem(JDBlocks.MAGENTA_CALCITE);
        blockWithItem(JDBlocks.GRAY_CALCITE);
        blockWithItem(JDBlocks.BLUE_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.BROWN_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.CYAN_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.GRAY_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.GREEN_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.LIGHT_BLUE_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.LIGHT_GRAY_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.LIME_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.MAGENTA_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.ORANGE_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.PINK_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.PURPLE_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.RED_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.WHITE_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.YELLOW_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.YELLOW_BRICKS);
        blockWithItem(JDBlocks.RED_BRICKS);
        blockWithItem(JDBlocks.BLACK_BRICKS);
        blockWithItem(JDBlocks.WHITE_BRICKS);
        blockWithItem(JDBlocks.BROWN_BRICKS);
        blockWithItem(JDBlocks.AQUA_BRICKS);
        blockWithItem(JDBlocks.ORANGE_BRICKS);
        blockWithItem(JDBlocks.GREEN_BRICKS);
        blockWithItem(JDBlocks.GRAY_BRICKS);
        blockWithItem(JDBlocks.BLUE_BRICKS);
        blockWithItem(JDBlocks.PURPLE_BRICKS);
        blockWithItem(JDBlocks.BASIC_BRICKS);
        blockWithItem(JDBlocks.TURQUOISE_COBBLESTONE);
        blockWithItem(JDBlocks.SPIRAL_STONE);
        blockWithItem(JDBlocks.BROWN_COBBLESTONE);
        blockWithItem(JDBlocks.BLUE_COBBLESTONE);
        blockWithItem(JDBlocks.BLACK_COBBLESTONE);
        blockWithItem(JDBlocks.GREEN_COBBLESTONE);
        blockWithItem(JDBlocks.RED_COBBLESTONE);
        blockWithItem(JDBlocks.PURPLE_COBBLESTONE);

        //STAIRS
        stairsBlock(((StairBlock) JDBlocks.SPRUCE_LOG_STAIRS.get()), new ResourceLocation("block/spruce_log"));
        stairsBlock(((StairBlock) JDBlocks.OAK_LOG_STAIRS.get()), new ResourceLocation("block/oak_log"));
        stairsBlock(((StairBlock) JDBlocks.DARK_OAK_LOG_STAIRS.get()), new ResourceLocation("block/dark_oak_log"));
        stairsBlock(((StairBlock) JDBlocks.ACACIA_LOG_STAIRS.get()), new ResourceLocation("block/acacia_log"));
        stairsBlock(((StairBlock) JDBlocks.JUNGLE_LOG_STAIRS.get()), new ResourceLocation("block/jungle_log"));
        stairsBlock(((StairBlock) JDBlocks.BIRCH_LOG_STAIRS.get()), new ResourceLocation("block/birch_log"));
        stairsBlock(((StairBlock) JDBlocks.WARPED_LOG_STAIRS.get()), new ResourceLocation("block/warped_stem"));
        stairsBlock(((StairBlock) JDBlocks.CRIMSON_LOG_STAIRS.get()), new ResourceLocation("block/crimson_stem"));
        stairsBlock(((StairBlock) JDBlocks.AMETHYST_STAIRS.get()), blockTexture(Blocks.AMETHYST_BLOCK));
        stairsBlock(((StairBlock) JDBlocks.CALCITE_STAIRS.get()), blockTexture(Blocks.CALCITE));
        stairsBlock(((StairBlock) JDBlocks.SPRUCE_SKINNED_LOG_STAIRS.get()), new ResourceLocation("block/stripped_spruce_log"));
        stairsBlock(((StairBlock) JDBlocks.OAK_SKINNED_LOG_STAIRS.get()), new ResourceLocation("block/stripped_oak_log"));
        stairsBlock(((StairBlock) JDBlocks.DARK_OAK_SKINNED_LOG_STAIRS.get()), new ResourceLocation("block/stripped_dark_oak_log"));
        stairsBlock(((StairBlock) JDBlocks.ACACIA_SKINNED_LOG_STAIRS.get()), new ResourceLocation("block/stripped_acacia_log"));
        stairsBlock(((StairBlock) JDBlocks.JUNGLE_SKINNED_LOG_STAIRS.get()), new ResourceLocation("block/stripped_jungle_log"));
        stairsBlock(((StairBlock) JDBlocks.BIRCH_SKINNED_LOG_STAIRS.get()), new ResourceLocation("block/stripped_birch_log"));
        stairsBlock(((StairBlock) JDBlocks.WARPED_SKINNED_LOG_STAIRS.get()), new ResourceLocation("block/stripped_warped_stem"));
        stairsBlock(((StairBlock) JDBlocks.CRIMSON_SKINNED_LOG_STAIRS.get()), new ResourceLocation("block/stripped_crimson_stem"));
        stairsBlock(((StairBlock) JDBlocks.CLAY_STAIRS.get()), blockTexture(Blocks.CLAY));
        stairsBlock(((StairBlock) JDBlocks.GRAVEL_STAIRS.get()), blockTexture(Blocks.GRAVEL));
        stairsBlock(((StairBlock) JDBlocks.TUFF_STAIRS.get()), blockTexture(Blocks.TUFF));
        stairsBlock(((StairBlock) JDBlocks.SAND_STAIRS.get()), blockTexture(Blocks.SAND));
        stairsBlock(((StairBlock) JDBlocks.RED_SAND_STAIRS.get()), blockTexture(Blocks.RED_SAND));
        stairsBlock(((StairBlock) JDBlocks.DIRT_STAIRS.get()), blockTexture(Blocks.DIRT));
        stairsBlock(((StairBlock) JDBlocks.COARSE_DIRT_STAIRS.get()), blockTexture(Blocks.COARSE_DIRT));
        stairsBlock(((StairBlock) JDBlocks.ROOTED_DIRT_STAIRS.get()), blockTexture(Blocks.ROOTED_DIRT));
        stairsBlock(((StairBlock) JDBlocks.OBSIDIAN_STAIRS.get()), blockTexture(Blocks.OBSIDIAN));
        stairsBlock(((StairBlock) JDBlocks.CRYING_OBSIDIAN_STAIRS.get()), blockTexture(Blocks.CRYING_OBSIDIAN));
        stairsBlock(((StairBlock) JDBlocks.NETHERRACK_STAIRS.get()), blockTexture(Blocks.NETHERRACK));
        stairsBlock(((StairBlock) JDBlocks.END_STONE_STAIRS.get()), blockTexture(Blocks.END_STONE));
        stairsBlock(((StairBlock) JDBlocks.CHISELED_QUARTZ_STAIRS.get()), new ResourceLocation("block/chiseled_quartz_block"));
        stairsBlock(((StairBlock) JDBlocks.QUARTZ_BRICKS_STAIRS.get()), blockTexture(Blocks.QUARTZ_BRICKS));
        stairsBlock(((StairBlock) JDBlocks.QUARTZ_PILLAR_STAIRS.get()), new ResourceLocation("block/quartz_pillar"));
        stairsBlock(((StairBlock) JDBlocks.BONE_BLOCK_STAIRS.get()), new ResourceLocation("block/bone_block_side"));
        stairsBlock(((StairBlock) JDBlocks.SMOOTH_BASALT_STAIRS.get()), new ResourceLocation("block/smooth_basalt"));
        stairsBlock(((StairBlock) JDBlocks.BASALT_STAIRS.get()), new ResourceLocation("block/basalt_side"));
        stairsBlock(((StairBlock) JDBlocks.POLISHED_BASALT_STAIRS.get()), new ResourceLocation("block/polished_basalt_side"));
        stairsBlock(((StairBlock) JDBlocks.WHITE_WOOL_STAIRS.get()), blockTexture(Blocks.WHITE_WOOL));
        stairsBlock(((StairBlock) JDBlocks.ORANGE_WOOL_STAIRS.get()), blockTexture(Blocks.ORANGE_WOOL));
        stairsBlock(((StairBlock) JDBlocks.MAGENTA_WOOL_STAIRS.get()), blockTexture(Blocks.MAGENTA_WOOL));
        stairsBlock(((StairBlock) JDBlocks.LIGHT_BLUE_WOOL_STAIRS.get()), blockTexture(Blocks.LIGHT_BLUE_WOOL));
        stairsBlock(((StairBlock) JDBlocks.YELLOW_WOOL_STAIRS.get()), blockTexture(Blocks.YELLOW_WOOL));
        stairsBlock(((StairBlock) JDBlocks.LIME_WOOL_STAIRS.get()), blockTexture(Blocks.LIME_WOOL));
        stairsBlock(((StairBlock) JDBlocks.PINK_WOOL_STAIRS.get()), blockTexture(Blocks.PINK_WOOL));
        stairsBlock(((StairBlock) JDBlocks.GRAY_WOOL_STAIRS.get()), blockTexture(Blocks.GRAY_WOOL));
        stairsBlock(((StairBlock) JDBlocks.LIGHT_GRAY_WOOL_STAIRS.get()), blockTexture(Blocks.LIGHT_GRAY_WOOL));
        stairsBlock(((StairBlock) JDBlocks.CYAN_WOOL_STAIRS.get()), blockTexture(Blocks.CYAN_WOOL));
        stairsBlock(((StairBlock) JDBlocks.PURPLE_WOOL_STAIRS.get()), blockTexture(Blocks.PURPLE_WOOL));
        stairsBlock(((StairBlock) JDBlocks.BLUE_WOOL_STAIRS.get()), blockTexture(Blocks.BLUE_WOOL));
        stairsBlock(((StairBlock) JDBlocks.BROWN_WOOL_STAIRS.get()), blockTexture(Blocks.BROWN_WOOL));
        stairsBlock(((StairBlock) JDBlocks.GREEN_WOOL_STAIRS.get()), blockTexture(Blocks.GREEN_WOOL));
        stairsBlock(((StairBlock) JDBlocks.RED_WOOL_STAIRS.get()), blockTexture(Blocks.RED_WOOL));
        stairsBlock(((StairBlock) JDBlocks.BLACK_WOOL_STAIRS.get()), blockTexture(Blocks.BLACK_WOOL));
        stairsBlock(((StairBlock) JDBlocks.CRACKED_NETHER_BRICKS_STAIRS.get()), blockTexture(Blocks.CRACKED_NETHER_BRICKS));
        stairsBlock(((StairBlock) JDBlocks.CHISELED_NETHER_BRICKS_STAIRS.get()), blockTexture(Blocks.CHISELED_NETHER_BRICKS));
        stairsBlock(((StairBlock) JDBlocks.CHISELED_RED_SANDSTONE_STAIRS.get()), blockTexture(Blocks.CHISELED_RED_SANDSTONE));
        stairsBlock(((StairBlock) JDBlocks.CHISELED_SANDSTONE_STAIRS.get()), blockTexture(Blocks.CHISELED_SANDSTONE));
        stairsBlock(((StairBlock) JDBlocks.CHISELED_STONE_BRICKS_STAIRS.get()), blockTexture(Blocks.CHISELED_STONE_BRICKS));
        stairsBlock(((StairBlock) JDBlocks.CRACKED_STONE_BRICKS_STAIRS.get()), blockTexture(Blocks.CRACKED_STONE_BRICKS));
        stairsBlock(((StairBlock) JDBlocks.CRACKED_POLISHED_BLACKSTONE_BRICKS_STAIRS.get()), blockTexture(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS));
        stairsBlock(((StairBlock) JDBlocks.MOSS_BLOCK_STAIRS.get()), blockTexture(Blocks.MOSS_BLOCK));
        stairsBlock(((StairBlock) JDBlocks.HONEYCOMB_BLOCK_STAIRS.get()), blockTexture(Blocks.HONEYCOMB_BLOCK));
        stairsBlock(((StairBlock) JDBlocks.TERRACOTTA_STAIRS.get()), blockTexture(Blocks.TERRACOTTA));
        stairsBlock(((StairBlock) JDBlocks.BLACK_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.BLACK_TERRACOTTA));
        stairsBlock(((StairBlock) JDBlocks.BLUE_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.BLUE_TERRACOTTA));
        stairsBlock(((StairBlock) JDBlocks.BROWN_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.BROWN_TERRACOTTA));
        stairsBlock(((StairBlock) JDBlocks.CYAN_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.CYAN_TERRACOTTA));
        stairsBlock(((StairBlock) JDBlocks.GRAY_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.GRAY_TERRACOTTA));
        stairsBlock(((StairBlock) JDBlocks.GREEN_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.GREEN_TERRACOTTA));
        stairsBlock(((StairBlock) JDBlocks.LIGHT_GRAY_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.LIGHT_GRAY_TERRACOTTA));
        stairsBlock(((StairBlock) JDBlocks.LIGHT_BLUE_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.LIGHT_BLUE_TERRACOTTA));
        stairsBlock(((StairBlock) JDBlocks.LIME_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.LIME_TERRACOTTA));
        stairsBlock(((StairBlock) JDBlocks.MAGENTA_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.MAGENTA_TERRACOTTA));
        stairsBlock(((StairBlock) JDBlocks.ORANGE_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.ORANGE_TERRACOTTA));
        stairsBlock(((StairBlock) JDBlocks.PINK_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.PINK_TERRACOTTA));
        stairsBlock(((StairBlock) JDBlocks.PURPLE_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.PURPLE_TERRACOTTA));
        stairsBlock(((StairBlock) JDBlocks.RED_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.RED_TERRACOTTA));
        stairsBlock(((StairBlock) JDBlocks.WHITE_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.WHITE_TERRACOTTA));
        stairsBlock(((StairBlock) JDBlocks.YELLOW_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.YELLOW_TERRACOTTA));
        stairsBlock(((StairBlock) JDBlocks.BLACK_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.BLACK_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDBlocks.BLUE_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.BLUE_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDBlocks.BROWN_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.BROWN_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDBlocks.CYAN_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.CYAN_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDBlocks.GRAY_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.GRAY_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDBlocks.GREEN_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.GREEN_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDBlocks.LIGHT_BLUE_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.LIGHT_BLUE_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDBlocks.LIGHT_GRAY_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.LIGHT_GRAY_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDBlocks.LIME_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.LIME_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDBlocks.MAGENTA_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.MAGENTA_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDBlocks.ORANGE_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.ORANGE_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDBlocks.PINK_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.PINK_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDBlocks.PURPLE_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.PURPLE_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDBlocks.RED_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.RED_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDBlocks.WHITE_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.WHITE_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDBlocks.YELLOW_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.YELLOW_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDBlocks.BLACK_CONCRETE_STAIRS.get()), blockTexture(Blocks.BLACK_CONCRETE));
        stairsBlock(((StairBlock) JDBlocks.BLUE_CONCRETE_STAIRS.get()), blockTexture(Blocks.BLUE_CONCRETE));
        stairsBlock(((StairBlock) JDBlocks.BROWN_CONCRETE_STAIRS.get()), blockTexture(Blocks.BROWN_CONCRETE));
        stairsBlock(((StairBlock) JDBlocks.CYAN_CONCRETE_STAIRS.get()), blockTexture(Blocks.CYAN_CONCRETE));
        stairsBlock(((StairBlock) JDBlocks.GRAY_CONCRETE_STAIRS.get()), blockTexture(Blocks.GRAY_CONCRETE));
        stairsBlock(((StairBlock) JDBlocks.GREEN_CONCRETE_STAIRS.get()), blockTexture(Blocks.GREEN_CONCRETE));
        stairsBlock(((StairBlock) JDBlocks.LIGHT_BLUE_CONCRETE_STAIRS.get()), blockTexture(Blocks.LIGHT_BLUE_CONCRETE));
        stairsBlock(((StairBlock) JDBlocks.LIGHT_GRAY_CONCRETE_STAIRS.get()), blockTexture(Blocks.LIGHT_GRAY_CONCRETE));
        stairsBlock(((StairBlock) JDBlocks.LIME_CONCRETE_STAIRS.get()), blockTexture(Blocks.LIME_CONCRETE));
        stairsBlock(((StairBlock) JDBlocks.MAGENTA_CONCRETE_STAIRS.get()), blockTexture(Blocks.MAGENTA_CONCRETE));
        stairsBlock(((StairBlock) JDBlocks.ORANGE_CONCRETE_STAIRS.get()), blockTexture(Blocks.ORANGE_CONCRETE));
        stairsBlock(((StairBlock) JDBlocks.PINK_CONCRETE_STAIRS.get()), blockTexture(Blocks.PINK_CONCRETE));
        stairsBlock(((StairBlock) JDBlocks.PURPLE_CONCRETE_STAIRS.get()), blockTexture(Blocks.PURPLE_CONCRETE));
        stairsBlock(((StairBlock) JDBlocks.RED_CONCRETE_STAIRS.get()), blockTexture(Blocks.RED_CONCRETE));
        stairsBlock(((StairBlock) JDBlocks.WHITE_CONCRETE_STAIRS.get()), blockTexture(Blocks.WHITE_CONCRETE));
        stairsBlock(((StairBlock) JDBlocks.YELLOW_CONCRETE_STAIRS.get()), blockTexture(Blocks.YELLOW_CONCRETE));
        stairsBlock(((StairBlock) JDBlocks.SMOOTH_STONE_STAIRS.get()), blockTexture(Blocks.SMOOTH_STONE));
        stairsBlock(((StairBlock) JDBlocks.GLOWSTONE_STAIRS.get()), blockTexture(Blocks.GLOWSTONE));

        //SLABS
        slabBlock(((SlabBlock) JDBlocks.SPRUCE_LOG_SLAB.get()), new ResourceLocation("block/spruce_log"), new ResourceLocation("block/spruce_log"));
        slabBlock(((SlabBlock) JDBlocks.OAK_LOG_SLAB.get()), new ResourceLocation("block/oak_log"), new ResourceLocation("block/oak_log"));
        slabBlock(((SlabBlock) JDBlocks.DARK_OAK_LOG_SLAB.get()), new ResourceLocation("block/dark_oak_log"), new ResourceLocation("block/dark_oak_log"));
        slabBlock(((SlabBlock) JDBlocks.ACACIA_LOG_SLAB.get()), new ResourceLocation("block/acacia_log"), new ResourceLocation("block/acacia_log"));
        slabBlock(((SlabBlock) JDBlocks.JUNGLE_LOG_SLAB.get()), new ResourceLocation("block/jungle_log"), new ResourceLocation("block/jungle_log"));
        slabBlock(((SlabBlock) JDBlocks.BIRCH_LOG_SLAB.get()), new ResourceLocation("block/birch_log"), new ResourceLocation("block/birch_log"));
        slabBlock(((SlabBlock) JDBlocks.WARPED_LOG_SLAB.get()), new ResourceLocation("block/warped_stem"), new ResourceLocation("block/warped_stem"));
        slabBlock(((SlabBlock) JDBlocks.CRIMSON_LOG_SLAB.get()), new ResourceLocation("block/crimson_stem"), new ResourceLocation("block/crimson_stem"));
        slabBlock(((SlabBlock) JDBlocks.AMETHYST_SLAB.get()), blockTexture(Blocks.AMETHYST_BLOCK), blockTexture(Blocks.AMETHYST_BLOCK));
        slabBlock(((SlabBlock) JDBlocks.CALCITE_SLAB.get()), blockTexture(Blocks.CALCITE), blockTexture(Blocks.CALCITE));
        slabBlock(((SlabBlock) JDBlocks.SPRUCE_SKINNED_LOG_SLAB.get()), new ResourceLocation("block/stripped_spruce_log"), new ResourceLocation("block/stripped_spruce_log"));
        slabBlock(((SlabBlock) JDBlocks.OAK_SKINNED_LOG_SLAB.get()), new ResourceLocation("block/stripped_oak_log"), new ResourceLocation("block/stripped_oak_log"));
        slabBlock(((SlabBlock) JDBlocks.DARK_SKINNED_OAK_LOG_SLAB.get()), new ResourceLocation("block/stripped_dark_oak_log"), new ResourceLocation("block/stripped_dark_oak_log"));
        slabBlock(((SlabBlock) JDBlocks.ACACIA_SKINNED_LOG_SLAB.get()), new ResourceLocation("block/stripped_acacia_log"), new ResourceLocation("block/stripped_acacia_log"));
        slabBlock(((SlabBlock) JDBlocks.JUNGLE_SKINNED_LOG_SLAB.get()), new ResourceLocation("block/stripped_jungle_log"), new ResourceLocation("block/stripped_jungle_log"));
        slabBlock(((SlabBlock) JDBlocks.BIRCH_SKINNED_LOG_SLAB.get()), new ResourceLocation("block/stripped_birch_log"), new ResourceLocation("block/stripped_birch_log"));
        slabBlock(((SlabBlock) JDBlocks.WARPED_SKINNED_LOG_SLAB.get()), new ResourceLocation("block/stripped_warped_stem"), new ResourceLocation("block/stripped_warped_stem"));
        slabBlock(((SlabBlock) JDBlocks.CRIMSON_SKINNED_LOG_SLAB.get()), new ResourceLocation("block/stripped_crimson_stem"), new ResourceLocation("block/stripped_crimson_stem"));
        slabBlock(((SlabBlock) JDBlocks.CLAY_SLAB.get()), blockTexture(Blocks.CLAY), blockTexture(Blocks.CLAY));
        slabBlock(((SlabBlock) JDBlocks.GRAVEL_SLAB.get()), blockTexture(Blocks.GRAVEL), blockTexture(Blocks.GRAVEL));
        slabBlock(((SlabBlock) JDBlocks.TUFF_SLAB.get()), blockTexture(Blocks.TUFF), blockTexture(Blocks.TUFF));
        slabBlock(((SlabBlock) JDBlocks.SAND_SLAB.get()), blockTexture(Blocks.SAND), blockTexture(Blocks.SAND));
        slabBlock(((SlabBlock) JDBlocks.RED_SAND_SLAB.get()), blockTexture(Blocks.RED_SAND), blockTexture(Blocks.RED_SAND));
        slabBlock(((SlabBlock) JDBlocks.DIRT_SLAB.get()), blockTexture(Blocks.DIRT), blockTexture(Blocks.DIRT));
        slabBlock(((SlabBlock) JDBlocks.COARSE_DIRT_SLAB.get()), blockTexture(Blocks.COARSE_DIRT), blockTexture(Blocks.COARSE_DIRT));
        slabBlock(((SlabBlock) JDBlocks.ROOTED_DIRT_SLAB.get()), blockTexture(Blocks.ROOTED_DIRT), blockTexture(Blocks.ROOTED_DIRT));
        slabBlock(((SlabBlock) JDBlocks.OBSIDIAN_SLAB.get()), blockTexture(Blocks.OBSIDIAN), blockTexture(Blocks.OBSIDIAN));
        slabBlock(((SlabBlock) JDBlocks.CRYING_OBSIDIAN_SLAB.get()), blockTexture(Blocks.CRYING_OBSIDIAN), blockTexture(Blocks.CRYING_OBSIDIAN));
        slabBlock(((SlabBlock) JDBlocks.NETHERRACK_SLAB.get()), blockTexture(Blocks.NETHERRACK), blockTexture(Blocks.NETHERRACK));
        slabBlock(((SlabBlock) JDBlocks.END_STONE_SLAB.get()), blockTexture(Blocks.END_STONE), blockTexture(Blocks.END_STONE));
        slabBlock(((SlabBlock) JDBlocks.CHISELED_QUARTZ_SLAB.get()), blockTexture(Blocks.CHISELED_QUARTZ_BLOCK), blockTexture(Blocks.CHISELED_QUARTZ_BLOCK));
        slabBlock(((SlabBlock) JDBlocks.QUARTZ_BRICKS_SLAB.get()), blockTexture(Blocks.QUARTZ_BRICKS), blockTexture(Blocks.QUARTZ_BRICKS));
        slabBlock(((SlabBlock) JDBlocks.QUARTZ_PILLAR_SLAB.get()), new ResourceLocation("block/quartz_pillar"), new ResourceLocation("block/quartz_pillar"));
        slabBlock(((SlabBlock) JDBlocks.BONE_BLOCK_SLAB.get()), new ResourceLocation("block/bone_block"), new ResourceLocation("block/bone_block_side"));
        slabBlock(((SlabBlock) JDBlocks.SMOOTH_BASALT_SLAB.get()), new ResourceLocation("block/smooth_basalt"), new ResourceLocation("block/smooth_basalt"));
        slabBlock(((SlabBlock) JDBlocks.BASALT_SLAB.get()), new ResourceLocation("block/basalt"), new ResourceLocation("block/basalt_side"));
        slabBlock(((SlabBlock) JDBlocks.POLISHED_BASALT_SLAB.get()), new ResourceLocation("block/polished_basalt"), new ResourceLocation("block/polished_basalt_side"));
        slabBlock(((SlabBlock) JDBlocks.WHITE_WOOL_SLAB.get()), blockTexture(Blocks.WHITE_WOOL), blockTexture(Blocks.WHITE_WOOL));
        slabBlock(((SlabBlock) JDBlocks.ORANGE_WOOL_SLAB.get()), blockTexture(Blocks.ORANGE_WOOL), blockTexture(Blocks.ORANGE_WOOL));
        slabBlock(((SlabBlock) JDBlocks.MAGENTA_WOOL_SLAB.get()), blockTexture(Blocks.MAGENTA_WOOL), blockTexture(Blocks.MAGENTA_WOOL));
        slabBlock(((SlabBlock) JDBlocks.LIGHT_BLUE_WOOL_SLAB.get()), blockTexture(Blocks.LIGHT_BLUE_WOOL), blockTexture(Blocks.LIGHT_BLUE_WOOL));
        slabBlock(((SlabBlock) JDBlocks.YELLOW_WOOL_SLAB.get()), blockTexture(Blocks.YELLOW_WOOL), blockTexture(Blocks.YELLOW_WOOL));
        slabBlock(((SlabBlock) JDBlocks.LIME_WOOL_SLAB.get()), blockTexture(Blocks.LIME_WOOL), blockTexture(Blocks.LIME_WOOL));
        slabBlock(((SlabBlock) JDBlocks.PINK_WOOL_SLAB.get()), blockTexture(Blocks.PINK_WOOL), blockTexture(Blocks.PINK_WOOL));
        slabBlock(((SlabBlock) JDBlocks.GRAY_WOOL_SLAB.get()), blockTexture(Blocks.GRAY_WOOL), blockTexture(Blocks.GRAY_WOOL));
        slabBlock(((SlabBlock) JDBlocks.LIGHT_GRAY_WOOL_SLAB.get()), blockTexture(Blocks.LIGHT_GRAY_WOOL), blockTexture(Blocks.LIGHT_GRAY_WOOL));
        slabBlock(((SlabBlock) JDBlocks.CYAN_WOOL_SLAB.get()), blockTexture(Blocks.CYAN_WOOL), blockTexture(Blocks.CYAN_WOOL));
        slabBlock(((SlabBlock) JDBlocks.PURPLE_WOOL_SLAB.get()), blockTexture(Blocks.PURPLE_WOOL), blockTexture(Blocks.PURPLE_WOOL));
        slabBlock(((SlabBlock) JDBlocks.BLUE_WOOL_SLAB.get()), blockTexture(Blocks.BLUE_WOOL), blockTexture(Blocks.BLUE_WOOL));
        slabBlock(((SlabBlock) JDBlocks.BROWN_WOOL_SLAB.get()), blockTexture(Blocks.BROWN_WOOL), blockTexture(Blocks.BROWN_WOOL));
        slabBlock(((SlabBlock) JDBlocks.GREEN_WOOL_SLAB.get()), blockTexture(Blocks.GREEN_WOOL), blockTexture(Blocks.GREEN_WOOL));
        slabBlock(((SlabBlock) JDBlocks.RED_WOOL_SLAB.get()), blockTexture(Blocks.RED_WOOL), blockTexture(Blocks.RED_WOOL));
        slabBlock(((SlabBlock) JDBlocks.BLACK_WOOL_SLAB.get()), blockTexture(Blocks.BLACK_WOOL), blockTexture(Blocks.BLACK_WOOL));
        slabBlock(((SlabBlock) JDBlocks.CRACKED_NETHER_BRICKS_SLAB.get()), blockTexture(Blocks.CRACKED_NETHER_BRICKS), blockTexture(Blocks.CRACKED_NETHER_BRICKS));
        slabBlock(((SlabBlock) JDBlocks.CHISELED_NETHER_BRICKS_SLAB.get()), blockTexture(Blocks.CHISELED_NETHER_BRICKS), blockTexture(Blocks.CHISELED_NETHER_BRICKS));
        slabBlock(((SlabBlock) JDBlocks.CHISELED_RED_SANDSTONE_SLAB.get()), blockTexture(Blocks.CHISELED_RED_SANDSTONE), blockTexture(Blocks.CHISELED_RED_SANDSTONE));
        slabBlock(((SlabBlock) JDBlocks.CHISELED_SANDSTONE_SLAB.get()), blockTexture(Blocks.CHISELED_SANDSTONE), blockTexture(Blocks.CHISELED_SANDSTONE));
        slabBlock(((SlabBlock) JDBlocks.CHISELED_STONE_BRICKS_SLAB.get()), blockTexture(Blocks.CHISELED_STONE_BRICKS), blockTexture(Blocks.CHISELED_STONE_BRICKS));
        slabBlock(((SlabBlock) JDBlocks.CRACKED_STONE_BRICKS_SLAB.get()), blockTexture(Blocks.CRACKED_STONE_BRICKS), blockTexture(Blocks.CRACKED_STONE_BRICKS));
        slabBlock(((SlabBlock) JDBlocks.CRACKED_POLISHED_BLACKSTONE_BRICKS_SLAB.get()), blockTexture(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS), blockTexture(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS));
        slabBlock(((SlabBlock) JDBlocks.MOSS_BLOCK_SLAB.get()), blockTexture(Blocks.MOSS_BLOCK), blockTexture(Blocks.MOSS_BLOCK));
        slabBlock(((SlabBlock) JDBlocks.HONEYCOMB_BLOCK_SLAB.get()), blockTexture(Blocks.HONEYCOMB_BLOCK), blockTexture(Blocks.HONEYCOMB_BLOCK));
        slabBlock(((SlabBlock) JDBlocks.TERRACOTTA_SLAB.get()), blockTexture(Blocks.TERRACOTTA), blockTexture(Blocks.TERRACOTTA));
        slabBlock(((SlabBlock) JDBlocks.BLACK_TERRACOTTA_SLAB.get()), blockTexture(Blocks.BLACK_TERRACOTTA), blockTexture(Blocks.BLACK_TERRACOTTA));
        slabBlock(((SlabBlock) JDBlocks.BLUE_TERRACOTTA_SLAB.get()), blockTexture(Blocks.BLUE_TERRACOTTA), blockTexture(Blocks.BLUE_TERRACOTTA));
        slabBlock(((SlabBlock) JDBlocks.BROWN_TERRACOTTA_SLAB.get()), blockTexture(Blocks.BROWN_TERRACOTTA), blockTexture(Blocks.BROWN_TERRACOTTA));
        slabBlock(((SlabBlock) JDBlocks.CYAN_TERRACOTTA_SLAB.get()), blockTexture(Blocks.CYAN_TERRACOTTA), blockTexture(Blocks.CYAN_TERRACOTTA));
        slabBlock(((SlabBlock) JDBlocks.GRAY_TERRACOTTA_SLAB.get()), blockTexture(Blocks.GRAY_TERRACOTTA), blockTexture(Blocks.GRAY_TERRACOTTA));
        slabBlock(((SlabBlock) JDBlocks.GREEN_TERRACOTTA_SLAB.get()), blockTexture(Blocks.GREEN_TERRACOTTA), blockTexture(Blocks.GREEN_TERRACOTTA));
        slabBlock(((SlabBlock) JDBlocks.LIGHT_GRAY_TERRACOTTA_SLAB.get()), blockTexture(Blocks.LIGHT_GRAY_TERRACOTTA), blockTexture(Blocks.LIGHT_GRAY_TERRACOTTA));
        slabBlock(((SlabBlock) JDBlocks.LIGHT_BLUE_TERRACOTTA_SLAB.get()), blockTexture(Blocks.LIGHT_BLUE_TERRACOTTA), blockTexture(Blocks.LIGHT_BLUE_TERRACOTTA));
        slabBlock(((SlabBlock) JDBlocks.LIME_TERRACOTTA_SLAB.get()), blockTexture(Blocks.LIME_TERRACOTTA), blockTexture(Blocks.LIME_TERRACOTTA));
        slabBlock(((SlabBlock) JDBlocks.MAGENTA_TERRACOTTA_SLAB.get()), blockTexture(Blocks.MAGENTA_TERRACOTTA), blockTexture(Blocks.MAGENTA_TERRACOTTA));
        slabBlock(((SlabBlock) JDBlocks.ORANGE_TERRACOTTA_SLAB.get()), blockTexture(Blocks.ORANGE_TERRACOTTA), blockTexture(Blocks.ORANGE_TERRACOTTA));
        slabBlock(((SlabBlock) JDBlocks.PINK_TERRACOTTA_SLAB.get()), blockTexture(Blocks.PINK_TERRACOTTA), blockTexture(Blocks.PINK_TERRACOTTA));
        slabBlock(((SlabBlock) JDBlocks.PURPLE_TERRACOTTA_SLAB.get()), blockTexture(Blocks.PURPLE_TERRACOTTA), blockTexture(Blocks.PURPLE_TERRACOTTA));
        slabBlock(((SlabBlock) JDBlocks.RED_TERRACOTTA_SLAB.get()), blockTexture(Blocks.RED_TERRACOTTA), blockTexture(Blocks.RED_TERRACOTTA));
        slabBlock(((SlabBlock) JDBlocks.WHITE_TERRACOTTA_SLAB.get()), blockTexture(Blocks.WHITE_TERRACOTTA), blockTexture(Blocks.WHITE_TERRACOTTA));
        slabBlock(((SlabBlock) JDBlocks.YELLOW_TERRACOTTA_SLAB.get()), blockTexture(Blocks.YELLOW_TERRACOTTA), blockTexture(Blocks.YELLOW_TERRACOTTA));
        slabBlock(((SlabBlock) JDBlocks.BLACK_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.BLACK_CONCRETE_POWDER), blockTexture(Blocks.BLACK_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDBlocks.BLUE_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.BLUE_CONCRETE_POWDER), blockTexture(Blocks.BLUE_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDBlocks.BROWN_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.BROWN_CONCRETE_POWDER), blockTexture(Blocks.BROWN_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDBlocks.CYAN_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.CYAN_CONCRETE_POWDER), blockTexture(Blocks.CYAN_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDBlocks.GRAY_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.GRAY_CONCRETE_POWDER), blockTexture(Blocks.GRAY_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDBlocks.GREEN_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.GREEN_CONCRETE_POWDER), blockTexture(Blocks.GREEN_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDBlocks.LIGHT_BLUE_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.LIGHT_BLUE_CONCRETE_POWDER), blockTexture(Blocks.LIGHT_BLUE_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDBlocks.LIGHT_GRAY_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.LIGHT_GRAY_CONCRETE_POWDER), blockTexture(Blocks.LIGHT_GRAY_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDBlocks.LIME_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.LIME_CONCRETE_POWDER), blockTexture(Blocks.LIME_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDBlocks.MAGENTA_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.MAGENTA_CONCRETE_POWDER), blockTexture(Blocks.MAGENTA_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDBlocks.ORANGE_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.ORANGE_CONCRETE_POWDER), blockTexture(Blocks.ORANGE_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDBlocks.PINK_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.PINK_CONCRETE_POWDER), blockTexture(Blocks.PINK_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDBlocks.PURPLE_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.PURPLE_CONCRETE_POWDER), blockTexture(Blocks.PURPLE_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDBlocks.RED_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.RED_CONCRETE_POWDER), blockTexture(Blocks.RED_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDBlocks.WHITE_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.WHITE_CONCRETE_POWDER), blockTexture(Blocks.WHITE_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDBlocks.YELLOW_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.YELLOW_CONCRETE_POWDER), blockTexture(Blocks.YELLOW_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDBlocks.BLACK_CONCRETE_SLAB.get()), blockTexture(Blocks.BLACK_CONCRETE), blockTexture(Blocks.BLACK_CONCRETE));
        slabBlock(((SlabBlock) JDBlocks.BLUE_CONCRETE_SLAB.get()), blockTexture(Blocks.BLUE_CONCRETE), blockTexture(Blocks.BLUE_CONCRETE));
        slabBlock(((SlabBlock) JDBlocks.BROWN_CONCRETE_SLAB.get()), blockTexture(Blocks.BROWN_CONCRETE), blockTexture(Blocks.BROWN_CONCRETE));
        slabBlock(((SlabBlock) JDBlocks.CYAN_CONCRETE_SLAB.get()), blockTexture(Blocks.CYAN_CONCRETE), blockTexture(Blocks.CYAN_CONCRETE));
        slabBlock(((SlabBlock) JDBlocks.GRAY_CONCRETE_SLAB.get()), blockTexture(Blocks.GRAY_CONCRETE), blockTexture(Blocks.GRAY_CONCRETE));
        slabBlock(((SlabBlock) JDBlocks.GREEN_CONCRETE_SLAB.get()), blockTexture(Blocks.GREEN_CONCRETE), blockTexture(Blocks.GREEN_CONCRETE));
        slabBlock(((SlabBlock) JDBlocks.LIGHT_BLUE_CONCRETE_SLAB.get()), blockTexture(Blocks.LIGHT_BLUE_CONCRETE), blockTexture(Blocks.LIGHT_BLUE_CONCRETE));
        slabBlock(((SlabBlock) JDBlocks.LIGHT_GRAY_CONCRETE_SLAB.get()), blockTexture(Blocks.LIGHT_GRAY_CONCRETE), blockTexture(Blocks.LIGHT_GRAY_CONCRETE));
        slabBlock(((SlabBlock) JDBlocks.LIME_CONCRETE_SLAB.get()), blockTexture(Blocks.LIME_CONCRETE), blockTexture(Blocks.LIME_CONCRETE));
        slabBlock(((SlabBlock) JDBlocks.MAGENTA_CONCRETE_SLAB.get()), blockTexture(Blocks.MAGENTA_CONCRETE), blockTexture(Blocks.MAGENTA_CONCRETE));
        slabBlock(((SlabBlock) JDBlocks.ORANGE_CONCRETE_SLAB.get()), blockTexture(Blocks.ORANGE_CONCRETE), blockTexture(Blocks.ORANGE_CONCRETE));
        slabBlock(((SlabBlock) JDBlocks.PINK_CONCRETE_SLAB.get()), blockTexture(Blocks.PINK_CONCRETE), blockTexture(Blocks.PINK_CONCRETE));
        slabBlock(((SlabBlock) JDBlocks.PURPLE_CONCRETE_SLAB.get()), blockTexture(Blocks.PURPLE_CONCRETE), blockTexture(Blocks.PURPLE_CONCRETE));
        slabBlock(((SlabBlock) JDBlocks.RED_CONCRETE_SLAB.get()), blockTexture(Blocks.RED_CONCRETE), blockTexture(Blocks.RED_CONCRETE));
        slabBlock(((SlabBlock) JDBlocks.WHITE_CONCRETE_SLAB.get()), blockTexture(Blocks.WHITE_CONCRETE), blockTexture(Blocks.WHITE_CONCRETE));
        slabBlock(((SlabBlock) JDBlocks.YELLOW_CONCRETE_SLAB.get()), blockTexture(Blocks.YELLOW_CONCRETE), blockTexture(Blocks.YELLOW_CONCRETE));
        slabBlock(((SlabBlock) JDBlocks.GLOWSTONE_SLAB.get()), blockTexture(Blocks.GLOWSTONE), blockTexture(Blocks.GLOWSTONE));

        //FENCES
        fenceBlock(((FenceBlock) JDBlocks.SPRUCE_LOG_FENCE.get()), new ResourceLocation("block/spruce_log"));
        fenceBlock(((FenceBlock) JDBlocks.OAK_LOG_FENCE.get()), new ResourceLocation("block/oak_log"));
        fenceBlock(((FenceBlock) JDBlocks.DARK_OAK_LOG_FENCE.get()), new ResourceLocation("block/dark_oak_log"));
        fenceBlock(((FenceBlock) JDBlocks.ACACIA_LOG_FENCE.get()), new ResourceLocation("block/acacia_log"));
        fenceBlock(((FenceBlock) JDBlocks.JUNGLE_LOG_FENCE.get()), new ResourceLocation("block/jungle_log"));
        fenceBlock(((FenceBlock) JDBlocks.BIRCH_LOG_FENCE.get()), new ResourceLocation("block/birch_log"));
        fenceBlock(((FenceBlock) JDBlocks.WARPED_LOG_FENCE.get()), new ResourceLocation("block/warped_stem"));
        fenceBlock(((FenceBlock) JDBlocks.CRIMSON_LOG_FENCE.get()), new ResourceLocation("block/crimson_stem"));
        fenceBlock(((FenceBlock) JDBlocks.SPRUCE_SKINNED_LOG_FENCE.get()), new ResourceLocation("block/stripped_spruce_log"));
        fenceBlock(((FenceBlock) JDBlocks.OAK_SKINNED_LOG_FENCE.get()), new ResourceLocation("block/stripped_oak_log"));
        fenceBlock(((FenceBlock) JDBlocks.DARK_SKINNED_OAK_LOG_FENCE.get()), new ResourceLocation("block/stripped_dark_oak_log"));
        fenceBlock(((FenceBlock) JDBlocks.ACACIA_SKINNED_LOG_FENCE.get()), new ResourceLocation("block/stripped_acacia_log"));
        fenceBlock(((FenceBlock) JDBlocks.JUNGLE_SKINNED_LOG_FENCE.get()), new ResourceLocation("block/stripped_jungle_log"));
        fenceBlock(((FenceBlock) JDBlocks.BIRCH_SKINNED_LOG_FENCE.get()), new ResourceLocation("block/stripped_birch_log"));
        fenceBlock(((FenceBlock) JDBlocks.WARPED_SKINNED_LOG_FENCE.get()), new ResourceLocation("block/stripped_warped_stem"));
        fenceBlock(((FenceBlock) JDBlocks.CRIMSON_SKINNED_LOG_FENCE.get()), new ResourceLocation("block/stripped_crimson_stem"));

        //FENCE GATES
        fenceGateBlock(((FenceGateBlock) JDBlocks.SPRUCE_LOG_FENCE_GATE.get()), new ResourceLocation("block/spruce_log"));
        fenceGateBlock(((FenceGateBlock) JDBlocks.OAK_LOG_FENCE_GATE.get()), new ResourceLocation("block/oak_log"));
        fenceGateBlock(((FenceGateBlock) JDBlocks.DARK_OAK_LOG_FENCE_GATE.get()), new ResourceLocation("block/dark_oak_log"));
        fenceGateBlock(((FenceGateBlock) JDBlocks.ACACIA_LOG_FENCE_GATE.get()), new ResourceLocation("block/acacia_log"));
        fenceGateBlock(((FenceGateBlock) JDBlocks.JUNGLE_LOG_FENCE_GATE.get()), new ResourceLocation("block/jungle_log"));
        fenceGateBlock(((FenceGateBlock) JDBlocks.BIRCH_LOG_FENCE_GATE.get()), new ResourceLocation("block/birch_log"));
        fenceGateBlock(((FenceGateBlock) JDBlocks.WARPED_LOG_FENCE_GATE.get()), new ResourceLocation("block/warped_stem"));
        fenceGateBlock(((FenceGateBlock) JDBlocks.CRIMSON_LOG_FENCE_GATE.get()), new ResourceLocation("block/crimson_stem"));
        fenceGateBlock(((FenceGateBlock) JDBlocks.SPRUCE_SKINNED_LOG_FENCE_GATE.get()), new ResourceLocation("block/stripped_spruce_log"));
        fenceGateBlock(((FenceGateBlock) JDBlocks.OAK_SKINNED_LOG_FENCE_GATE.get()), new ResourceLocation("block/stripped_oak_log"));
        fenceGateBlock(((FenceGateBlock) JDBlocks.DARK_SKINNED_OAK_LOG_FENCE_GATE.get()), new ResourceLocation("block/stripped_dark_oak_log"));
        fenceGateBlock(((FenceGateBlock) JDBlocks.ACACIA_SKINNED_LOG_FENCE_GATE.get()), new ResourceLocation("block/stripped_acacia_log"));
        fenceGateBlock(((FenceGateBlock) JDBlocks.JUNGLE_SKINNED_LOG_FENCE_GATE.get()), new ResourceLocation("block/stripped_jungle_log"));
        fenceGateBlock(((FenceGateBlock) JDBlocks.BIRCH_SKINNED_LOG_FENCE_GATE.get()), new ResourceLocation("block/stripped_birch_log"));
        fenceGateBlock(((FenceGateBlock) JDBlocks.WARPED_SKINNED_LOG_FENCE_GATE.get()), new ResourceLocation("block/stripped_warped_stem"));
        fenceGateBlock(((FenceGateBlock) JDBlocks.CRIMSON_SKINNED_LOG_FENCE_GATE.get()), new ResourceLocation("block/stripped_crimson_stem"));

        //WALLS
        wallBlock(((WallBlock) JDBlocks.SPRUCE_LOG_WALL.get()), new ResourceLocation("block/spruce_log"));
        wallBlock(((WallBlock) JDBlocks.OAK_LOG_WALL.get()), new ResourceLocation("block/oak_log"));
        wallBlock(((WallBlock) JDBlocks.DARK_OAK_LOG_WALL.get()), new ResourceLocation("block/dark_oak_log"));
        wallBlock(((WallBlock) JDBlocks.ACACIA_LOG_WALL.get()), new ResourceLocation("block/acacia_log"));
        wallBlock(((WallBlock) JDBlocks.JUNGLE_LOG_WALL.get()), new ResourceLocation("block/jungle_log"));
        wallBlock(((WallBlock) JDBlocks.BIRCH_LOG_WALL.get()), new ResourceLocation("block/birch_log"));
        wallBlock(((WallBlock) JDBlocks.WARPED_LOG_WALL.get()), new ResourceLocation("block/warped_stem"));
        wallBlock(((WallBlock) JDBlocks.CRIMSON_LOG_WALL.get()), new ResourceLocation("block/crimson_stem"));
        wallBlock(((WallBlock) JDBlocks.AMETHYST_WALL.get()), blockTexture(Blocks.AMETHYST_BLOCK));
        wallBlock(((WallBlock) JDBlocks.CALCITE_WALL.get()), blockTexture(Blocks.CALCITE));
        wallBlock(((WallBlock) JDBlocks.SPRUCE_SKINNED_LOG_WALL.get()), new ResourceLocation("block/stripped_spruce_log"));
        wallBlock(((WallBlock) JDBlocks.OAK_SKINNED_LOG_WALL.get()), new ResourceLocation("block/stripped_oak_log"));
        wallBlock(((WallBlock) JDBlocks.DARK_SKINNED_OAK_LOG_WALL.get()), new ResourceLocation("block/stripped_dark_oak_log"));
        wallBlock(((WallBlock) JDBlocks.ACACIA_SKINNED_LOG_WALL.get()), new ResourceLocation("block/stripped_acacia_log"));
        wallBlock(((WallBlock) JDBlocks.JUNGLE_SKINNED_LOG_WALL.get()), new ResourceLocation("block/stripped_jungle_log"));
        wallBlock(((WallBlock) JDBlocks.BIRCH_SKINNED_LOG_WALL.get()), new ResourceLocation("block/stripped_birch_log"));
        wallBlock(((WallBlock) JDBlocks.WARPED_SKINNED_LOG_WALL.get()), new ResourceLocation("block/stripped_warped_stem"));
        wallBlock(((WallBlock) JDBlocks.CRIMSON_SKINNED_LOG_WALL.get()), new ResourceLocation("block/stripped_crimson_stem"));
        wallBlock(((WallBlock) JDBlocks.CLAY_WALL.get()), blockTexture(Blocks.CLAY));
        wallBlock(((WallBlock) JDBlocks.GRAVEL_WALL.get()), blockTexture(Blocks.GRAVEL));
        wallBlock(((WallBlock) JDBlocks.TUFF_WALL.get()), blockTexture(Blocks.TUFF));
        wallBlock(((WallBlock) JDBlocks.SAND_WALL.get()), blockTexture(Blocks.SAND));
        wallBlock(((WallBlock) JDBlocks.RED_SAND_WALL.get()), blockTexture(Blocks.RED_SAND));
        wallBlock(((WallBlock) JDBlocks.DIRT_WALL.get()), blockTexture(Blocks.DIRT));
        wallBlock(((WallBlock) JDBlocks.COARSE_DIRT_WALL.get()), blockTexture(Blocks.COARSE_DIRT));
        wallBlock(((WallBlock) JDBlocks.ROOTED_DIRT_WALL.get()), blockTexture(Blocks.ROOTED_DIRT));
        wallBlock(((WallBlock) JDBlocks.OBSIDIAN_WALL.get()), blockTexture(Blocks.OBSIDIAN));
        wallBlock(((WallBlock) JDBlocks.CRYING_OBSIDIAN_WALL.get()), blockTexture(Blocks.CRYING_OBSIDIAN));
        wallBlock(((WallBlock) JDBlocks.NETHERRACK_WALL.get()), blockTexture(Blocks.NETHERRACK));
        wallBlock(((WallBlock) JDBlocks.END_STONE_WALL.get()), blockTexture(Blocks.END_STONE));
        wallBlock(((WallBlock) JDBlocks.CHISELED_QUARTZ_WALL.get()), new ResourceLocation("block/chiseled_quartz_block"));
        wallBlock(((WallBlock) JDBlocks.QUARTZ_BRICKS_WALL.get()), blockTexture(Blocks.QUARTZ_BRICKS));
        wallBlock(((WallBlock) JDBlocks.QUARTZ_PILLAR_WALL.get()), new ResourceLocation("block/quartz_pillar"));
        wallBlock(((WallBlock) JDBlocks.BONE_BLOCK_WALL.get()), new ResourceLocation("block/bone_block_side"));
        wallBlock(((WallBlock) JDBlocks.SMOOTH_BASALT_WALL.get()), new ResourceLocation("block/smooth_basalt"));
        wallBlock(((WallBlock) JDBlocks.BASALT_WALL.get()), new ResourceLocation("block/basalt_side"));
        wallBlock(((WallBlock) JDBlocks.POLISHED_BASALT_WALL.get()), new ResourceLocation("block/polished_basalt_side"));
        wallBlock(((WallBlock) JDBlocks.WHITE_WOOL_WALL.get()), blockTexture(Blocks.WHITE_WOOL));
        wallBlock(((WallBlock) JDBlocks.ORANGE_WOOL_WALL.get()), blockTexture(Blocks.ORANGE_WOOL));
        wallBlock(((WallBlock) JDBlocks.MAGENTA_WOOL_WALL.get()), blockTexture(Blocks.MAGENTA_WOOL));
        wallBlock(((WallBlock) JDBlocks.LIGHT_BLUE_WOOL_WALL.get()), blockTexture(Blocks.LIGHT_BLUE_WOOL));
        wallBlock(((WallBlock) JDBlocks.YELLOW_WOOL_WALL.get()), blockTexture(Blocks.YELLOW_WOOL));
        wallBlock(((WallBlock) JDBlocks.LIME_WOOL_WALL.get()), blockTexture(Blocks.LIME_WOOL));
        wallBlock(((WallBlock) JDBlocks.PINK_WOOL_WALL.get()), blockTexture(Blocks.PINK_WOOL));
        wallBlock(((WallBlock) JDBlocks.GRAY_WOOL_WALL.get()), blockTexture(Blocks.GRAY_WOOL));
        wallBlock(((WallBlock) JDBlocks.LIGHT_GRAY_WOOL_WALL.get()), blockTexture(Blocks.LIGHT_GRAY_WOOL));
        wallBlock(((WallBlock) JDBlocks.CYAN_WOOL_WALL.get()), blockTexture(Blocks.CYAN_WOOL));
        wallBlock(((WallBlock) JDBlocks.PURPLE_WOOL_WALL.get()), blockTexture(Blocks.PURPLE_WOOL));
        wallBlock(((WallBlock) JDBlocks.BLUE_WOOL_WALL.get()), blockTexture(Blocks.BLUE_WOOL));
        wallBlock(((WallBlock) JDBlocks.BROWN_WOOL_WALL.get()), blockTexture(Blocks.BROWN_WOOL));
        wallBlock(((WallBlock) JDBlocks.GREEN_WOOL_WALL.get()), blockTexture(Blocks.GREEN_WOOL));
        wallBlock(((WallBlock) JDBlocks.RED_WOOL_WALL.get()), blockTexture(Blocks.RED_WOOL));
        wallBlock(((WallBlock) JDBlocks.BLACK_WOOL_WALL.get()), blockTexture(Blocks.BLACK_WOOL));
        wallBlock(((WallBlock) JDBlocks.CRACKED_NETHER_BRICKS_WALL.get()), blockTexture(Blocks.CRACKED_NETHER_BRICKS));
        wallBlock(((WallBlock) JDBlocks.CHISELED_NETHER_BRICKS_WALL.get()), blockTexture(Blocks.CHISELED_NETHER_BRICKS));
        wallBlock(((WallBlock) JDBlocks.CHISELED_RED_SANDSTONE_WALL.get()), blockTexture(Blocks.CHISELED_RED_SANDSTONE));
        wallBlock(((WallBlock) JDBlocks.CHISELED_SANDSTONE_WALL.get()), blockTexture(Blocks.CHISELED_SANDSTONE));
        wallBlock(((WallBlock) JDBlocks.CHISELED_STONE_BRICKS_WALL.get()), blockTexture(Blocks.CHISELED_STONE_BRICKS));
        wallBlock(((WallBlock) JDBlocks.CRACKED_STONE_BRICKS_WALL.get()), blockTexture(Blocks.CRACKED_STONE_BRICKS));
        wallBlock(((WallBlock) JDBlocks.CRACKED_POLISHED_BLACKSTONE_BRICKS_WALL.get()), blockTexture(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS));
        wallBlock(((WallBlock) JDBlocks.MOSS_BLOCK_WALL.get()), blockTexture(Blocks.MOSS_BLOCK));
        wallBlock(((WallBlock) JDBlocks.HONEYCOMB_BLOCK_WALL.get()), blockTexture(Blocks.HONEYCOMB_BLOCK));
        wallBlock(((WallBlock) JDBlocks.TERRACOTTA_WALL.get()), blockTexture(Blocks.TERRACOTTA));
        wallBlock(((WallBlock) JDBlocks.BLACK_TERRACOTTA_WALL.get()), blockTexture(Blocks.BLACK_TERRACOTTA));
        wallBlock(((WallBlock) JDBlocks.BLUE_TERRACOTTA_WALL.get()), blockTexture(Blocks.BLUE_TERRACOTTA));
        wallBlock(((WallBlock) JDBlocks.BROWN_TERRACOTTA_WALL.get()), blockTexture(Blocks.BROWN_TERRACOTTA));
        wallBlock(((WallBlock) JDBlocks.CYAN_TERRACOTTA_WALL.get()), blockTexture(Blocks.CYAN_TERRACOTTA));
        wallBlock(((WallBlock) JDBlocks.GRAY_TERRACOTTA_WALL.get()), blockTexture(Blocks.GRAY_TERRACOTTA));
        wallBlock(((WallBlock) JDBlocks.GREEN_TERRACOTTA_WALL.get()), blockTexture(Blocks.GREEN_TERRACOTTA));
        wallBlock(((WallBlock) JDBlocks.LIGHT_GRAY_TERRACOTTA_WALL.get()), blockTexture(Blocks.LIGHT_GRAY_TERRACOTTA));
        wallBlock(((WallBlock) JDBlocks.LIGHT_BLUE_TERRACOTTA_WALL.get()), blockTexture(Blocks.LIGHT_BLUE_TERRACOTTA));
        wallBlock(((WallBlock) JDBlocks.LIME_TERRACOTTA_WALL.get()), blockTexture(Blocks.LIME_TERRACOTTA));
        wallBlock(((WallBlock) JDBlocks.MAGENTA_TERRACOTTA_WALL.get()), blockTexture(Blocks.MAGENTA_TERRACOTTA));
        wallBlock(((WallBlock) JDBlocks.ORANGE_TERRACOTTA_WALL.get()), blockTexture(Blocks.ORANGE_TERRACOTTA));
        wallBlock(((WallBlock) JDBlocks.PINK_TERRACOTTA_WALL.get()), blockTexture(Blocks.PINK_TERRACOTTA));
        wallBlock(((WallBlock) JDBlocks.PURPLE_TERRACOTTA_WALL.get()), blockTexture(Blocks.PURPLE_TERRACOTTA));
        wallBlock(((WallBlock) JDBlocks.RED_TERRACOTTA_WALL.get()), blockTexture(Blocks.RED_TERRACOTTA));
        wallBlock(((WallBlock) JDBlocks.WHITE_TERRACOTTA_WALL.get()), blockTexture(Blocks.WHITE_TERRACOTTA));
        wallBlock(((WallBlock) JDBlocks.YELLOW_TERRACOTTA_WALL.get()), blockTexture(Blocks.YELLOW_TERRACOTTA));
        wallBlock(((WallBlock) JDBlocks.BLACK_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.BLACK_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDBlocks.BLUE_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.BLUE_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDBlocks.BROWN_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.BROWN_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDBlocks.CYAN_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.CYAN_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDBlocks.GRAY_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.GRAY_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDBlocks.GREEN_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.GREEN_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDBlocks.LIGHT_BLUE_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.LIGHT_BLUE_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDBlocks.LIGHT_GRAY_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.LIGHT_GRAY_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDBlocks.LIME_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.LIME_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDBlocks.MAGENTA_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.MAGENTA_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDBlocks.ORANGE_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.ORANGE_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDBlocks.PINK_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.PINK_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDBlocks.PURPLE_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.PURPLE_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDBlocks.RED_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.RED_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDBlocks.WHITE_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.WHITE_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDBlocks.YELLOW_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.YELLOW_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDBlocks.BLACK_CONCRETE_WALL.get()), blockTexture(Blocks.BLACK_CONCRETE));
        wallBlock(((WallBlock) JDBlocks.BLUE_CONCRETE_WALL.get()), blockTexture(Blocks.BLUE_CONCRETE));
        wallBlock(((WallBlock) JDBlocks.BROWN_CONCRETE_WALL.get()), blockTexture(Blocks.BROWN_CONCRETE));
        wallBlock(((WallBlock) JDBlocks.CYAN_CONCRETE_WALL.get()), blockTexture(Blocks.CYAN_CONCRETE));
        wallBlock(((WallBlock) JDBlocks.GRAY_CONCRETE_WALL.get()), blockTexture(Blocks.GRAY_CONCRETE));
        wallBlock(((WallBlock) JDBlocks.GREEN_CONCRETE_WALL.get()), blockTexture(Blocks.GREEN_CONCRETE));
        wallBlock(((WallBlock) JDBlocks.LIGHT_BLUE_CONCRETE_WALL.get()), blockTexture(Blocks.LIGHT_BLUE_CONCRETE));
        wallBlock(((WallBlock) JDBlocks.LIGHT_GRAY_CONCRETE_WALL.get()), blockTexture(Blocks.LIGHT_GRAY_CONCRETE));
        wallBlock(((WallBlock) JDBlocks.LIME_CONCRETE_WALL.get()), blockTexture(Blocks.LIME_CONCRETE));
        wallBlock(((WallBlock) JDBlocks.MAGENTA_CONCRETE_WALL.get()), blockTexture(Blocks.MAGENTA_CONCRETE));
        wallBlock(((WallBlock) JDBlocks.ORANGE_CONCRETE_WALL.get()), blockTexture(Blocks.ORANGE_CONCRETE));
        wallBlock(((WallBlock) JDBlocks.PINK_CONCRETE_WALL.get()), blockTexture(Blocks.PINK_CONCRETE));
        wallBlock(((WallBlock) JDBlocks.PURPLE_CONCRETE_WALL.get()), blockTexture(Blocks.PURPLE_CONCRETE));
        wallBlock(((WallBlock) JDBlocks.RED_CONCRETE_WALL.get()), blockTexture(Blocks.RED_CONCRETE));
        wallBlock(((WallBlock) JDBlocks.WHITE_CONCRETE_WALL.get()), blockTexture(Blocks.WHITE_CONCRETE));
        wallBlock(((WallBlock) JDBlocks.YELLOW_CONCRETE_WALL.get()), blockTexture(Blocks.YELLOW_CONCRETE));
        wallBlock(((WallBlock) JDBlocks.MANGROVE_PLANK_WALL.get()), blockTexture(Blocks.MANGROVE_PLANKS));
        wallBlock(((WallBlock) JDBlocks.OAK_PLANK_WALL.get()), blockTexture(Blocks.OAK_PLANKS));
        wallBlock(((WallBlock) JDBlocks.DARK_OAK_PLANK_WALL.get()), blockTexture(Blocks.DARK_OAK_PLANKS));
        wallBlock(((WallBlock) JDBlocks.SPRUCE_PLANK_WALL.get()), blockTexture(Blocks.SPRUCE_PLANKS));
        wallBlock(((WallBlock) JDBlocks.JUNGLE_PLANK_WALL.get()), blockTexture(Blocks.JUNGLE_PLANKS));
        wallBlock(((WallBlock) JDBlocks.ACACIA_PLANK_WALL.get()), blockTexture(Blocks.ACACIA_PLANKS));
        wallBlock(((WallBlock) JDBlocks.BIRCH_PLANK_WALL.get()), blockTexture(Blocks.BIRCH_PLANKS));
        wallBlock(((WallBlock) JDBlocks.CRIMSON_PLANK_WALL.get()), blockTexture(Blocks.CRIMSON_PLANKS));
        wallBlock(((WallBlock) JDBlocks.WARPED_PLANK_WALL.get()), blockTexture(Blocks.WARPED_PLANKS));
        wallBlock(((WallBlock) JDBlocks.MANGROVE_LOG_WALL.get()), new ResourceLocation("block/mangrove_log"));
        wallBlock(((WallBlock) JDBlocks.PACKED_MUD_WALL.get()), blockTexture(Blocks.PACKED_MUD));
        wallBlock(((WallBlock) JDBlocks.MUDDY_MANGROVE_ROOTS_WALL.get()), new ResourceLocation("block/muddy_mangrove_roots_side"));
        wallBlock(((WallBlock) JDBlocks.STRIPPED_MANGROVE_LOG_WALL.get()), new ResourceLocation("block/stripped_mangrove_log"));
        wallBlock(((WallBlock) JDBlocks.MUD_WALL.get()), blockTexture(Blocks.MUD));
        wallBlock(((WallBlock) JDBlocks.OCHRE_FROGLIGHT_WALL.get()), new ResourceLocation("block/ochre_froglight_side"));
        wallBlock(((WallBlock) JDBlocks.VERDANT_FROGLIGHT_WALL.get()), new ResourceLocation("block/verdant_froglight_side"));
        wallBlock(((WallBlock) JDBlocks.PEARLESCENT_FROGLIGHT_WALL.get()), new ResourceLocation("block/pearlescent_froglight_side"));
        wallBlock(((WallBlock) JDBlocks.SMOOTH_STONE_WALL.get()), blockTexture(Blocks.SMOOTH_STONE));
        wallBlock(((WallBlock) JDBlocks.GLOWSTONE_WALL.get()), blockTexture(Blocks.GLOWSTONE));

    }

    private void blockWithItem(RegistryObject<Block> blockRegistryObject) {
        simpleBlockWithItem(blockRegistryObject.get(), cubeAll(blockRegistryObject.get()));
    }

}