package com.jaydizzle.buildingblocks.datagen;

import com.jaydizzle.buildingblocks.BuildingBlocks;
import com.jaydizzle.buildingblocks.block.*;
import com.jaydizzle.buildingblocks.block.custom.JDBlocks;
import net.minecraft.data.PackOutput;
import net.minecraft.world.level.block.*;
import net.minecraftforge.client.model.generators.BlockStateProvider;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraftforge.registries.RegistryObject;

public class JDBlockStateProvider extends BlockStateProvider {
    public JDBlockStateProvider(PackOutput output, ExistingFileHelper exFileHelper) {
        super(output, BuildingBlocks.MOD_ID, exFileHelper);
    }

    @Override
    protected void registerStatesAndModels() {

        //CUSTOM BLOCKS
        blockWithItem(JDBlocks.PINK_CALCITE);
        blockWithItem(JDBlocks.PURPLE_CALCITE);
        blockWithItem(JDBlocks.ORANGE_CALCITE);
        blockWithItem(JDBlocks.LIGHT_BLUE_CALCITE);
        blockWithItem(JDBlocks.YELLOW_CALCITE);
        blockWithItem(JDBlocks.LIME_CALCITE);
        blockWithItem(JDBlocks.BLUE_CALCITE);
        blockWithItem(JDBlocks.LIGHT_GRAY_CALCITE);
        blockWithItem(JDBlocks.MAGENTA_CALCITE);
        blockWithItem(JDBlocks.GRAY_CALCITE);
        blockWithItem(JDBlocks.BLUE_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.BROWN_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.CYAN_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.GRAY_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.GREEN_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.LIGHT_BLUE_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.LIGHT_GRAY_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.LIME_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.MAGENTA_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.ORANGE_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.PINK_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.PURPLE_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.RED_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.WHITE_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.YELLOW_CONCRETE_BRICKS);
        blockWithItem(JDBlocks.YELLOW_BRICKS);
        blockWithItem(JDBlocks.RED_BRICKS);
        blockWithItem(JDBlocks.BLACK_BRICKS);
        blockWithItem(JDBlocks.WHITE_BRICKS);
        blockWithItem(JDBlocks.BROWN_BRICKS);
        blockWithItem(JDBlocks.AQUA_BRICKS);
        blockWithItem(JDBlocks.ORANGE_BRICKS);
        blockWithItem(JDBlocks.GREEN_BRICKS);
        blockWithItem(JDBlocks.GRAY_BRICKS);
        blockWithItem(JDBlocks.BLUE_BRICKS);
        blockWithItem(JDBlocks.PURPLE_BRICKS);
        blockWithItem(JDBlocks.BASIC_BRICKS);

        //STAIRS
        stairsBlock(((StairBlock) JDStairs.SPRUCE_LOG_STAIRS.get()), blockTexture(Blocks.SPRUCE_LOG));
        stairsBlock(((StairBlock) JDStairs.OAK_LOG_STAIRS.get()), blockTexture(Blocks.OAK_LOG));
        stairsBlock(((StairBlock) JDStairs.DARK_OAK_LOG_STAIRS.get()), blockTexture(Blocks.DARK_OAK_LOG));
        stairsBlock(((StairBlock) JDStairs.ACACIA_LOG_STAIRS.get()), blockTexture(Blocks.ACACIA_LOG));
        stairsBlock(((StairBlock) JDStairs.JUNGLE_LOG_STAIRS.get()), blockTexture(Blocks.JUNGLE_LOG));
        stairsBlock(((StairBlock) JDStairs.BIRCH_LOG_STAIRS.get()), blockTexture(Blocks.BIRCH_LOG));
        stairsBlock(((StairBlock) JDStairs.WARPED_LOG_STAIRS.get()), blockTexture(Blocks.WARPED_HYPHAE));
        stairsBlock(((StairBlock) JDStairs.CRIMSON_LOG_STAIRS.get()), blockTexture(Blocks.CRIMSON_HYPHAE));
        stairsBlock(((StairBlock) JDStairs.AMETHYST_STAIRS.get()), blockTexture(Blocks.AMETHYST_BLOCK));
        stairsBlock(((StairBlock) JDStairs.CALCITE_STAIRS.get()), blockTexture(Blocks.CALCITE));
        stairsBlock(((StairBlock) JDStairs.SPRUCE_SKINNED_LOG_STAIRS.get()), blockTexture(Blocks.STRIPPED_SPRUCE_LOG));
        stairsBlock(((StairBlock) JDStairs.OAK_SKINNED_LOG_STAIRS.get()), blockTexture(Blocks.STRIPPED_OAK_LOG));
        stairsBlock(((StairBlock) JDStairs.DARK_OAK_SKINNED_LOG_STAIRS.get()), blockTexture(Blocks.STRIPPED_DARK_OAK_LOG));
        stairsBlock(((StairBlock) JDStairs.ACACIA_SKINNED_LOG_STAIRS.get()), blockTexture(Blocks.STRIPPED_ACACIA_LOG));
        stairsBlock(((StairBlock) JDStairs.JUNGLE_SKINNED_LOG_STAIRS.get()), blockTexture(Blocks.STRIPPED_JUNGLE_LOG));
        stairsBlock(((StairBlock) JDStairs.BIRCH_SKINNED_LOG_STAIRS.get()), blockTexture(Blocks.STRIPPED_BIRCH_LOG));
        stairsBlock(((StairBlock) JDStairs.WARPED_SKINNED_LOG_STAIRS.get()), blockTexture(Blocks.STRIPPED_WARPED_HYPHAE));
        stairsBlock(((StairBlock) JDStairs.CRIMSON_SKINNED_LOG_STAIRS.get()), blockTexture(Blocks.STRIPPED_CRIMSON_HYPHAE));
        stairsBlock(((StairBlock) JDStairs.CLAY_STAIRS.get()), blockTexture(Blocks.CLAY));
        stairsBlock(((StairBlock) JDStairs.GRAVEL_STAIRS.get()), blockTexture(Blocks.GRAVEL));
        stairsBlock(((StairBlock) JDStairs.TUFF_STAIRS.get()), blockTexture(Blocks.TUFF));
        stairsBlock(((StairBlock) JDStairs.SAND_STAIRS.get()), blockTexture(Blocks.SAND));
        stairsBlock(((StairBlock) JDStairs.RED_SAND_STAIRS.get()), blockTexture(Blocks.RED_SAND));
        stairsBlock(((StairBlock) JDStairs.DIRT_STAIRS.get()), blockTexture(Blocks.DIRT));
        stairsBlock(((StairBlock) JDStairs.COARSE_DIRT_STAIRS.get()), blockTexture(Blocks.COARSE_DIRT));
        stairsBlock(((StairBlock) JDStairs.ROOTED_DIRT_STAIRS.get()), blockTexture(Blocks.ROOTED_DIRT));
        stairsBlock(((StairBlock) JDStairs.OBSIDIAN_STAIRS.get()), blockTexture(Blocks.OBSIDIAN));
        stairsBlock(((StairBlock) JDStairs.CRYING_OBSIDIAN_STAIRS.get()), blockTexture(Blocks.CRYING_OBSIDIAN));
        stairsBlock(((StairBlock) JDStairs.NETHERRACK_STAIRS.get()), blockTexture(Blocks.NETHERRACK));
        stairsBlock(((StairBlock) JDStairs.END_STONE_STAIRS.get()), blockTexture(Blocks.END_STONE));
        stairsBlock(((StairBlock) JDStairs.CHISELED_QUARTZ_STAIRS.get()), blockTexture(Blocks.CHISELED_QUARTZ_BLOCK));
        stairsBlock(((StairBlock) JDStairs.QUARTZ_BRICKS_STAIRS.get()), blockTexture(Blocks.QUARTZ_BRICKS));
        stairsBlock(((StairBlock) JDStairs.QUARTZ_PILLAR_STAIRS.get()), blockTexture(Blocks.QUARTZ_PILLAR));
        stairsBlock(((StairBlock) JDStairs.BONE_BLOCK_STAIRS.get()), blockTexture(Blocks.BONE_BLOCK));
        stairsBlock(((StairBlock) JDStairs.SMOOTH_BASALT_STAIRS.get()), blockTexture(Blocks.SMOOTH_BASALT));
        stairsBlock(((StairBlock) JDStairs.BASALT_STAIRS.get()), blockTexture(Blocks.BASALT));
        stairsBlock(((StairBlock) JDStairs.POLISHED_BASALT_STAIRS.get()), blockTexture(Blocks.POLISHED_BASALT));
        stairsBlock(((StairBlock) JDStairs.WHITE_WOOL_STAIRS.get()), blockTexture(Blocks.WHITE_WOOL));
        stairsBlock(((StairBlock) JDStairs.ORANGE_WOOL_STAIRS.get()), blockTexture(Blocks.ORANGE_WOOL));
        stairsBlock(((StairBlock) JDStairs.MAGENTA_WOOL_STAIRS.get()), blockTexture(Blocks.MAGENTA_WOOL));
        stairsBlock(((StairBlock) JDStairs.LIGHT_BLUE_WOOL_STAIRS.get()), blockTexture(Blocks.LIGHT_BLUE_WOOL));
        stairsBlock(((StairBlock) JDStairs.YELLOW_WOOL_STAIRS.get()), blockTexture(Blocks.YELLOW_WOOL));
        stairsBlock(((StairBlock) JDStairs.LIME_WOOL_STAIRS.get()), blockTexture(Blocks.LIME_WOOL));
        stairsBlock(((StairBlock) JDStairs.PINK_WOOL_STAIRS.get()), blockTexture(Blocks.PINK_WOOL));
        stairsBlock(((StairBlock) JDStairs.GRAY_WOOL_STAIRS.get()), blockTexture(Blocks.GRAY_WOOL));
        stairsBlock(((StairBlock) JDStairs.LIGHT_GRAY_WOOL_STAIRS.get()), blockTexture(Blocks.LIGHT_GRAY_WOOL));
        stairsBlock(((StairBlock) JDStairs.CYAN_WOOL_STAIRS.get()), blockTexture(Blocks.CYAN_WOOL));
        stairsBlock(((StairBlock) JDStairs.PURPLE_WOOL_STAIRS.get()), blockTexture(Blocks.PURPLE_WOOL));
        stairsBlock(((StairBlock) JDStairs.BLUE_WOOL_STAIRS.get()), blockTexture(Blocks.BLUE_WOOL));
        stairsBlock(((StairBlock) JDStairs.BROWN_WOOL_STAIRS.get()), blockTexture(Blocks.BROWN_WOOL));
        stairsBlock(((StairBlock) JDStairs.GREEN_WOOL_STAIRS.get()), blockTexture(Blocks.GREEN_WOOL));
        stairsBlock(((StairBlock) JDStairs.RED_WOOL_STAIRS.get()), blockTexture(Blocks.RED_WOOL));
        stairsBlock(((StairBlock) JDStairs.BLACK_WOOL_STAIRS.get()), blockTexture(Blocks.BLACK_WOOL));
        stairsBlock(((StairBlock) JDStairs.CRACKED_NETHER_BRICKS_STAIRS.get()), blockTexture(Blocks.CRACKED_NETHER_BRICKS));
        stairsBlock(((StairBlock) JDStairs.CHISELED_NETHER_BRICKS_STAIRS.get()), blockTexture(Blocks.CHISELED_NETHER_BRICKS));
        stairsBlock(((StairBlock) JDStairs.CHISELED_RED_SANDSTONE_STAIRS.get()), blockTexture(Blocks.CHISELED_RED_SANDSTONE));
        stairsBlock(((StairBlock) JDStairs.CHISELED_SANDSTONE_STAIRS.get()), blockTexture(Blocks.CHISELED_SANDSTONE));
        stairsBlock(((StairBlock) JDStairs.CHISELED_STONE_BRICKS_STAIRS.get()), blockTexture(Blocks.CHISELED_STONE_BRICKS));
        stairsBlock(((StairBlock) JDStairs.CRACKED_STONE_BRICKS_STAIRS.get()), blockTexture(Blocks.CRACKED_STONE_BRICKS));
        stairsBlock(((StairBlock) JDStairs.CRACKED_POLISHED_BLACKSTONE_BRICKS_STAIRS.get()), blockTexture(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS));
        stairsBlock(((StairBlock) JDStairs.MOSS_BLOCK_STAIRS.get()), blockTexture(Blocks.MOSS_BLOCK));
        stairsBlock(((StairBlock) JDStairs.HONEYCOMB_BLOCK_STAIRS.get()), blockTexture(Blocks.HONEYCOMB_BLOCK));
        stairsBlock(((StairBlock) JDStairs.TERRACOTTA_STAIRS.get()), blockTexture(Blocks.TERRACOTTA));
        stairsBlock(((StairBlock) JDStairs.BLACK_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.BLACK_TERRACOTTA));
        stairsBlock(((StairBlock) JDStairs.BLUE_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.BLUE_TERRACOTTA));
        stairsBlock(((StairBlock) JDStairs.BROWN_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.BROWN_TERRACOTTA));
        stairsBlock(((StairBlock) JDStairs.CYAN_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.CYAN_TERRACOTTA));
        stairsBlock(((StairBlock) JDStairs.GRAY_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.GRAY_TERRACOTTA));
        stairsBlock(((StairBlock) JDStairs.GREEN_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.GREEN_TERRACOTTA));
        stairsBlock(((StairBlock) JDStairs.LIGHT_GRAY_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.LIGHT_GRAY_TERRACOTTA));
        stairsBlock(((StairBlock) JDStairs.LIGHT_BLUE_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.LIGHT_BLUE_TERRACOTTA));
        stairsBlock(((StairBlock) JDStairs.LIME_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.LIME_TERRACOTTA));
        stairsBlock(((StairBlock) JDStairs.MAGENTA_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.MAGENTA_TERRACOTTA));
        stairsBlock(((StairBlock) JDStairs.ORANGE_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.ORANGE_TERRACOTTA));
        stairsBlock(((StairBlock) JDStairs.PINK_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.PINK_TERRACOTTA));
        stairsBlock(((StairBlock) JDStairs.PURPLE_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.PURPLE_TERRACOTTA));
        stairsBlock(((StairBlock) JDStairs.RED_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.RED_TERRACOTTA));
        stairsBlock(((StairBlock) JDStairs.WHITE_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.WHITE_TERRACOTTA));
        stairsBlock(((StairBlock) JDStairs.YELLOW_TERRACOTTA_STAIRS.get()), blockTexture(Blocks.YELLOW_TERRACOTTA));
        stairsBlock(((StairBlock) JDStairs.BLACK_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.BLACK_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDStairs.BLUE_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.BLUE_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDStairs.BROWN_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.BROWN_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDStairs.CYAN_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.CYAN_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDStairs.GRAY_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.GRAY_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDStairs.GREEN_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.GREEN_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDStairs.LIGHT_BLUE_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.LIGHT_BLUE_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDStairs.LIGHT_GRAY_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.LIGHT_GRAY_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDStairs.LIME_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.LIME_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDStairs.MAGENTA_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.MAGENTA_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDStairs.ORANGE_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.ORANGE_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDStairs.PINK_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.PINK_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDStairs.PURPLE_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.PURPLE_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDStairs.RED_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.RED_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDStairs.WHITE_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.WHITE_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDStairs.YELLOW_CONCRETE_POWDER_STAIRS.get()), blockTexture(Blocks.YELLOW_CONCRETE_POWDER));
        stairsBlock(((StairBlock) JDStairs.BLACK_CONCRETE_STAIRS.get()), blockTexture(Blocks.BLACK_CONCRETE));
        stairsBlock(((StairBlock) JDStairs.BLUE_CONCRETE_STAIRS.get()), blockTexture(Blocks.BLUE_CONCRETE));
        stairsBlock(((StairBlock) JDStairs.BROWN_CONCRETE_STAIRS.get()), blockTexture(Blocks.BROWN_CONCRETE));
        stairsBlock(((StairBlock) JDStairs.CYAN_CONCRETE_STAIRS.get()), blockTexture(Blocks.CYAN_CONCRETE));
        stairsBlock(((StairBlock) JDStairs.GRAY_CONCRETE_STAIRS.get()), blockTexture(Blocks.GRAY_CONCRETE));
        stairsBlock(((StairBlock) JDStairs.GREEN_CONCRETE_STAIRS.get()), blockTexture(Blocks.GREEN_CONCRETE));
        stairsBlock(((StairBlock) JDStairs.LIGHT_BLUE_CONCRETE_STAIRS.get()), blockTexture(Blocks.LIGHT_BLUE_CONCRETE));
        stairsBlock(((StairBlock) JDStairs.LIGHT_GRAY_CONCRETE_STAIRS.get()), blockTexture(Blocks.LIGHT_GRAY_CONCRETE));
        stairsBlock(((StairBlock) JDStairs.LIME_CONCRETE_STAIRS.get()), blockTexture(Blocks.LIME_CONCRETE));
        stairsBlock(((StairBlock) JDStairs.MAGENTA_CONCRETE_STAIRS.get()), blockTexture(Blocks.MAGENTA_CONCRETE));
        stairsBlock(((StairBlock) JDStairs.ORANGE_CONCRETE_STAIRS.get()), blockTexture(Blocks.ORANGE_CONCRETE));
        stairsBlock(((StairBlock) JDStairs.PINK_CONCRETE_STAIRS.get()), blockTexture(Blocks.PINK_CONCRETE));
        stairsBlock(((StairBlock) JDStairs.PURPLE_CONCRETE_STAIRS.get()), blockTexture(Blocks.PURPLE_CONCRETE));
        stairsBlock(((StairBlock) JDStairs.RED_CONCRETE_STAIRS.get()), blockTexture(Blocks.RED_CONCRETE));
        stairsBlock(((StairBlock) JDStairs.WHITE_CONCRETE_STAIRS.get()), blockTexture(Blocks.WHITE_CONCRETE));
        stairsBlock(((StairBlock) JDStairs.YELLOW_CONCRETE_STAIRS.get()), blockTexture(Blocks.YELLOW_CONCRETE));

        //SLABS
        slabBlock(((SlabBlock) JDSlabs.SPRUCE_LOG_SLAB.get()), blockTexture(Blocks.SPRUCE_LOG), blockTexture(Blocks.SPRUCE_LOG));
        slabBlock(((SlabBlock) JDSlabs.OAK_LOG_SLAB.get()), blockTexture(Blocks.OAK_LOG), blockTexture(Blocks.OAK_LOG));
        slabBlock(((SlabBlock) JDSlabs.DARK_OAK_LOG_SLAB.get()), blockTexture(Blocks.DARK_OAK_LOG), blockTexture(Blocks.DARK_OAK_LOG));
        slabBlock(((SlabBlock) JDSlabs.ACACIA_LOG_SLAB.get()), blockTexture(Blocks.ACACIA_LOG), blockTexture(Blocks.ACACIA_LOG));
        slabBlock(((SlabBlock) JDSlabs.JUNGLE_LOG_SLAB.get()), blockTexture(Blocks.JUNGLE_LOG), blockTexture(Blocks.JUNGLE_LOG));
        slabBlock(((SlabBlock) JDSlabs.BIRCH_LOG_SLAB.get()), blockTexture(Blocks.BIRCH_LOG), blockTexture(Blocks.BIRCH_LOG));
        slabBlock(((SlabBlock) JDSlabs.WARPED_LOG_SLAB.get()), blockTexture(Blocks.WARPED_HYPHAE), blockTexture(Blocks.WARPED_HYPHAE));
        slabBlock(((SlabBlock) JDSlabs.CRIMSON_LOG_SLAB.get()), blockTexture(Blocks.CRIMSON_HYPHAE), blockTexture(Blocks.CRIMSON_HYPHAE));
        slabBlock(((SlabBlock) JDSlabs.AMETHYST_SLAB.get()), blockTexture(Blocks.AMETHYST_BLOCK), blockTexture(Blocks.AMETHYST_BLOCK));
        slabBlock(((SlabBlock) JDSlabs.CALCITE_SLAB.get()), blockTexture(Blocks.CALCITE), blockTexture(Blocks.CALCITE));
        slabBlock(((SlabBlock) JDSlabs.SPRUCE_SKINNED_LOG_SLAB.get()), blockTexture(Blocks.STRIPPED_SPRUCE_LOG), blockTexture(Blocks.STRIPPED_SPRUCE_LOG));
        slabBlock(((SlabBlock) JDSlabs.OAK_SKINNED_LOG_SLAB.get()), blockTexture(Blocks.STRIPPED_OAK_LOG), blockTexture(Blocks.STRIPPED_OAK_LOG));
        slabBlock(((SlabBlock) JDSlabs.DARK_SKINNED_OAK_LOG_SLAB.get()), blockTexture(Blocks.STRIPPED_DARK_OAK_LOG), blockTexture(Blocks.STRIPPED_DARK_OAK_LOG));
        slabBlock(((SlabBlock) JDSlabs.ACACIA_SKINNED_LOG_SLAB.get()), blockTexture(Blocks.STRIPPED_ACACIA_LOG), blockTexture(Blocks.STRIPPED_ACACIA_LOG));
        slabBlock(((SlabBlock) JDSlabs.JUNGLE_SKINNED_LOG_SLAB.get()), blockTexture(Blocks.STRIPPED_JUNGLE_LOG), blockTexture(Blocks.STRIPPED_JUNGLE_LOG));
        slabBlock(((SlabBlock) JDSlabs.BIRCH_SKINNED_LOG_SLAB.get()), blockTexture(Blocks.STRIPPED_BIRCH_LOG), blockTexture(Blocks.STRIPPED_BIRCH_LOG));
        slabBlock(((SlabBlock) JDSlabs.WARPED_SKINNED_LOG_SLAB.get()), blockTexture(Blocks.STRIPPED_WARPED_HYPHAE), blockTexture(Blocks.STRIPPED_WARPED_HYPHAE));
        slabBlock(((SlabBlock) JDSlabs.CRIMSON_SKINNED_LOG_SLAB.get()), blockTexture(Blocks.STRIPPED_CRIMSON_HYPHAE), blockTexture(Blocks.STRIPPED_CRIMSON_HYPHAE));
        slabBlock(((SlabBlock) JDSlabs.CLAY_SLAB.get()), blockTexture(Blocks.CLAY), blockTexture(Blocks.CLAY));
        slabBlock(((SlabBlock) JDSlabs.GRAVEL_SLAB.get()), blockTexture(Blocks.GRAVEL), blockTexture(Blocks.GRAVEL));
        slabBlock(((SlabBlock) JDSlabs.TUFF_SLAB.get()), blockTexture(Blocks.TUFF), blockTexture(Blocks.TUFF));
        slabBlock(((SlabBlock) JDSlabs.SAND_SLAB.get()), blockTexture(Blocks.SAND), blockTexture(Blocks.SAND));
        slabBlock(((SlabBlock) JDSlabs.RED_SAND_SLAB.get()), blockTexture(Blocks.RED_SAND), blockTexture(Blocks.RED_SAND));
        slabBlock(((SlabBlock) JDSlabs.DIRT_SLAB.get()), blockTexture(Blocks.DIRT), blockTexture(Blocks.DIRT));
        slabBlock(((SlabBlock) JDSlabs.COARSE_DIRT_SLAB.get()), blockTexture(Blocks.COARSE_DIRT), blockTexture(Blocks.COARSE_DIRT));
        slabBlock(((SlabBlock) JDSlabs.ROOTED_DIRT_SLAB.get()), blockTexture(Blocks.ROOTED_DIRT), blockTexture(Blocks.ROOTED_DIRT));
        slabBlock(((SlabBlock) JDSlabs.OBSIDIAN_SLAB.get()), blockTexture(Blocks.OBSIDIAN), blockTexture(Blocks.OBSIDIAN));
        slabBlock(((SlabBlock) JDSlabs.CRYING_OBSIDIAN_SLAB.get()), blockTexture(Blocks.CRYING_OBSIDIAN), blockTexture(Blocks.CRYING_OBSIDIAN));
        slabBlock(((SlabBlock) JDSlabs.NETHERRACK_SLAB.get()), blockTexture(Blocks.NETHERRACK), blockTexture(Blocks.NETHERRACK));
        slabBlock(((SlabBlock) JDSlabs.END_STONE_SLAB.get()), blockTexture(Blocks.END_STONE), blockTexture(Blocks.END_STONE));
        slabBlock(((SlabBlock) JDSlabs.CHISELED_QUARTZ_SLAB.get()), blockTexture(Blocks.CHISELED_QUARTZ_BLOCK), blockTexture(Blocks.CHISELED_QUARTZ_BLOCK));
        slabBlock(((SlabBlock) JDSlabs.QUARTZ_BRICKS_SLAB.get()), blockTexture(Blocks.QUARTZ_BRICKS), blockTexture(Blocks.QUARTZ_BRICKS));
        slabBlock(((SlabBlock) JDSlabs.QUARTZ_PILLAR_SLAB.get()), blockTexture(Blocks.QUARTZ_PILLAR), blockTexture(Blocks.QUARTZ_PILLAR));
        slabBlock(((SlabBlock) JDSlabs.BONE_BLOCK_SLAB.get()), blockTexture(Blocks.BONE_BLOCK), blockTexture(Blocks.BONE_BLOCK));
        slabBlock(((SlabBlock) JDSlabs.SMOOTH_BASALT_SLAB.get()), blockTexture(Blocks.SMOOTH_BASALT), blockTexture(Blocks.SMOOTH_BASALT));
        slabBlock(((SlabBlock) JDSlabs.BASALT_SLAB.get()), blockTexture(Blocks.BASALT), blockTexture(Blocks.BASALT));
        slabBlock(((SlabBlock) JDSlabs.POLISHED_BASALT_SLAB.get()), blockTexture(Blocks.POLISHED_BASALT), blockTexture(Blocks.POLISHED_BASALT));
        slabBlock(((SlabBlock) JDSlabs.WHITE_WOOL_SLAB.get()), blockTexture(Blocks.WHITE_WOOL), blockTexture(Blocks.WHITE_WOOL));
        slabBlock(((SlabBlock) JDSlabs.ORANGE_WOOL_SLAB.get()), blockTexture(Blocks.ORANGE_WOOL), blockTexture(Blocks.ORANGE_WOOL));
        slabBlock(((SlabBlock) JDSlabs.MAGENTA_WOOL_SLAB.get()), blockTexture(Blocks.MAGENTA_WOOL), blockTexture(Blocks.MAGENTA_WOOL));
        slabBlock(((SlabBlock) JDSlabs.LIGHT_BLUE_WOOL_SLAB.get()), blockTexture(Blocks.LIGHT_BLUE_WOOL), blockTexture(Blocks.LIGHT_BLUE_WOOL));
        slabBlock(((SlabBlock) JDSlabs.YELLOW_WOOL_SLAB.get()), blockTexture(Blocks.YELLOW_WOOL), blockTexture(Blocks.YELLOW_WOOL));
        slabBlock(((SlabBlock) JDSlabs.LIME_WOOL_SLAB.get()), blockTexture(Blocks.LIME_WOOL), blockTexture(Blocks.LIME_WOOL));
        slabBlock(((SlabBlock) JDSlabs.PINK_WOOL_SLAB.get()), blockTexture(Blocks.PINK_WOOL), blockTexture(Blocks.PINK_WOOL));
        slabBlock(((SlabBlock) JDSlabs.GRAY_WOOL_SLAB.get()), blockTexture(Blocks.GRAY_WOOL), blockTexture(Blocks.GRAY_WOOL));
        slabBlock(((SlabBlock) JDSlabs.LIGHT_GRAY_WOOL_SLAB.get()), blockTexture(Blocks.LIGHT_GRAY_WOOL), blockTexture(Blocks.LIGHT_GRAY_WOOL));
        slabBlock(((SlabBlock) JDSlabs.CYAN_WOOL_SLAB.get()), blockTexture(Blocks.CYAN_WOOL), blockTexture(Blocks.CYAN_WOOL));
        slabBlock(((SlabBlock) JDSlabs.PURPLE_WOOL_SLAB.get()), blockTexture(Blocks.PURPLE_WOOL), blockTexture(Blocks.PURPLE_WOOL));
        slabBlock(((SlabBlock) JDSlabs.BLUE_WOOL_SLAB.get()), blockTexture(Blocks.BLUE_WOOL), blockTexture(Blocks.BLUE_WOOL));
        slabBlock(((SlabBlock) JDSlabs.BROWN_WOOL_SLAB.get()), blockTexture(Blocks.BROWN_WOOL), blockTexture(Blocks.BROWN_WOOL));
        slabBlock(((SlabBlock) JDSlabs.GREEN_WOOL_SLAB.get()), blockTexture(Blocks.GREEN_WOOL), blockTexture(Blocks.GREEN_WOOL));
        slabBlock(((SlabBlock) JDSlabs.RED_WOOL_SLAB.get()), blockTexture(Blocks.RED_WOOL), blockTexture(Blocks.RED_WOOL));
        slabBlock(((SlabBlock) JDSlabs.BLACK_WOOL_SLAB.get()), blockTexture(Blocks.BLACK_WOOL), blockTexture(Blocks.BLACK_WOOL));
        slabBlock(((SlabBlock) JDSlabs.CRACKED_NETHER_BRICKS_SLAB.get()), blockTexture(Blocks.CRACKED_NETHER_BRICKS), blockTexture(Blocks.CRACKED_NETHER_BRICKS));
        slabBlock(((SlabBlock) JDSlabs.CHISELED_NETHER_BRICKS_SLAB.get()), blockTexture(Blocks.CHISELED_NETHER_BRICKS), blockTexture(Blocks.CHISELED_NETHER_BRICKS));
        slabBlock(((SlabBlock) JDSlabs.CHISELED_RED_SANDSTONE_SLAB.get()), blockTexture(Blocks.CHISELED_RED_SANDSTONE), blockTexture(Blocks.CHISELED_RED_SANDSTONE));
        slabBlock(((SlabBlock) JDSlabs.CHISELED_SANDSTONE_SLAB.get()), blockTexture(Blocks.CHISELED_SANDSTONE), blockTexture(Blocks.CHISELED_SANDSTONE));
        slabBlock(((SlabBlock) JDSlabs.CHISELED_STONE_BRICKS_SLAB.get()), blockTexture(Blocks.CHISELED_STONE_BRICKS), blockTexture(Blocks.CHISELED_STONE_BRICKS));
        slabBlock(((SlabBlock) JDSlabs.CRACKED_STONE_BRICKS_SLAB.get()), blockTexture(Blocks.CRACKED_STONE_BRICKS), blockTexture(Blocks.CRACKED_STONE_BRICKS));
        slabBlock(((SlabBlock) JDSlabs.CRACKED_POLISHED_BLACKSTONE_BRICKS_SLAB.get()), blockTexture(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS), blockTexture(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS));
        slabBlock(((SlabBlock) JDSlabs.MOSS_BLOCK_SLAB.get()), blockTexture(Blocks.MOSS_BLOCK), blockTexture(Blocks.MOSS_BLOCK));
        slabBlock(((SlabBlock) JDSlabs.HONEYCOMB_BLOCK_SLAB.get()), blockTexture(Blocks.HONEYCOMB_BLOCK), blockTexture(Blocks.HONEYCOMB_BLOCK));
        slabBlock(((SlabBlock) JDSlabs.TERRACOTTA_SLAB.get()), blockTexture(Blocks.TERRACOTTA), blockTexture(Blocks.TERRACOTTA));
        slabBlock(((SlabBlock) JDSlabs.BLACK_TERRACOTTA_SLAB.get()), blockTexture(Blocks.BLACK_TERRACOTTA), blockTexture(Blocks.BLACK_TERRACOTTA));
        slabBlock(((SlabBlock) JDSlabs.BLUE_TERRACOTTA_SLAB.get()), blockTexture(Blocks.BLUE_TERRACOTTA), blockTexture(Blocks.BLUE_TERRACOTTA));
        slabBlock(((SlabBlock) JDSlabs.BROWN_TERRACOTTA_SLAB.get()), blockTexture(Blocks.BROWN_TERRACOTTA), blockTexture(Blocks.BROWN_TERRACOTTA));
        slabBlock(((SlabBlock) JDSlabs.CYAN_TERRACOTTA_SLAB.get()), blockTexture(Blocks.CYAN_TERRACOTTA), blockTexture(Blocks.CYAN_TERRACOTTA));
        slabBlock(((SlabBlock) JDSlabs.GRAY_TERRACOTTA_SLAB.get()), blockTexture(Blocks.GRAY_TERRACOTTA), blockTexture(Blocks.GRAY_TERRACOTTA));
        slabBlock(((SlabBlock) JDSlabs.GREEN_TERRACOTTA_SLAB.get()), blockTexture(Blocks.GREEN_TERRACOTTA), blockTexture(Blocks.GREEN_TERRACOTTA));
        slabBlock(((SlabBlock) JDSlabs.LIGHT_GRAY_TERRACOTTA_SLAB.get()), blockTexture(Blocks.LIGHT_GRAY_TERRACOTTA), blockTexture(Blocks.LIGHT_GRAY_TERRACOTTA));
        slabBlock(((SlabBlock) JDSlabs.LIGHT_BLUE_TERRACOTTA_SLAB.get()), blockTexture(Blocks.LIGHT_BLUE_TERRACOTTA), blockTexture(Blocks.LIGHT_BLUE_TERRACOTTA));
        slabBlock(((SlabBlock) JDSlabs.LIME_TERRACOTTA_SLAB.get()), blockTexture(Blocks.LIME_TERRACOTTA), blockTexture(Blocks.LIME_TERRACOTTA));
        slabBlock(((SlabBlock) JDSlabs.MAGENTA_TERRACOTTA_SLAB.get()), blockTexture(Blocks.MAGENTA_TERRACOTTA), blockTexture(Blocks.MAGENTA_TERRACOTTA));
        slabBlock(((SlabBlock) JDSlabs.ORANGE_TERRACOTTA_SLAB.get()), blockTexture(Blocks.ORANGE_TERRACOTTA), blockTexture(Blocks.ORANGE_TERRACOTTA));
        slabBlock(((SlabBlock) JDSlabs.PINK_TERRACOTTA_SLAB.get()), blockTexture(Blocks.PINK_TERRACOTTA), blockTexture(Blocks.PINK_TERRACOTTA));
        slabBlock(((SlabBlock) JDSlabs.PURPLE_TERRACOTTA_SLAB.get()), blockTexture(Blocks.PURPLE_TERRACOTTA), blockTexture(Blocks.PURPLE_TERRACOTTA));
        slabBlock(((SlabBlock) JDSlabs.RED_TERRACOTTA_SLAB.get()), blockTexture(Blocks.RED_TERRACOTTA), blockTexture(Blocks.RED_TERRACOTTA));
        slabBlock(((SlabBlock) JDSlabs.WHITE_TERRACOTTA_SLAB.get()), blockTexture(Blocks.WHITE_TERRACOTTA), blockTexture(Blocks.WHITE_TERRACOTTA));
        slabBlock(((SlabBlock) JDSlabs.YELLOW_TERRACOTTA_SLAB.get()), blockTexture(Blocks.YELLOW_TERRACOTTA), blockTexture(Blocks.YELLOW_TERRACOTTA));
        slabBlock(((SlabBlock) JDSlabs.BLACK_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.BLACK_CONCRETE_POWDER), blockTexture(Blocks.BLACK_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDSlabs.BLUE_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.BLUE_CONCRETE_POWDER), blockTexture(Blocks.BLUE_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDSlabs.BROWN_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.BROWN_CONCRETE_POWDER), blockTexture(Blocks.BROWN_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDSlabs.CYAN_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.CYAN_CONCRETE_POWDER), blockTexture(Blocks.CYAN_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDSlabs.GRAY_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.GRAY_CONCRETE_POWDER), blockTexture(Blocks.GRAY_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDSlabs.GREEN_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.GREEN_CONCRETE_POWDER), blockTexture(Blocks.GREEN_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDSlabs.LIGHT_BLUE_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.LIGHT_BLUE_CONCRETE_POWDER), blockTexture(Blocks.LIGHT_BLUE_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDSlabs.LIGHT_GRAY_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.LIGHT_GRAY_CONCRETE_POWDER), blockTexture(Blocks.LIGHT_GRAY_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDSlabs.LIME_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.LIME_CONCRETE_POWDER), blockTexture(Blocks.LIME_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDSlabs.MAGENTA_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.MAGENTA_CONCRETE_POWDER), blockTexture(Blocks.MAGENTA_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDSlabs.ORANGE_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.ORANGE_CONCRETE_POWDER), blockTexture(Blocks.ORANGE_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDSlabs.PINK_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.PINK_CONCRETE_POWDER), blockTexture(Blocks.PINK_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDSlabs.PURPLE_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.PURPLE_CONCRETE_POWDER), blockTexture(Blocks.PURPLE_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDSlabs.RED_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.RED_CONCRETE_POWDER), blockTexture(Blocks.RED_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDSlabs.WHITE_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.WHITE_CONCRETE_POWDER), blockTexture(Blocks.WHITE_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDSlabs.YELLOW_CONCRETE_POWDER_SLAB.get()), blockTexture(Blocks.YELLOW_CONCRETE_POWDER), blockTexture(Blocks.YELLOW_CONCRETE_POWDER));
        slabBlock(((SlabBlock) JDSlabs.BLACK_CONCRETE_SLAB.get()), blockTexture(Blocks.BLACK_CONCRETE), blockTexture(Blocks.BLACK_CONCRETE));
        slabBlock(((SlabBlock) JDSlabs.BLUE_CONCRETE_SLAB.get()), blockTexture(Blocks.BLUE_CONCRETE), blockTexture(Blocks.BLUE_CONCRETE));
        slabBlock(((SlabBlock) JDSlabs.BROWN_CONCRETE_SLAB.get()), blockTexture(Blocks.BROWN_CONCRETE), blockTexture(Blocks.BROWN_CONCRETE));
        slabBlock(((SlabBlock) JDSlabs.CYAN_CONCRETE_SLAB.get()), blockTexture(Blocks.CYAN_CONCRETE), blockTexture(Blocks.CYAN_CONCRETE));
        slabBlock(((SlabBlock) JDSlabs.GRAY_CONCRETE_SLAB.get()), blockTexture(Blocks.GRAY_CONCRETE), blockTexture(Blocks.GRAY_CONCRETE));
        slabBlock(((SlabBlock) JDSlabs.GREEN_CONCRETE_SLAB.get()), blockTexture(Blocks.GREEN_CONCRETE), blockTexture(Blocks.GREEN_CONCRETE));
        slabBlock(((SlabBlock) JDSlabs.LIGHT_BLUE_CONCRETE_SLAB.get()), blockTexture(Blocks.LIGHT_BLUE_CONCRETE), blockTexture(Blocks.LIGHT_BLUE_CONCRETE));
        slabBlock(((SlabBlock) JDSlabs.LIGHT_GRAY_CONCRETE_SLAB.get()), blockTexture(Blocks.LIGHT_GRAY_CONCRETE), blockTexture(Blocks.LIGHT_GRAY_CONCRETE));
        slabBlock(((SlabBlock) JDSlabs.LIME_CONCRETE_SLAB.get()), blockTexture(Blocks.LIME_CONCRETE), blockTexture(Blocks.LIME_CONCRETE));
        slabBlock(((SlabBlock) JDSlabs.MAGENTA_CONCRETE_SLAB.get()), blockTexture(Blocks.MAGENTA_CONCRETE), blockTexture(Blocks.MAGENTA_CONCRETE));
        slabBlock(((SlabBlock) JDSlabs.ORANGE_CONCRETE_SLAB.get()), blockTexture(Blocks.ORANGE_CONCRETE), blockTexture(Blocks.ORANGE_CONCRETE));
        slabBlock(((SlabBlock) JDSlabs.PINK_CONCRETE_SLAB.get()), blockTexture(Blocks.PINK_CONCRETE), blockTexture(Blocks.PINK_CONCRETE));
        slabBlock(((SlabBlock) JDSlabs.PURPLE_CONCRETE_SLAB.get()), blockTexture(Blocks.PURPLE_CONCRETE), blockTexture(Blocks.PURPLE_CONCRETE));
        slabBlock(((SlabBlock) JDSlabs.RED_CONCRETE_SLAB.get()), blockTexture(Blocks.RED_CONCRETE), blockTexture(Blocks.RED_CONCRETE));
        slabBlock(((SlabBlock) JDSlabs.WHITE_CONCRETE_SLAB.get()), blockTexture(Blocks.WHITE_CONCRETE), blockTexture(Blocks.WHITE_CONCRETE));
        slabBlock(((SlabBlock) JDSlabs.YELLOW_CONCRETE_SLAB.get()), blockTexture(Blocks.YELLOW_CONCRETE), blockTexture(Blocks.YELLOW_CONCRETE));

        //FENCES
        fenceBlock(((FenceBlock) JDFences.SPRUCE_LOG_FENCE.get()), blockTexture(Blocks.SPRUCE_LOG));
        fenceBlock(((FenceBlock) JDFences.OAK_LOG_FENCE.get()), blockTexture(Blocks.OAK_LOG));
        fenceBlock(((FenceBlock) JDFences.DARK_OAK_LOG_FENCE.get()), blockTexture(Blocks.DARK_OAK_LOG));
        fenceBlock(((FenceBlock) JDFences.ACACIA_LOG_FENCE.get()), blockTexture(Blocks.ACACIA_LOG));
        fenceBlock(((FenceBlock) JDFences.JUNGLE_LOG_FENCE.get()), blockTexture(Blocks.JUNGLE_LOG));
        fenceBlock(((FenceBlock) JDFences.BIRCH_LOG_FENCE.get()), blockTexture(Blocks.BIRCH_LOG));
        fenceBlock(((FenceBlock) JDFences.WARPED_LOG_FENCE.get()), blockTexture(Blocks.WARPED_HYPHAE));
        fenceBlock(((FenceBlock) JDFences.CRIMSON_LOG_FENCE.get()), blockTexture(Blocks.CRIMSON_HYPHAE));
        fenceBlock(((FenceBlock) JDFences.SPRUCE_SKINNED_LOG_FENCE.get()), blockTexture(Blocks.STRIPPED_SPRUCE_LOG));
        fenceBlock(((FenceBlock) JDFences.OAK_SKINNED_LOG_FENCE.get()), blockTexture(Blocks.STRIPPED_OAK_LOG));
        fenceBlock(((FenceBlock) JDFences.DARK_SKINNED_OAK_LOG_FENCE.get()), blockTexture(Blocks.STRIPPED_DARK_OAK_LOG));
        fenceBlock(((FenceBlock) JDFences.ACACIA_SKINNED_LOG_FENCE.get()), blockTexture(Blocks.STRIPPED_ACACIA_LOG));
        fenceBlock(((FenceBlock) JDFences.JUNGLE_SKINNED_LOG_FENCE.get()), blockTexture(Blocks.STRIPPED_JUNGLE_WOOD));
        fenceBlock(((FenceBlock) JDFences.BIRCH_SKINNED_LOG_FENCE.get()), blockTexture(Blocks.STRIPPED_BIRCH_LOG));
        fenceBlock(((FenceBlock) JDFences.WARPED_SKINNED_LOG_FENCE.get()), blockTexture(Blocks.STRIPPED_WARPED_HYPHAE));
        fenceBlock(((FenceBlock) JDFences.CRIMSON_SKINNED_LOG_FENCE.get()), blockTexture(Blocks.STRIPPED_CRIMSON_HYPHAE));

        //FENCE GATES
        fenceGateBlock(((FenceGateBlock) JDFenceGates.SPRUCE_LOG_FENCE_GATE.get()), blockTexture(Blocks.SPRUCE_LOG));
        fenceGateBlock(((FenceGateBlock) JDFenceGates.OAK_LOG_FENCE_GATE.get()), blockTexture(Blocks.OAK_LOG));
        fenceGateBlock(((FenceGateBlock) JDFenceGates.DARK_OAK_LOG_FENCE_GATE.get()), blockTexture(Blocks.DARK_OAK_LOG));
        fenceGateBlock(((FenceGateBlock) JDFenceGates.ACACIA_LOG_FENCE_GATE.get()), blockTexture(Blocks.ACACIA_LOG));
        fenceGateBlock(((FenceGateBlock) JDFenceGates.JUNGLE_LOG_FENCE_GATE.get()), blockTexture(Blocks.JUNGLE_LOG));
        fenceGateBlock(((FenceGateBlock) JDFenceGates.BIRCH_LOG_FENCE_GATE.get()), blockTexture(Blocks.BIRCH_LOG));
        fenceGateBlock(((FenceGateBlock) JDFenceGates.WARPED_LOG_FENCE_GATE.get()), blockTexture(Blocks.WARPED_HYPHAE));
        fenceGateBlock(((FenceGateBlock) JDFenceGates.CRIMSON_LOG_FENCE_GATE.get()), blockTexture(Blocks.CRIMSON_HYPHAE));
        fenceGateBlock(((FenceGateBlock) JDFenceGates.SPRUCE_SKINNED_LOG_FENCE_GATE.get()), blockTexture(Blocks.STRIPPED_SPRUCE_LOG));
        fenceGateBlock(((FenceGateBlock) JDFenceGates.OAK_SKINNED_LOG_FENCE_GATE.get()), blockTexture(Blocks.STRIPPED_OAK_LOG));
        fenceGateBlock(((FenceGateBlock) JDFenceGates.DARK_SKINNED_OAK_LOG_FENCE_GATE.get()), blockTexture(Blocks.STRIPPED_DARK_OAK_LOG));
        fenceGateBlock(((FenceGateBlock) JDFenceGates.ACACIA_SKINNED_LOG_FENCE_GATE.get()), blockTexture(Blocks.STRIPPED_ACACIA_LOG));
        fenceGateBlock(((FenceGateBlock) JDFenceGates.JUNGLE_SKINNED_LOG_FENCE_GATE.get()), blockTexture(Blocks.STRIPPED_JUNGLE_WOOD));
        fenceGateBlock(((FenceGateBlock) JDFenceGates.BIRCH_SKINNED_LOG_FENCE_GATE.get()), blockTexture(Blocks.STRIPPED_BIRCH_LOG));
        fenceGateBlock(((FenceGateBlock) JDFenceGates.WARPED_SKINNED_LOG_FENCE_GATE.get()), blockTexture(Blocks.STRIPPED_WARPED_HYPHAE));
        fenceGateBlock(((FenceGateBlock) JDFenceGates.CRIMSON_SKINNED_LOG_FENCE_GATE.get()), blockTexture(Blocks.STRIPPED_CRIMSON_HYPHAE));

        //WALLS
        wallBlock(((WallBlock) JDWalls.SPRUCE_LOG_WALL.get()), blockTexture(Blocks.SPRUCE_LOG));
        wallBlock(((WallBlock) JDWalls.OAK_LOG_WALL.get()), blockTexture(Blocks.OAK_LOG));
        wallBlock(((WallBlock) JDWalls.DARK_OAK_LOG_WALL.get()), blockTexture(Blocks.DARK_OAK_LOG));
        wallBlock(((WallBlock) JDWalls.ACACIA_LOG_WALL.get()), blockTexture(Blocks.ACACIA_LOG));
        wallBlock(((WallBlock) JDWalls.JUNGLE_LOG_WALL.get()), blockTexture(Blocks.JUNGLE_LOG));
        wallBlock(((WallBlock) JDWalls.BIRCH_LOG_WALL.get()), blockTexture(Blocks.BIRCH_LOG));
        wallBlock(((WallBlock) JDWalls.WARPED_LOG_WALL.get()), blockTexture(Blocks.WARPED_HYPHAE));
        wallBlock(((WallBlock) JDWalls.CRIMSON_LOG_WALL.get()), blockTexture(Blocks.CRIMSON_HYPHAE));
        wallBlock(((WallBlock) JDWalls.AMETHYST_WALL.get()), blockTexture(Blocks.AMETHYST_BLOCK));
        wallBlock(((WallBlock) JDWalls.CALCITE_WALL.get()), blockTexture(Blocks.CALCITE));
        wallBlock(((WallBlock) JDWalls.SPRUCE_SKINNED_LOG_WALL.get()), blockTexture(Blocks.STRIPPED_SPRUCE_LOG));
        wallBlock(((WallBlock) JDWalls.OAK_SKINNED_LOG_WALL.get()), blockTexture(Blocks.STRIPPED_OAK_LOG));
        wallBlock(((WallBlock) JDWalls.DARK_SKINNED_OAK_LOG_WALL.get()), blockTexture(Blocks.STRIPPED_DARK_OAK_LOG));
        wallBlock(((WallBlock) JDWalls.ACACIA_SKINNED_LOG_WALL.get()), blockTexture(Blocks.STRIPPED_ACACIA_LOG));
        wallBlock(((WallBlock) JDWalls.JUNGLE_SKINNED_LOG_WALL.get()), blockTexture(Blocks.STRIPPED_JUNGLE_LOG));
        wallBlock(((WallBlock) JDWalls.BIRCH_SKINNED_LOG_WALL.get()), blockTexture(Blocks.STRIPPED_BIRCH_LOG));
        wallBlock(((WallBlock) JDWalls.WARPED_SKINNED_LOG_WALL.get()), blockTexture(Blocks.STRIPPED_WARPED_HYPHAE));
        wallBlock(((WallBlock) JDWalls.CRIMSON_SKINNED_LOG_WALL.get()), blockTexture(Blocks.STRIPPED_CRIMSON_HYPHAE));
        wallBlock(((WallBlock) JDWalls.CLAY_WALL.get()), blockTexture(Blocks.CLAY));
        wallBlock(((WallBlock) JDWalls.GRAVEL_WALL.get()), blockTexture(Blocks.GRAVEL));
        wallBlock(((WallBlock) JDWalls.TUFF_WALL.get()), blockTexture(Blocks.TUFF));
        wallBlock(((WallBlock) JDWalls.SAND_WALL.get()), blockTexture(Blocks.SAND));
        wallBlock(((WallBlock) JDWalls.RED_SAND_WALL.get()), blockTexture(Blocks.RED_SAND));
        wallBlock(((WallBlock) JDWalls.DIRT_WALL.get()), blockTexture(Blocks.DIRT));
        wallBlock(((WallBlock) JDWalls.COARSE_DIRT_WALL.get()), blockTexture(Blocks.COARSE_DIRT));
        wallBlock(((WallBlock) JDWalls.ROOTED_DIRT_WALL.get()), blockTexture(Blocks.ROOTED_DIRT));
        wallBlock(((WallBlock) JDWalls.OBSIDIAN_WALL.get()), blockTexture(Blocks.OBSIDIAN));
        wallBlock(((WallBlock) JDWalls.CRYING_OBSIDIAN_WALL.get()), blockTexture(Blocks.CRYING_OBSIDIAN));
        wallBlock(((WallBlock) JDWalls.NETHERRACK_WALL.get()), blockTexture(Blocks.NETHERRACK));
        wallBlock(((WallBlock) JDWalls.END_STONE_WALL.get()), blockTexture(Blocks.END_STONE));
        wallBlock(((WallBlock) JDWalls.CHISELED_QUARTZ_WALL.get()), blockTexture(Blocks.CHISELED_QUARTZ_BLOCK));
        wallBlock(((WallBlock) JDWalls.QUARTZ_BRICKS_WALL.get()), blockTexture(Blocks.QUARTZ_BRICKS));
        wallBlock(((WallBlock) JDWalls.QUARTZ_PILLAR_WALL.get()), blockTexture(Blocks.QUARTZ_PILLAR));
        wallBlock(((WallBlock) JDWalls.BONE_BLOCK_WALL.get()), blockTexture(Blocks.BONE_BLOCK));
        wallBlock(((WallBlock) JDWalls.SMOOTH_BASALT_WALL.get()), blockTexture(Blocks.SMOOTH_BASALT));
        wallBlock(((WallBlock) JDWalls.BASALT_WALL.get()), blockTexture(Blocks.BASALT));
        wallBlock(((WallBlock) JDWalls.POLISHED_BASALT_WALL.get()), blockTexture(Blocks.POLISHED_BASALT));
        wallBlock(((WallBlock) JDWalls.WHITE_WOOL_WALL.get()), blockTexture(Blocks.WHITE_WOOL));
        wallBlock(((WallBlock) JDWalls.ORANGE_WOOL_WALL.get()), blockTexture(Blocks.ORANGE_WOOL));
        wallBlock(((WallBlock) JDWalls.MAGENTA_WOOL_WALL.get()), blockTexture(Blocks.MAGENTA_WOOL));
        wallBlock(((WallBlock) JDWalls.LIGHT_BLUE_WOOL_WALL.get()), blockTexture(Blocks.LIGHT_BLUE_WOOL));
        wallBlock(((WallBlock) JDWalls.YELLOW_WOOL_WALL.get()), blockTexture(Blocks.YELLOW_WOOL));
        wallBlock(((WallBlock) JDWalls.LIME_WOOL_WALL.get()), blockTexture(Blocks.LIME_WOOL));
        wallBlock(((WallBlock) JDWalls.PINK_WOOL_WALL.get()), blockTexture(Blocks.PINK_WOOL));
        wallBlock(((WallBlock) JDWalls.GRAY_WOOL_WALL.get()), blockTexture(Blocks.GRAY_WOOL));
        wallBlock(((WallBlock) JDWalls.LIGHT_GRAY_WOOL_WALL.get()), blockTexture(Blocks.LIGHT_GRAY_WOOL));
        wallBlock(((WallBlock) JDWalls.CYAN_WOOL_WALL.get()), blockTexture(Blocks.CYAN_WOOL));
        wallBlock(((WallBlock) JDWalls.PURPLE_WOOL_WALL.get()), blockTexture(Blocks.PURPLE_WOOL));
        wallBlock(((WallBlock) JDWalls.BLUE_WOOL_WALL.get()), blockTexture(Blocks.BLUE_WOOL));
        wallBlock(((WallBlock) JDWalls.BROWN_WOOL_WALL.get()), blockTexture(Blocks.BROWN_WOOL));
        wallBlock(((WallBlock) JDWalls.GREEN_WOOL_WALL.get()), blockTexture(Blocks.GREEN_WOOL));
        wallBlock(((WallBlock) JDWalls.RED_WOOL_WALL.get()), blockTexture(Blocks.RED_WOOL));
        wallBlock(((WallBlock) JDWalls.BLACK_WOOL_WALL.get()), blockTexture(Blocks.BLACK_WOOL));
        wallBlock(((WallBlock) JDWalls.CRACKED_NETHER_BRICKS_WALL.get()), blockTexture(Blocks.CRACKED_NETHER_BRICKS));
        wallBlock(((WallBlock) JDWalls.CHISELED_NETHER_BRICKS_WALL.get()), blockTexture(Blocks.CHISELED_NETHER_BRICKS));
        wallBlock(((WallBlock) JDWalls.CHISELED_RED_SANDSTONE_WALL.get()), blockTexture(Blocks.CHISELED_RED_SANDSTONE));
        wallBlock(((WallBlock) JDWalls.CHISELED_SANDSTONE_WALL.get()), blockTexture(Blocks.CHISELED_SANDSTONE));
        wallBlock(((WallBlock) JDWalls.CHISELED_STONE_BRICKS_WALL.get()), blockTexture(Blocks.CHISELED_STONE_BRICKS));
        wallBlock(((WallBlock) JDWalls.CRACKED_STONE_BRICKS_WALL.get()), blockTexture(Blocks.CRACKED_STONE_BRICKS));
        wallBlock(((WallBlock) JDWalls.CRACKED_POLISHED_BLACKSTONE_BRICKS_WALL.get()), blockTexture(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS));
        wallBlock(((WallBlock) JDWalls.MOSS_BLOCK_WALL.get()), blockTexture(Blocks.MOSS_BLOCK));
        wallBlock(((WallBlock) JDWalls.HONEYCOMB_BLOCK_WALL.get()), blockTexture(Blocks.HONEYCOMB_BLOCK));
        wallBlock(((WallBlock) JDWalls.TERRACOTTA_WALL.get()), blockTexture(Blocks.TERRACOTTA));
        wallBlock(((WallBlock) JDWalls.BLACK_TERRACOTTA_WALL.get()), blockTexture(Blocks.BLACK_TERRACOTTA));
        wallBlock(((WallBlock) JDWalls.BLUE_TERRACOTTA_WALL.get()), blockTexture(Blocks.BLUE_TERRACOTTA));
        wallBlock(((WallBlock) JDWalls.BROWN_TERRACOTTA_WALL.get()), blockTexture(Blocks.BROWN_TERRACOTTA));
        wallBlock(((WallBlock) JDWalls.CYAN_TERRACOTTA_WALL.get()), blockTexture(Blocks.CYAN_TERRACOTTA));
        wallBlock(((WallBlock) JDWalls.GRAY_TERRACOTTA_WALL.get()), blockTexture(Blocks.GRAY_TERRACOTTA));
        wallBlock(((WallBlock) JDWalls.GREEN_TERRACOTTA_WALL.get()), blockTexture(Blocks.GREEN_TERRACOTTA));
        wallBlock(((WallBlock) JDWalls.LIGHT_GRAY_TERRACOTTA_WALL.get()), blockTexture(Blocks.LIGHT_GRAY_TERRACOTTA));
        wallBlock(((WallBlock) JDWalls.LIGHT_BLUE_TERRACOTTA_WALL.get()), blockTexture(Blocks.LIGHT_BLUE_TERRACOTTA));
        wallBlock(((WallBlock) JDWalls.LIME_TERRACOTTA_WALL.get()), blockTexture(Blocks.LIME_TERRACOTTA));
        wallBlock(((WallBlock) JDWalls.MAGENTA_TERRACOTTA_WALL.get()), blockTexture(Blocks.MAGENTA_TERRACOTTA));
        wallBlock(((WallBlock) JDWalls.ORANGE_TERRACOTTA_WALL.get()), blockTexture(Blocks.ORANGE_TERRACOTTA));
        wallBlock(((WallBlock) JDWalls.PINK_TERRACOTTA_WALL.get()), blockTexture(Blocks.PINK_TERRACOTTA));
        wallBlock(((WallBlock) JDWalls.PURPLE_TERRACOTTA_WALL.get()), blockTexture(Blocks.PURPLE_TERRACOTTA));
        wallBlock(((WallBlock) JDWalls.RED_TERRACOTTA_WALL.get()), blockTexture(Blocks.RED_TERRACOTTA));
        wallBlock(((WallBlock) JDWalls.WHITE_TERRACOTTA_WALL.get()), blockTexture(Blocks.WHITE_TERRACOTTA));
        wallBlock(((WallBlock) JDWalls.YELLOW_TERRACOTTA_WALL.get()), blockTexture(Blocks.YELLOW_TERRACOTTA));
        wallBlock(((WallBlock) JDWalls.BLACK_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.BLACK_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDWalls.BLUE_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.BLUE_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDWalls.BROWN_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.BROWN_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDWalls.CYAN_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.CYAN_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDWalls.GRAY_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.GRAY_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDWalls.GREEN_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.GREEN_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDWalls.LIGHT_BLUE_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.LIGHT_BLUE_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDWalls.LIGHT_GRAY_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.LIGHT_GRAY_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDWalls.LIME_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.LIME_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDWalls.MAGENTA_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.MAGENTA_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDWalls.ORANGE_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.ORANGE_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDWalls.PINK_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.PINK_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDWalls.PURPLE_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.PURPLE_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDWalls.RED_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.RED_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDWalls.WHITE_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.WHITE_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDWalls.YELLOW_CONCRETE_POWDER_WALL.get()), blockTexture(Blocks.YELLOW_CONCRETE_POWDER));
        wallBlock(((WallBlock) JDWalls.BLACK_CONCRETE_WALL.get()), blockTexture(Blocks.BLACK_CONCRETE));
        wallBlock(((WallBlock) JDWalls.BLUE_CONCRETE_WALL.get()), blockTexture(Blocks.BLUE_CONCRETE));
        wallBlock(((WallBlock) JDWalls.BROWN_CONCRETE_WALL.get()), blockTexture(Blocks.BROWN_CONCRETE));
        wallBlock(((WallBlock) JDWalls.CYAN_CONCRETE_WALL.get()), blockTexture(Blocks.CYAN_CONCRETE));
        wallBlock(((WallBlock) JDWalls.GRAY_CONCRETE_WALL.get()), blockTexture(Blocks.GRAY_CONCRETE));
        wallBlock(((WallBlock) JDWalls.GREEN_CONCRETE_WALL.get()), blockTexture(Blocks.GREEN_CONCRETE));
        wallBlock(((WallBlock) JDWalls.LIGHT_BLUE_CONCRETE_WALL.get()), blockTexture(Blocks.LIGHT_BLUE_CONCRETE));
        wallBlock(((WallBlock) JDWalls.LIGHT_GRAY_CONCRETE_WALL.get()), blockTexture(Blocks.LIGHT_GRAY_CONCRETE));
        wallBlock(((WallBlock) JDWalls.LIME_CONCRETE_WALL.get()), blockTexture(Blocks.LIME_CONCRETE));
        wallBlock(((WallBlock) JDWalls.MAGENTA_CONCRETE_WALL.get()), blockTexture(Blocks.MAGENTA_CONCRETE));
        wallBlock(((WallBlock) JDWalls.ORANGE_CONCRETE_WALL.get()), blockTexture(Blocks.ORANGE_CONCRETE));
        wallBlock(((WallBlock) JDWalls.PINK_CONCRETE_WALL.get()), blockTexture(Blocks.PINK_CONCRETE));
        wallBlock(((WallBlock) JDWalls.PURPLE_CONCRETE_WALL.get()), blockTexture(Blocks.PURPLE_CONCRETE));
        wallBlock(((WallBlock) JDWalls.RED_CONCRETE_WALL.get()), blockTexture(Blocks.RED_CONCRETE));
        wallBlock(((WallBlock) JDWalls.WHITE_CONCRETE_WALL.get()), blockTexture(Blocks.WHITE_CONCRETE));
        wallBlock(((WallBlock) JDWalls.YELLOW_CONCRETE_WALL.get()), blockTexture(Blocks.YELLOW_CONCRETE));
        wallBlock(((WallBlock) JDWalls.MANGROVE_PLANK_WALL.get()), blockTexture(Blocks.MANGROVE_PLANKS));
        wallBlock(((WallBlock) JDWalls.OAK_PLANK_WALL.get()), blockTexture(Blocks.OAK_PLANKS));
        wallBlock(((WallBlock) JDWalls.DARK_OAK_PLANK_WALL.get()), blockTexture(Blocks.DARK_OAK_PLANKS));
        wallBlock(((WallBlock) JDWalls.SPRUCE_PLANK_WALL.get()), blockTexture(Blocks.SPRUCE_PLANKS));
        wallBlock(((WallBlock) JDWalls.JUNGLE_PLANK_WALL.get()), blockTexture(Blocks.JUNGLE_PLANKS));
        wallBlock(((WallBlock) JDWalls.ACACIA_PLANK_WALL.get()), blockTexture(Blocks.ACACIA_PLANKS));
        wallBlock(((WallBlock) JDWalls.BIRCH_PLANK_WALL.get()), blockTexture(Blocks.BIRCH_PLANKS));
        wallBlock(((WallBlock) JDWalls.CRIMSON_PLANK_WALL.get()), blockTexture(Blocks.CRIMSON_PLANKS));
        wallBlock(((WallBlock) JDWalls.WARPED_PLANK_WALL.get()), blockTexture(Blocks.WARPED_PLANKS));
        wallBlock(((WallBlock) JDWalls.MANGROVE_LOG_WALL.get()), blockTexture(Blocks.MANGROVE_LOG));
        wallBlock(((WallBlock) JDWalls.PACKED_MUD_WALL.get()), blockTexture(Blocks.PACKED_MUD));
        wallBlock(((WallBlock) JDWalls.MUDDY_MANGROVE_ROOTS_WALL.get()), blockTexture(Blocks.MUDDY_MANGROVE_ROOTS));
        wallBlock(((WallBlock) JDWalls.STRIPPED_MANGROVE_LOG_WALL.get()), blockTexture(Blocks.STRIPPED_MANGROVE_LOG));
        wallBlock(((WallBlock) JDWalls.MUD_WALL.get()), blockTexture(Blocks.MUD));
        wallBlock(((WallBlock) JDWalls.OCHRE_FROGLIGHT_WALL.get()), blockTexture(Blocks.OCHRE_FROGLIGHT));
        wallBlock(((WallBlock) JDWalls.VERDANT_FROGLIGHT_WALL.get()), blockTexture(Blocks.VERDANT_FROGLIGHT));
        wallBlock(((WallBlock) JDWalls.PEARLESCENT_FROGLIGHT_WALL.get()), blockTexture(Blocks.PEARLESCENT_FROGLIGHT));

    }

    private void blockWithItem(RegistryObject<Block> blockRegistryObject) {
        simpleBlockWithItem(blockRegistryObject.get(), cubeAll(blockRegistryObject.get()));
    }
}